### PR TITLE
#8523 Add alwaysRender property

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description

This PR introduces a new property for the Plugins API to make a contained plugin always rendered skipping the priority property

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**

#8523

**What is the new behavior?**

This PR introduces a new `alwaysRender` property for the Plugins API 

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [x] No

### CODE REVIEW

**Comment by offtherailz** [comment]
It should solve a lot of issues with priority. I should use `alwaysRender` (imperative).
Tests are failing, anyway, once documented, it could be good to me
Summarizing:
- `doNotHide`: does not hide the main component if the component is rendered in the container (in this case the name was confusing, it means `doNotHideMainComponent`,but we need to maintain it)
- `alwaysRender`: always renders the component in the given containier, regardless the priority

correct?

**Comment by allyoucanmap** [comment]
> It should solve a lot of issues with priority. I should use `alwaysRender` (imperative). Tests are failing, anyway, once documented, it could be good to me Summarizing:
> 
> * `doNotHide`: does not hide the main component if the component is rendered in the container (in this case the name was confusing, it means `doNotHideMainComponent`,but we need to maintain it)
> * `alwaysRender`: always renders the component in the given containier, regardless the priority
> 
> correct?

@offtherailz 
Yes, correct, ok I'm going to fix the PR, thanks

**Comment by tdipisa** [comment]
@offtherailz we need a review for this. That's needed for 2022.02.01.

**Review by offtherailz — APPROVED** [review]

**Comment by tdipisa** [comment]
@ElenaGallo please check in DEV and let us know if we ca backport to 2022.02.xx and 2022.02.xx-c040.

**Comment by ElenaGallo** [comment]
Hi @allyoucanmap, now the Map View button on the sidebar cover the burger menu. See [this context](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/11).

nnnn

**Comment by allyoucanmap** [comment]
> Hi @allyoucanmap, now the Map View button on the sidebar cover the burger menu. See [this context](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/11).

Hi @ElenaGallo , why do we need to include burger menu in that context? (cc @tdipisa)
image

**Comment by tdipisa** [comment]
@ElenaGallo please open a dedicated issue for this.

**Comment by ElenaGallo** [comment]
New issue [here](https://github.com/geosolutions-it/MapStore2/issues/8783). @allyoucanmap please backport this pr. Thanks

**Comment by tdipisa** [comment]
@allyoucanmap @ElenaGallo correction: this need to be backported only to  2022.02.xx-c040.

**Pull request merged**
