### PR TITLE
Fix 4274 Annotations circle has problem with radius

### PR DESCRIPTION
**Pull request by kasongoyo**
## Description
Fix annotations circle when changing radius or coordinates, a bug which caused by https://github.com/geosolutions-it/MapStore2/pull/4131. This PR restore some code which was removed by 4131 and apply fix which work for both 4274 and 3842

## Issues
 - #4274 
 - ...

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
see #4274 

**What is the new behavior?**
The circle change smoothly

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by MV88** [comment]
@kasongoyo Please, pay more attention before submitting a PR because you have not fixed completely the original problems
4274annotation circle problems

- The circle should remain the same size when changing lat lon from the form
- and if you change 1 meter it should not grow
@offtherailz do you confirm this?

**Comment by kasongoyo** [comment]
@MV88 
The value you saw in the radius form field is the one returned by geometry.getRadius() in drawend event. So do you mean that if projection is 4326 then that value should be in degree units instead of meters? I think all value returned by geometry.getRadius https://github.com/geosolutions-it/MapStore2/blob/dda8563b7a3bdd7b52fac7f9a3475d7f732bebab/web/client/components/map/openlayers/DrawSupport.jsx#L417 are in meters ?

**Comment by offtherailz** [comment]
Actually the form shows the uom in meters, therefore you should show the number consistent with the UOM.

In the actual implementation the circle annotation is a circle in the projected system, therefore if I change the projection it should change it's shape. it doesn't happenm so it is a little inconstistent per se.
Peek 2019-11-15 15-30

For the moment convert the UOM accordingly for the selector. @MV88 please take note of this.

**Comment by offtherailz** [comment]
any news about this PR?

**Comment by offtherailz** [comment]
I'm reviewing this PR. Now I have to switch to another task. I report my observations. 
In fact the radius problem is also a problem of the Filter Panel (radius becomes in degrees, but the form indicates it's in meters. So I think we can open a separate issue to fix UOM indicated 

I'd like to clarify : 
 - [ ] Still didn't understand 1000 division or multiplication issue. @kasongoyo can you please explain, even in code, why that operation is present?
 - [ ] I found this issue, not sure is new moving the circle in invalid coordinates and then back to valid. Couldn't replicate in dev but couldn't investigate too much.  
Peek 2019-11-27 11-12

When these two points are clarified, we can merge (opening the issue for radius fix in both query panel and annotations panel) because the issue is solved. 
Any comment @MV88 ?

**Comment by kasongoyo** [comment]
> Still didn't understand 1000 division or multiplication issue. @kasongoyo can you please explain, even in code, why that operation is present?

The unit parameter is missing in [turf/circle](https://www.npmjs.com/package/@turf/circle) library used to generate circle coordinates [here](https://github.com/geosolutions-it/MapStore2/blob/bfe9a4edb9f653b823a3c3ab6ed902d6fc08ad74/web/client/reducers/annotations.js#L96) so it means the turf/circle use default unit which is `kilometers` and map in `3857` projection report the distance in `meters` so there was a need to convert the reported radius in meter to kilometers to enable turf/circle to produce accurate coordinates. 

I agree with you @offtherailz  that we should open a new issue to address distance calculation and conversion when a map is in `4326` projection and actually, this is what I suggested to @tdipisa well the issue is when the map is in `4326` projection it's by default report distance in degrees, turf/circle support radius in a degree so the issue could be easily solved changing unit parameter to degrees when projection is in `4326` but the annotation form does not support degrees among the units of measurements and it's difficult to change between degrees to other units used in annotation form.

**Comment by offtherailz** [comment]
Agree. Please : 
 - [ ] Please open an issue about UOM conversion with your observations and also the problem in filter panel (in 4326 it reports degrees but indicates `m` as unit of measure. When the specification about what we should do for radius in 4326 in annotations is clear. Some alternatives: 
    - convert implicitly in the UI from meeters to degrees (it may not work with every projection)
    - adding degrees to uoms and denying conversion in that case... it could be more general solution
    - other...
- [ ] Please comment the code to quote the reason of multiplication / division by 1000 
image

**Comment by MV88** [comment]
@offtherailz i agree with you.
So, this pr can be merged and a new issue is needed for the other use cases mentioned by you.
@kasongoyo please follow Lorenzo's suggestions

**Comment by offtherailz** [comment]
Just to have a complete panorama, now we have the same behavior of annotations "view" mode, as discussed here: 
https://github.com/geosolutions-it/MapStore2/pull/4167

Reprojecting circles (as ellipse, oval...) can be a  future task but not part of this issue.

**Comment by tdipisa** [comment]
@offtherailz so can we merge this? If yes please approve

**Comment by kasongoyo** [comment]
see #4577

**Pull request merged**
