### PR TITLE
#8745 Date-time picker for date-time/date/time attributes on feature editor

### PR DESCRIPTION
**Pull request by alex-fko**
## Description
This PR adds date-time picker for date-time/date/time attributes on feature editor.
It also provides a few handy options to existing DateTimePicker component to make it usable not only for filters, but also for data editing:
- Control over popup position with dates and time.
- Ability to skip hours change upon date selection. By default it picks current time upon date change, but if this behavior is disabled via option - existing time will be kept upon date selection.

DateTimeEditor for featuregrid supports three possible data types: date-time, date, time. In all the cases it expects data to be ISO 8601 formatted (https://www.w3.org/TR/NOTE-datetime)

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
#8745 

**What is the new behavior?**
Date-time picker is available for date, time and date-time attribute types.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information
image

### CODE REVIEW

**Comment by alex-fko** [comment]
Handy links useful for testing:
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/new?addLayers=mapstore:Types (time values looks to be broken in data samples)
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/new?addLayers=mapstore:Meteorite_Landings_from_NASA_Open_Data_Portal

**Review by allyoucanmap — CHANGES_REQUESTED** [review]
The code seems fine but after testing I found out following issue:

- [x] double click on an empty date, time or date-time field will crash the app

https://user-images.githubusercontent.com/19175505/200004882-8b73256c-612b-4d9f-8b99-33dbfb9fdc45.mp4

Other findings to discuss with @tdipisa before proceed

- [ ] the picker has a minimum year set to 1900. I think the only way to set a date before  the 1900 is to manually type it. I'm not sure we need this on most of the cases, I only found out it because of the Meteorites layer that has years before 1900

image

- [ ] time column starts as date-time format in the UI and it changes only after clicking in the field to edit it

https://user-images.githubusercontent.com/19175505/200008273-6f26adb9-2c6c-44e2-a453-89f5152f434c.mp4

**Comment by alex-fko** [comment]
Added checks to make it behave properly if initial value is empty.

> the picker has a minimum year set to 1900. I think the only way to set a date before the 1900 is to manually type it. I'm not sure we need this on most of the cases, I only found out it because of the Meteorites layer that has years before 1900

@allyoucanmap @tdipisa it actually configurable for Calendar widget. Min/max values can be set to any date. It could become a part of the `FeatureEditor` plugin configuration, allowing user to override defaults for minimum and maximum years (1900-2099)

**Review by allyoucanmap — CHANGES_REQUESTED** [review]
Code seems fine and the empty cell bug has been fixed, the only issue I see is the highlight of empty cells event if they are not changed:

https://user-images.githubusercontent.com/19175505/200610039-9663be92-863d-4839-a40f-b58ca0a5c11a.mp4

**Review by allyoucanmap — APPROVED** [review]

**Comment by allyoucanmap** [comment]
@ElenaGallo please test on dev and let us know if we can backport, thanks

**Comment by alex-fko** [comment]
@ElenaGallo This doesn't seem to be related to the changes in PR, I can reproduce it on QA too (exported dashboard from dev and imported into QA). I'll create an issue for it.

**Comment by tdipisa** [comment]
@ElenaGallo after the test a backport to 2022.02.xx-c040 is needed

**Comment by ElenaGallo** [comment]
Test passed on DEV, @alex-fko please backport to 2022.02.xx-c040

**Pull request merged**
