### PR TITLE
#9219 - Allow to configure hidden columns in featuregrid

### PR DESCRIPTION
**Pull request by dsuren1**
## Description
This PR allows user to save feature grid columns upon map save and to user session when plugin enabled

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Feature

## Issue

**What is the current behavior?**
- #9219 

**What is the new behavior?**
User can save the feature grid column configuration
- On map save
- To user session

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by offtherailz — APPROVED** [review]

**Comment by tdipisa** [comment]
@ElenaGallo please test this in DEV with priority and let us know.

**Comment by ElenaGallo** [comment]
@dsuren1 If I hide some columns in the attribute table of a layer and then save the map, opening another map the layer will have the same hidden columns in the attribute table.


https://github.com/geosolutions-it/MapStore2/assets/56537133/0f3d21dd-28e8-4425-a8d2-2899e2a166a5

**Comment by dsuren1** [comment]
@ElenaGallo Let me check

**Comment by dsuren1** [comment]
@ElenaGallo I believe this is an existing issue. You can check in qa do everything without saving map instead leave the map and open a new map with same layer and check. The problem is caused by featuregrid state is maintained between map and navigation. 

Kindly let me know if should be fixed as part of this issue @tdipisa ?

**Comment by ElenaGallo** [comment]
@dsuren1 @tdipisa  I also saw that there is the same issue on QA

**Comment by tdipisa** [comment]
> @dsuren1 @tdipisa I also saw that there is the same issue on QA

@ElenaGallo therefore it the issue is not related. Please open a new issue and assign this to me. We will schedule it separately @dsuren1

**Comment by ElenaGallo** [comment]
The new issue is #9229

**Pull request merged**
