### PR TITLE
Dependency updates for mapstore-services and POMs refactoring

### PR DESCRIPTION
**Pull request by tdipisa**
## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [x] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#<issue>

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by tdipisa — COMMENTED** [review]
@afabiani we have opened this PR to contribute what you have done for [c125-2024.01.xx](https://github.com/geosolutions-it/MapStore2/tree/c125-2024.01.xx) branch in master. Some conflicts have been fixed as well.

Can you please double check the PR? Can you also please explain better the purpose of this contribution?

**Comment by afabiani** [comment]
Done

**Comment by tdipisa** [comment]
@offtherailz this PR should be backported to 2024.01.xx but using versions (of geostore, proxy, services and print) expected for the stable branch.

**Review by offtherailz — COMMENTED** [review]
I'm going to apply my changes and test.

**Pull request merged**
