### PR TITLE
Update to log4j2

### PR DESCRIPTION
**Pull request by taba90**
## Description

This pr:
- updated dependencies from log4j to log4j2.
- migrates log4j.properties to log4j2.properties
- add depedency management when needed in the various pom.xml to force versions avoiding duplicated, conflicting dependencies.

Blocked by:
- [x] https://github.com/geosolutions-it/geostore/pull/316
- [x] https://github.com/geosolutions-it/mapfish-print/pull/59
- [x] https://github.com/geosolutions-it/http-proxy/pull/68

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [x] Refactoring (no functional changes, no api changes)
 - [x] Build related changes
 - [ ] CI related changes
 - [x] Other... Please describe:

## Issue

**What is the current behavior?**

#<issue>

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
- [ ] I see we renamed and changed the format of the configuration of the files. I think we need some migration guidelines to:
    - [ ] change our configuration  from log4j to log4j2 
    - [ ] Properly name and place the files
- [ ] The `web/pom.xml` has some `packageExcludes` that remove jars for `slf4j`. Are these needed anymore (once the http-proxy and goestore are updated?


The new output of `mapstore.log` is very compact. Is it desired (I like it personally). I don't know if this is caused by the fact that I don't have geostore updated yet or what.

I tried this request 
```
curl 'http://localhost:8080/mapstore/rest/geostore/data/14' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'Accept-Language: en-US,en;q=0.9,it-IT;q=0.8,it;q=0.7' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: ys-search=o%3AsearchTab%3Ds%253Adefault' \
  -H 'Pragma: no-cache' \
  -H 'Sec-Fetch-Dest: document' \
  -H 'Sec-Fetch-Mode: navigate' \
  -H 'Sec-Fetch-Site: none' \
  -H 'Sec-Fetch-User: ?1' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="107", "Chromium";v="107", "Not=A?Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  --compressed
```
and I had no log. I think because we don't have the geostore log until I properly build it with recent changes, isn't it?
```
INFO   2022-11-24 09:44:25.076   ContextLoader.initWebApplicationContext() - Root WebApplicationContext: initialization started 
INFO   2022-11-24 09:44:25.769   SpringSecurityCoreVersion.performVersionChecks() - You are running with Spring Security Core 5.3.10.RELEASE 
INFO   2022-11-24 09:44:25.773   SecurityNamespaceHandler.<init>() - Spring Security 'config' module version is 5.3.10.RELEASE 
INFO   2022-11-24 09:44:25.857   AuthenticationConfigBuilder.createLoginPageFilterIfNeeded() - No login page configured. The default internal one will be used. Use the 'login-page' attribute to set the URL of the login page. 
INFO   2022-11-24 09:44:25.862   HttpSecurityBeanDefinitionParser.checkFilterChainOrder() - Checking sorted filter chain: [Root bean: class [org.springframework.security.web.context.SecurityContextPersistenceFilter]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 200, Root bean: class [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 400, Root bean: class [org.springframework.security.web.header.HeaderWriterFilter]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 500, Root bean: class [org.springframework.security.web.authentication.logout.LogoutFilter]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 800, <authenticationTokenProcessingFilter>, order = 1399, <org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter#0>, order = 1400, <sessionTokenProcessingFilter>, order = 1401, Root bean: class [org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 1600, Root bean: class [org.springframework.security.web.authentication.ui.DefaultLogoutPageGeneratingFilter]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 1700, <keycloakFilter>, order = 1999, Root bean: class [org.springframework.security.web.authentication.www.BasicAuthenticationFilter]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 2000, <googleOpenIdFilter>, order = 2001, Root bean: class [org.springframework.security.web.savedrequest.RequestCacheAwareFilter]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 2100, Root bean: class [null]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.security.config.http.HttpConfigurationBuilder$SecurityContextHolderAwareRequestFilterBeanFactory#0; factoryMethodName=getBean; initMethodName=null; destroyMethodName=null, order = 2200, Root bean: class [org.springframework.security.web.authentication.AnonymousAuthenticationFilter]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 2500, Root bean: class [org.springframework.security.web.session.SessionManagementFilter]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 2700, Root bean: class [org.springframework.security.web.access.ExceptionTranslationFilter]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null, order = 2800, <org.springframework.security.web.access.intercept.FilterSecurityInterceptor#0>, order = 2900] 
INFO   2022-11-24 09:44:27.111   LogHelper.logPersistenceUnitInformation() - HHH000204: Processing PersistenceUnitInfo [name: geostore] 
INFO   2022-11-24 09:44:27.247   Version.logVersion() - HHH000412: Hibernate ORM core version 5.4.33.Final 
WARN   2022-11-24 09:44:27.506   EhcacheRegionFactory.<init>() - HHH020100: The Ehcache second-level cache provider for Hibernate is deprecated.  See https://hibernate.atlassian.net/browse/HHH-12441 for details. 
INFO   2022-11-24 09:44:27.531   JavaReflectionManager.<clinit>() - HCANN000001: Hibernate Commons Annotations {5.1.2.Final} 
INFO   2022-11-24 09:44:28.073   Dialect.<init>() - HHH000400: Using dialect: org.hibernate.dialect.H2Dialect 
INFO   2022-11-24 09:44:29.459   JtaPlatformInitiator.initiateService() - HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform] 
INFO   2022-11-24 09:44:29.478   AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory() - Initialized JPA EntityManagerFactory for persistence unit 'geostore' 
INFO   2022-11-24 09:44:32.682   DefaultSecurityFilterChain.<init>() - Creating filter chain: any request, [org.springframework.security.web.context.SecurityContextPersistenceFilter@45ef3d69, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@56aae289, org.springframework.security.web.header.HeaderWriterFilter@1fa6fd05, org.springframework.security.web.authentication.logout.LogoutFilter@21cba5a7, it.geosolutions.geostore.services.rest.security.UserAttributeTokenAuthenticationFilter@285ae556, org.springframework.security.web.authentication.UsernamePasswordAuthenticationFilter@614b050d, it.geosolutions.geostore.services.rest.security.SessionTokenAuthenticationFilter@1122ad40, org.springframework.security.web.authentication.ui.DefaultLoginPageGeneratingFilter@7f219e1d, org.springframework.security.web.authentication.ui.DefaultLogoutPageGeneratingFilter@f4b81c4, it.geosolutions.geostore.services.rest.security.keycloak.KeyCloakFilter@23d5a95, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@3673d3, it.geosolutions.geostore.services.rest.security.oauth2.OpenIdFilter@3125000b, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@34d6168, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@4fc324d6, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@1223bfd1, org.springframework.security.web.session.SessionManagementFilter@39f8fa29, org.springframework.security.web.access.ExceptionTranslationFilter@34d7b464, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@29b73179] 
INFO   2022-11-24 09:44:33.226   ContextLoader.initWebApplicationContext() - Root WebApplicationContext initialized in 8142 ms 
INFO   2022-11-24 09:44:33.496   FrameworkServlet.initServletBean() - Initializing Servlet 'loadAssets' 
INFO   2022-11-24 09:44:33.541   SecurityNamespaceHandler.<init>() - Spring Security 'config' module version is 5.3.10.RELEASE 
INFO   2022-11-24 09:44:34.266   FrameworkServlet.initServletBean() - Completed initialization in 769 ms 
INFO   2022-11-24 09:44:34.266   FrameworkServlet.initServletBean() - Initializing Servlet 'configs' 
INFO   2022-11-24 09:44:34.284   SecurityNamespaceHandler.<init>() - Spring Security 'config' module version is 5.3.10.RELEASE 
INFO   2022-11-24 09:44:34.367   FrameworkServlet.initServletBean() - Completed initialization in 101 ms 
INFO   2022-11-24 09:44:34.368   FrameworkServlet.initServletBean() - Initializing Servlet 'extensions' 
INFO   2022-11-24 09:44:34.385   SecurityNamespaceHandler.<init>() - Spring Security 'config' module version is 5.3.10.RELEASE 
INFO   2022-11-24 09:44:34.474   FrameworkServlet.initServletBean() - Completed initialization in 106 ms 
WARN   2022-11-24 09:55:07.806   QueryTranslatorImpl.list() - HHH000104: firstResult/maxResults specified with collection fetch; applying in memory! 
WARN   2022-11-24 09:55:07.805   QueryTranslatorImpl.list() - HHH000104: firstResult/maxResults specified with collection fetch; applying in memory! 
WARN   2022-11-24 09:55:07.805   QueryTranslatorImpl.list() - HHH000104: firstResult/maxResults specified with collection fetch; applying in memory! 
WARN   2022-11-24 09:55:07.813   QueryTranslatorImpl.list() - HHH000104: firstResult/maxResults specified with collection fetch; applying in memory! 
WARN   2022-11-24 09:55:07.970   QueryTranslatorImpl.list() - HHH000104: firstResult/maxResults specified with collection fetch; applying in memory! 
```

I see dependency management is not shared between all modules yet, but it is a beginning. I think we should do an additional step for it. 

**Note**: I don't know recent evolution of this  #8685 . After these changes, getting back to a prior version of http-proxy may be problematic. @tdipisa we should also solve the known issues of the proxy on the master branch too.

**Comment by taba90** [comment]
@offtherailz thanks for your review. Feedback have been applied. 
Until the pr on the other project is not merged or all the involved depedencies are build in your local system, yes log4j2 settings will not properly work.

**Review by offtherailz — COMMENTED** [review]
LGTM. We have to wait the other PR to merge this and test.

**Comment by taba90** [comment]
@offtherailz thanks for the review, all the other pr have been merged and the artifacts published on the repo. If you approve here I'll merge this as well.

**Review by offtherailz — APPROVED** [review]

**Pull request merged**
