### PR TITLE
Add Zoom to Layer Dashboard map widget

### PR DESCRIPTION
**Pull request by kasongoyo**
## Description
Add Zoom to Layer tool in Dashboard map widget

This PR is blocked by some regression introduced by https://github.com/geosolutions-it/MapStore2/pull/4278.   

## Issues
 - #3533 
 - ...

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
see #3533 

**What is the new behavior?**
Zoom to layer tool added

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by kasongoyo** [comment]
@offtherailz Can you look at this PR and comment about the issue we talked in the chat.

**Comment by kasongoyo** [comment]
@offtherailz I have discovered that my fix doesn't work smoothly because of the changes introduced by this PR https://github.com/geosolutions-it/MapStore2/pull/4278. I have tried to apply it to codebase before that PR and everything is working fine. That PR seems to introduce many things and not easy for me to understand all changes it made but I will work with the PR author, in this case  @MV88 to identify the problem. Before that PR all actions we saw yesterday are called in the same order but with different effect compared to if I call them after that PR.

**Comment by kasongoyo** [comment]
We can merge this PR with the assumption that it will work when the regression bug introduced by PR https://github.com/geosolutions-it/MapStore2/pull/4278 is fixed. @MV88 can advise about this

**Comment by MV88** [comment]
Here's what i have found based on my investigation.

The fix for Issue  #4614  is just to remove [this](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/widgets/builder/wizard/map/enhancers/handleMapSelect.js#L28) line, but i'm not sure it causes regression in geostory, still need to verify it.

this pr does not work with that fix, the state is updated correctly (i tested the version without last commit "replace editWidget with onEditorChange") but then because of [this](https://github.com/geosolutions-it/MapStore2/blame/master/web/client/components/map/openlayers/Map.jsx#L272) if condition, the map position in preview does not update. 

I repeat i'm not sure this PR will work after fixing #4614

**Comment by offtherailz** [comment]
accordingly with @MV88 I blocked this PR because applying the fix suggested by matteo the issue zoom will not work anymore. Therefore we should wait for a definitive fix of  #4614 , that has more priority, before to merge this new functionality

**Comment by MV88** [comment]
This seems working after my fix on #4614

**Comment by tdipisa** [comment]
@MV88, please provide a backport PR to 2019.03.xx

**Pull request merged**
