### PR TITLE
#9974: Add permission validation to manage catalog service

### PR DESCRIPTION
**Pull request by dsuren1**
## Description
This PR adds configurable options to MetadataExplorer plugin (applicable for Map, Geostory, Context) and DashboardEditor's catalog component to configure permissible roles and groups via `editingAllowedRoles` and `editingAllowedGroups`

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] New Feature

## Issue

**What is the current behavior?**
- #9974 

**What is the new behavior?**
Based on the configured roles and groups permissible, the catalog services buttons are hidden/shown. By default editingAllowedRoles is "ADMIN"

```json
{
  "name": "MetadataExplorer",
  "cfg": {
    ...
    "editingAllowedRoles": [
      "some-role"
    ]"editingAllowedGroups": [
      "some-group"
    ]
  }
}
```

```json
{
  "name": "DashboardEditor",
  "cfg": {
    ...
    "servicesPermission": {
      "editingAllowedRoles": [
        "some-role"
      ]"editingAllowedGroups": [
        "some-group"
      ]
    }
  }
}
```

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by MV88 — CHANGES_REQUESTED** [review]
@dsuren1 please check the only a consideration i've made. the rest looks fine

**Review by MV88 — APPROVED** [review]
LGTM

**Comment by MV88** [comment]
@ElenaGallo Please test it in DEv

**Comment by ElenaGallo** [comment]
Test passed, @dsuren1 please backport to 2024.01.xx. Thanks

**Pull request merged**
