### PR TITLE
fix pom versions for release 2022.01.02

### PR DESCRIPTION
**Pull request by MV88**
## Description

fix pom versions for release 2022.01.02

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

snapshot were present

**What is the new behavior?**

fixed versions

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
looking at the historty 1.3.0 and 1.3.1 has already been used. We should use 1.3.2 instead?
Please confirm

**Comment by offtherailz** [comment]
ok, It can work. Anyway for the future I suggest to release anyway new versions, to avoid to check case by case. 
Anyway everything will be simpler when we will align the verison numbers.

**Review by offtherailz — APPROVED** [review]
ok, it may work. Anyway let's simplify for the future. 
Backend modules should be updated with MapStore version. Anyway with new project system and new version system anything will become simpler.

**Comment by tdipisa** [comment]
@offtherailz
A new release must be released only if there are updates otherwise we add unusefull tasks to the pipeline. The relase calendar can help for this it is updated according to the plans.

**Pull request merged**
