### PR TITLE
Annotation new design

### PR DESCRIPTION
**Pull request by dsuren1**
## Description
Simplify annotation and complete overhaul of the annotation panel

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
- [x] Feature

## Issue

**What is the current behavior?**
#5775 

**What is the new behavior?**
https://demo.geo-solutions.it/mockups/mapstore2/austrocontrol2020/#/

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information
Related issues:
https://github.com/geosolutions-it/austrocontrol-C125/issues/153
https://github.com/geosolutions-it/austrocontrol-C125/issues/187
https://github.com/geosolutions-it/austrocontrol-C125/issues/188
https://github.com/geosolutions-it/austrocontrol-C125/issues/189
https://github.com/geosolutions-it/austrocontrol-C125/issues/190
https://github.com/geosolutions-it/austrocontrol-C125/issues/191
https://github.com/geosolutions-it/austrocontrol-C125/issues/171
https://github.com/geosolutions-it/MapStore2/issues/4553

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
Good job :+1: I like it and it works quite good. Here some bugs I found and some notes about things that was missing/unclear in mock-up.

**bugs/changes**
- [ ] The enable editing button is not present in the mock-up, can we remove it?
image
- [ ] This text should be more clear (instead of "the geometry can not be empty", set "you must add at least one valid geometry to save the annotation" or "add at least one valid geometry"):
image
- [ ] The pencil button above appears only when you edit a new feature, but it doesn't seem to have any function.
- [ ] I can add more than one incomplete geometries without saving and I have some strange behaviours, and at the end a big error
Peek 03-09-2020 17-40
- [ ] An empty view with some text (like "no annotations yet, click on + to add annotations") can help to start, instead of the white panel.
- [ ] I can remove annotations except the last. This can make sense because the annotation layer becomes empty, but is not intuitive. So 2 options:
   - Allow to remove the last annotation (I prefer this option, remove the annotation layer in cascade automatically can be an option)
   - Show the "trash" button disabled, with a tooltip: "You can not remove the last annotation" to remove all the annotations, delete the Annotations layer.
- [ ] Color of lines during styling is not visible because it is in edit mode (blue all the time). Could we change this to allow to see live changes.
- [x] See comments inline

Any comments @allyoucanmap or @tdipisa ?

**Comment by dsuren1** [comment]
> The enable editing button is not present in the mock-up, can we remove it?

2020-09-07 12_42_58-Modify edit geometry of annotation · Issue #190 · geosolutions-it_austrocontrol-

Ref: https://github.com/geosolutions-it/austrocontrol-C125/issues/190

Since it wasn't available in the mockup, I added it myself. 
@offtherailz  Should I remove the edit button and its feature, as it was skipped in the mockup? Kindly advice.

**Comment by offtherailz** [comment]
Yes please @dsuren1, skip it if possible.

**Comment by allyoucanmap** [comment]
> I can add more than one incomplete geometries without saving...
@offtherailz

I think this behaviour is correct. In the .gif it seems some geometries are validated even if you did not draw it on the map (eg. polygon one)

**Comment by dsuren1** [comment]
> > I can add more than one incomplete geometries without saving...
> 
> @offtherailz @tdipisa
> 
> I think this behaviour is correct. In the .gif it seems some geometries are validated even if you did not draw it on the map (eg. polygon one)

In the fix, i'm working, I have fixed this by preventing user from adding a new geometry until the current one is valid. 
Please advice @offtherailz @tdipisa  @allyoucanmap

**Comment by tdipisa** [comment]
> > > I can add more than one incomplete geometries without saving...
> > 
> > 
> > @offtherailz @tdipisa
> > I think this behaviour is correct. In the .gif it seems some geometries are validated even if you did not draw it on the map (eg. polygon one)
> 
> In the fix, i'm working, I have fixed this by preventing user from adding a new geometry until the current one is valid.
> Please advice @offtherailz @tdipisa @allyoucanmap

I think it makes sense.

**Review by offtherailz — APPROVED** [review]
looks great to me :+1: 
@allyoucanmap do you want to try it to check it is consistent with your idea?

**Pull request merged**
