### PR TITLE
Fix #9999 Measures distance and area now supports all operations as geodesics features

### LINKED ISSUE #9999: Geodesic Measurement export
## Acceptance criteria

- [ ] transform area and distance measures drawn in 2d to geodesic 
- [ ] enable export / import as geodesic **areas** measures (export as geojson)
- [ ] enable export / import as geodesic **distances** measures (export as geojson)
- [ ] extend previous 2 points also for annotations 
  - [ ] when a measure is transformed in annotations it should render as geodesic lines without touching geom (only via style)
  - [ ] when exported (from toc toolbar or from annotations one) it should be transformed to geodesic lines (i.e. segmenting it, including originalGeom in properties)
  - [ ] when importing such annotation it should convert it back so that in the coord editor you see only original drawn points

### PR DESCRIPTION
**Pull request by MV88**
## Description

lines and areas are now geodesic
- in export as geojson
- in created as annotations and export and import there

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

Fix #9999

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by MV88** [comment]
> Inline comments are addressing mainly some issues with the style parsers. The workflow for import/export of geodesic annotation is working well. Also the export of geodesic measurement is working as expected probably the only part missing is to improve the import of geojson to intercept if the feature collections has some features with originalGeom and restore it ([geoJSONToLayer](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/LayersUtils.js#L586) used by [processFiles](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/import/dragZone/enhancers/processFiles.jsx#L151)). Maybe we could add some custom properties to feature collection eg "msType": "measure" as we are doing for annotation to focus the parsing only on this type of imported layers

@tdipisa @allyoucanmap 
i think this should be a dedicated issue, also because it requires to apply some different styling when the measures is created as vector layer and also when exported as geojson and then needs to be handled also in import

**Review by allyoucanmap — APPROVED** [review]
LGTM

**Comment by allyoucanmap** [comment]
@ElenaGallo please test on dev and let us know if we can backport to 2024.01.xx, thanks

**Comment by ElenaGallo** [comment]
@MV88 I don't know if the problem is due to this PR but when a measurement is transformed into an annotation and the coordinates change then the style of the text is no longer correct. 


https://github.com/geosolutions-it/MapStore2/assets/56537133/ad4ae44c-a2ca-497e-bb8b-88a3ce246fe7

**Comment by MV88** [comment]
@tdipisa @ElenaGallo 
This issue was present also before my PR, I guess we need to open a dedicated issue

**Comment by tdipisa** [comment]
Wait @ElenaGallo 

> This issue was present also before my PR, I guess we need to open a dedicated issue

@MV88 I tried and it doesn't seems to me at the moment. Let's check it together before opening a new issue.

**Comment by tdipisa** [comment]
Ok, that's more clear now what is the problem: the length measurement text of the _last_ segment is changing after changing one vertex. The image below better clarify before and after @ElenaGallo 

image

@ElenaGallo that's a preexisting issue, please open a new issue for that for 2024.01.00 and assign it to @MV88. Then, let us know if we can proceed with the backport of this to 2024.01.xx.

**Comment by ElenaGallo** [comment]
@tdipisa New issue https://github.com/geosolutions-it/MapStore2/issues/10051, @MV88 please backport this PR to 2024.01.xx. Thanks

**Pull request merged**
