### PR TITLE
#5883 adjust wrong value of radius when geodesic is set to true for annotations circle

### PR DESCRIPTION
**Pull request by MV88**
## Description

fixed the value of radius when geodesic is set to true plus adding a test to cover it

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#5883

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
I think we are doing something wrong:
DEV: 
Peek 15-01-2021 09-56

PR: 
Peek 15-01-2021 09-58


This happens also at small scale:
Peek 15-01-2021 10-12

@MV88 I think you modified the wrong place.

Can you also please @tdipisa write a set of defined step to verify the functionality? 
It should be also useful having a set of tests (from cucumber, they should be there) to allow devs to verify their work is still consistent with the other requirements.

**Comment by offtherailz** [comment]
Sorry, duplicated gif in first edit of the review. Now I re-uploaded correct gif.

**Comment by MV88** [comment]
the real problem is how we handle the geodesic in circle annotations since we have no option to draw a geodesic circle and interacting with it by resizing the perimeter or moving the center, i-e using a modify interaction for it.
before this pr we were always drawing circle e non geodesic circle, even if it was configured otherwise.

@offtherailz @mbarto @tdipisa @allyoucanmap 
my opinion is that 
- have a look and find a way to draw a real geodesic circle (not as a polygon),
- if that is not possible remove the possibility to draw geodesic circle in annotation
- if that is not possible i accept suggestions

**Comment by tdipisa** [comment]
Closed in favor of #6503

**Pull request closed without merging**
