### PR TITLE
[Backport 2021.02.xx] #7602 Google Street view plugin (#7603)

### PR DESCRIPTION
**Pull request by offtherailz**
[Backport 2021.02.xx] #7602 Google Street view plugin (#7603)

### CODE REVIEW

**Comment by tdipisa** [comment]
@ElenaGallo did you already test this in DEV? Can we proceed with the review/merge of the backport?

**Comment by ElenaGallo** [comment]
@tdipisa I haven't tested it in dev yet.

**Comment by tdipisa** [comment]
@ElenaGallo let us know about the test in DEV asap so that we can proceed with the backport.

**Comment by ElenaGallo** [comment]
@tdipisa test passed on DEV, you can proceed with the backport.

**Review by tdipisa — APPROVED** [review]

**Pull request merged**
