### PR TITLE
#6537: Measurement panel improvement (III)

### PR DESCRIPTION
**Pull request by dsuren1**
## Description
This PR adds more improvements to the measurement panel

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [x] Enhancement

## Issue

**What is the current behavior?**
https://github.com/geosolutions-it/MapStore2/pull/6545#issuecomment-781278947

**What is the new behavior?**
Measurement panel with coordinates editor
- Upon clicking the **+** button, the coordinate row is added and either by clicking on the map or entering the valid coordinate and submitting, the coordinate editor will automatically add coordinates row until the geometry is valid (LineString & Bearing - 2 row, Polygon - 3 rows)
- Upon adding the vertices, the vertex points of the coordinate is highlighted with a point (To guide the user in visualizing the position while the geometry is drawn) 
- The Linestring arc will be maintained while updating the features (if any).
- When saving the measurement to annotation, the 'Bearing' will not be transformed to arc line (if any).
- User should be able to use left/right arrow keys to move cursor position in the coordinates editor input fields

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information
https://github.com/geosolutions-it/austrocontrol-C125/issues/268
https://github.com/geosolutions-it/austrocontrol-C125/issues/269

### CODE REVIEW

**Review by MV88 — CHANGES_REQUESTED** [review]
i have found something

when you draw a line and then a bearing the lines are no longer selectable
this does not works when you change type in general
image


there is an extra label with 0° on map when doing this

https://user-images.githubusercontent.com/11991428/108542007-728e4080-72e3-11eb-89d7-7f57abae64c7.mp4

**Comment by dsuren1** [comment]
Thanks for the feedback @MV88 
> when you draw a line and then a bearing the lines are no longer selectable
> this does not works when you change type in general

_Unfortunately I couldn't reproduce this issue. kindly let me know if it involves any specific steps._

> there is an extra label with 0° on map when doing this

_I have provided a fix_

**Review by MV88 — APPROVED** [review]
good job LGTM

**Comment by ElenaGallo** [comment]
@tdipisa test done, @dsuren1 please backport this to the stable branch

**Comment by tdipisa** [comment]
Since @dsuren1 is not available today, @MV88 can you please backport in 2021.01.xx all the involved PRs?
https://github.com/geosolutions-it/MapStore2/pull/6538
https://github.com/geosolutions-it/MapStore2/pull/6545
https://github.com/geosolutions-it/MapStore2/pull/6555 (this one)

**Pull request merged**
