### PR TITLE
#9319 - Fix: Exception when printing a annotation (Polygon) with modified vertices

### PR DESCRIPTION
**Pull request by dsuren1**
## Description
This PR fixes the exception caused by modified polygon that is malformed

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**
- #9319 

**What is the new behavior?**
The polygon annotation is not malformed and is printable when the vertices are modified

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
- [ ] I tried to import the atttached Annotations.json file (from the original issue)  and I noticed this issue: 

[annotations.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/1371485c-4a26-4e6a-adaa-5054d9b6f805)

[Annotations.zip](https://github.com/geosolutions-it/MapStore2/files/12649358/Annotations.zip)

Basically the zoom of the print is reset to zero. 

Did I missed something in replicating the issue?

**Comment by dsuren1** [comment]
@offtherailz 
Merging with the latest commits of 2023.02.xx fixes the issue. Probably fixes related to scales and zoom did the trick. Kindly give it a try now and let me know how it goes. Thanks!

**Review by offtherailz — APPROVED** [review]
I didn't get this point. I created the annotation and it worked. I tried to import the annotation attached (old) and it had that bug, so I supposed it was caused by importing.
The bug during editing is effectively fixed.

**Comment by ElenaGallo** [comment]
Test passed, @dsuren1 please backport this to stable branch. Thanks

**Comment by dsuren1** [comment]
> Test passed, @dsuren1 please backport this to stable branch. Thanks

@ElenaGallo The fix is directly pushed to stable. Kindly test it in QA, if not already. Thanks!

**Pull request merged**
