### PR TITLE
#7126 - share tool visibility is configurable at Home page elements grid

### PR DESCRIPTION
**Pull request by alexander-fedorenko**
Updated localConfig to store defaults for new configuration options;
Passed new property to the grid components: featured, maps, dashboards, geostories.

## Description
Share tool visibility is configurable at Home page elements grid.
Updated localConfig to store defaults for new configuration options;
Passed new property to the grid components: featured, maps, dashboards, geostories.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
It's not possible to configure share tool visibility via localConfig.json
#7126

**What is the new behavior?**
Configuration value is properly passed to the grid components on the home page.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by MV88 — APPROVED** [review]

**Comment by MV88** [comment]
@ElenaGallo test this locally since you have to change the localConfig.json for:
- Maps 
- Geostories
- FeaturedMaps
- Dashboards

with the flag  shareToolEnabled  set to false to see if you can hide the button

**Comment by ElenaGallo** [comment]
@alexander-fedorenko @tdipisa If the content is in the Featured section, the share tool is present on the card.

**How to reproduce**
Follow the steps in the gif below:
share-tool

**Comment by MV88** [comment]
@tdipisa @ElenaGallo 
that does not work per content, but per plugin 

so if you remove share in geostoreis for example, but you do not that for featured cards then is normale to have the share also in the featured cards

i'm not sure the issue was specified this plugin interconnection as a requirement

**Comment by alexander-fedorenko** [comment]
@MV88 @tdipisa @ElenaGallo 
Should we move it forward or more use-cases need to be covered? Ability to define share tool visibility rules based on the entity type could be a separate feature if it's needed.

**Comment by tdipisa** [comment]
As we have discussed in the call it is only a matter of configuration between featured/non featured plugin list in home. therefore I think a new issue can be created with a _question_ label so that we can discuss later which configuration we want apply.

**Pull request merged**
