### PR TITLE
#8529 maxItems is now used from Identify plugin

### PR DESCRIPTION
**Pull request by MV88**
## Description

Now you can specify maxItems in identify cfg

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#8529 

**What is the new behavior?**

now you can specify it in localConfig under identify cfg

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by ale-cristofori — APPROVED** [review]
OK for me

**Comment by ale-cristofori** [comment]
@ElenaGallo please test locally

**Comment by ElenaGallo** [comment]
@ale-cristofori @MV88 I have noticed that it is possible to add a maximum of 26 Items. See the image below:
26 okkk

**Comment by ale-cristofori** [comment]
@ElenaGallo, test it with a smaller number on the same dataset (like 3) and if it passes then the tests are completed

**Comment by ElenaGallo** [comment]
@ale-cristofori  ok, in this case the test passes

**Comment by ale-cristofori** [comment]
@MV88, could you backport this to 2022.01.xx?
Thanks

**Comment by MV88** [comment]
@ale-cristofori 
are you sure we have to use that branch? latest stable branch is 2022.02.xx 
which it will be used to release next major release in Mapstore 2022.02.00

**Comment by ale-cristofori** [comment]
@MV88, yes it surely needs to be backported to 2022.02.xx. Since Vlaanderen use 2022.01.03 in dev maybe a further backport is needed, so please backport to 2022.02.xx first and then I'd wait for @tdipisa to ask if more backports are needed.
Thanks

**Comment by MV88** [comment]
Here is the backport for 2022.02.xx 
https://github.com/geosolutions-it/MapStore2/pull/8589

**Pull request merged**
