### PR TITLE
#6077: Multiple Selection/wmsSync bug fix

### LINKED ISSUE #6187: Attribute Table - Issue generating charts
## Description

As soon as you select the aggregation method the chart disappear from the preview and it is not present in the final chart widget.

## How to reproduce

-  Open [this map](https://qa.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/10358)
- Follow the steps reported in the GIF below

fg_edit_6

*Expected Result*

The chart should be available in preview and in the final widget according to the configured parameter **including the applied filters**

*Current Result*

The chart is no longer available as soon as you select the aggregation method

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### PR DESCRIPTION
**Pull request by AGMETEOR**
## Description

This PR fixes [issue here](https://github.com/geosolutions-it/MapStore2/issues/6077#issuecomment-722530005) with the syncMapWmsFilter.
This also potentially fixes #6187 (I have tested it with these changes)

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#6077 

**What is the new behavior?**

All features are shown when syncMapWmsFilter is activated

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by MV88 — CHANGES_REQUESTED** [review]
what if you define a spatial filter from the advanced search and you trigger the search, will that be ignored?

**Comment by AGMETEOR** [comment]
> what if you define a spatial filter from the advanced search and you trigger the search, will that be ignored?

 i am not sure how that can be done

**Comment by MV88** [comment]
> > what if you define a spatial filter from the advanced search and you trigger the search, will that be ignored?
> 
> @MV88 i am not sure how that can be done. spatial filter was a bit of a problem when it came to deselection of features that were selected using box selection tool. i think it's better if the filter used to sync is always generated based on the selected features.

the spatial filter defined in the Advanced Search should win over the one defined in the selected features, in fact they are lost when a search is done

@tdipisa correct me if i'm wrong

**Comment by tdipisa** [comment]
> > > what if you define a spatial filter from the advanced search and you trigger the search, will that be ignored?
> > 
> > 
> > @MV88 i am not sure how that can be done. spatial filter was a bit of a problem when it came to deselection of features that were selected using box selection tool. i think it's better if the filter used to sync is always generated based on the selected features.
> 
> the spatial filter defined in the Advanced Search should win over the one defined in the selected features, in fact they are lost when a search is done
> 
> @tdipisa correct me if i'm wrong

correct @MV88

**Comment by AGMETEOR** [comment]
> > > what if you define a spatial filter from the advanced search and you trigger the search, will that be ignored?
> > 
> > 
> > @MV88 i am not sure how that can be done. spatial filter was a bit of a problem when it came to deselection of features that were selected using box selection tool. i think it's better if the filter used to sync is always generated based on the selected features.
> 
> the spatial filter defined in the Advanced Search should win over the one defined in the selected features, in fact they are lost when a search is done
> 
> @tdipisa correct me if i'm wrong

Ok I get it now. Update coming up.

**Review by MV88 — APPROVED** [review]
looks good to me

**Pull request merged**
