### PR TITLE
#8872 WMTS - No persistency for TileMatrixSetLimits il TileMatrixSet is within a layer

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description

This PR introduces a refactor of the `wmts` tile matrix set configuration replacing the `matrixIds` and `tileMatrixSets` properties with a single property called `availableTileMatrixSets`. The main reason of this change is related to the need to store custom tile set limits in the layer object configuration.
Here an example of map configuration:

```js
{
    "version": 2,
    "map": {
        "projection": "EPSG:900913",
        // other options
        "layers": [
            {
                "id": "layer:001",
                "name": "workspace:layer",
                "title": "Layer",
                "type": "wmts",
                "url": "http://some.domain/geoserver/gwc/service/wmts",
                "bbox": {
                    "crs": "EPSG:4326",
                    "bounds": {
                        "minx": "-180.0",
                        "miny": "-79.99999999999945",
                        "maxx": "180.0",
                        "maxy": "83.99999999999999"
                    }
                },
                "allowedSRS": {
                    "EPSG:3857": true,
                    "EPSG:900913": true
                },
                "availableTileMatrixSets": {
                    "EPSG:900913": {
                        "crs": "EPSG:900913",
                        "limits": [
                            {
                                "identifier": "EPSG:900913:0",
                                "ranges": {
                                    "cols": {
                                        "min": "0",
                                        "max": "0"
                                    },
                                    "rows": {
                                        "min": "0",
                                        "max": "0"
                                    }
                                }
                            },
                            {
                                "identifier": "EPSG:900913:1",
                                "ranges": {
                                    "cols": {
                                        "min": "0",
                                        "max": "1"
                                    },
                                    "rows": {
                                        "min": "0",
                                        "max": "1"
                                    }
                                }
                            },
                            {
                                "identifier": "EPSG:900913:2",
                                "ranges": {
                                    "cols": {
                                        "min": "0",
                                        "max": "3"
                                    },
                                    "rows": {
                                        "min": "0",
                                        "max": "3"
                                    }
                                }
                            }
                        ],
                        "tileMatrixSetLink": "sources['http://some.domain/geoserver/gwc/service/wmts'].tileMatrixSet['EPSG:900913']"
                    }
                }
            }
        ],
        "sources": {
            "http://some.domain/geoserver/gwc/service/wmts": {
                "tileMatrixSet": {
                    "EPSG:900913": {
                        "ows:Identifier": "EPSG:900913",
                        "ows:SupportedCRS": "urn:ogc:def:crs:EPSG::900913",
                        "TileMatrix": [
                            {
                                "ows:Identifier": "EPSG:900913:0",
                                "ScaleDenominator": "5.590822639508929E8",
                                "TopLeftCorner": "-2.003750834E7 2.0037508E7",
                                "TileWidth": "256",
                                "TileHeight": "256",
                                "MatrixWidth": "1",
                                "MatrixHeight": "1"
                            },
                            {
                                "ows:Identifier": "EPSG:900913:1",
                                "ScaleDenominator": "2.7954113197544646E8",
                                "TopLeftCorner": "-2.003750834E7 2.0037508E7",
                                "TileWidth": "256",
                                "TileHeight": "256",
                                "MatrixWidth": "2",
                                "MatrixHeight": "2"
                            },
                            {
                                "ows:Identifier": "EPSG:900913:2",
                                "ScaleDenominator": "1.3977056598772323E8",
                                "TopLeftCorner": "-2.003750834E7 2.0037508E7",
                                "TileWidth": "256",
                                "TileHeight": "256",
                                "MatrixWidth": "4",
                                "MatrixHeight": "4"
                            }
                        ]
                    }
                }
            }
        }
    }
}
```

This PR is also fixing an issue with the get feature info request with WMTS

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**

#8872

**What is the new behavior?**

Introduced the `availableTileMatrixSets` property configuration for WMTS layers

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [x] No

## Other useful information

Here some suggesting on testing. Before starts we need to crate maps that include multiple wmts layers:
- create a map with multiple wmts layer from multiple catalog
- create a map with multiple wmts layer from same catalog
- ...

We need to test this maps with following plugins/workflows:
- save/save as
- import/export
- printing of wmts layer
- visualization in openlayers, cesium and leaflet
- identify/get feature info

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
I tested with old maps and GeoStories and looks work well. The only note is on documentation. @allyoucanmap please correct me If I'm wrong with my suggestions, or merge them.

**Comment by tdipisa** [comment]
@offtherailz @allyoucanmap this is not a change that can be backported to an official stable branch. This must lends in 2023.01.00. This is PR introduce a change of the map config model therefore, as we have already discussed @offtherailz, it should be clearly reported in online documentation in a dedicated section I think, where all of these kind of changes are reported between different versions.

**Comment by offtherailz** [comment]
@tdipisa  this change in configuration keeps backward compatibility and it doesn't introduce any breaking change or needing for migration. Right @allyoucanmap ?

**Comment by offtherailz** [comment]
@ElenaGallo, could you please test this on  DEV  ? Thank you

**Comment by ElenaGallo** [comment]
Hi @allyoucanmap, testing this I notice this error performing the GFI:

- If GFI is run in an area where there is only the osm:simple_dark layer in [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/42508), the GFI opens with no information and this error is displayed in the console:

> GET https://dev-mapstore.geosolutionsgroup.com/mapstore/proxy/?url=https%3A%2F%2Fgeoserver-osm.gis.cloud.mow.vlaanderen.be%2Fgeoserver%2Fgwc%2Fservice%2Fwmts%3Fservice%3DWMTS%26request%3DGetFeatureInfo%26layer%3Dosm%253Aroads%26infoformat%3Dtext%252Fplain%26style%3Dosm%253Aroads%26tilecol%3D32%26tilerow%3D22%26tilematrix%3D6%26tilematrixset%3DWebMercator%26i%3D180%26j%3D209 400 (400)

https://user-images.githubusercontent.com/56537133/207647258-7e665fcb-ce87-41a6-84ad-ff84c1d849f5.mov

**Comment by ale-cristofori** [comment]
The error highlighted by @ElenaGallo has been captured to a separate issue that can be investigated later on. Please refer to https://github.com/geosolutions-it/support/issues/2418

**Pull request merged**
