### PR TITLE
#5539 Update Layer Title and Description

### PR DESCRIPTION
**Pull request by vlt1**
## Description
Changes as per [this comment](https://github.com/geosolutions-it/austrocontrol-C125/issues/168#issuecomment-698444579).

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
#5539 
[austrocontrol-C125/#168](https://github.com/geosolutions-it/austrocontrol-C125/issues/168)

**What is the current behavior?**
#5539 

**What is the new behavior?**
Description

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
- [ ] It works, but I think editing of the layer name should be a little more explicit
because the refresh button says nothing, and if you click on save on top, the name is not updated, it can be hard to understand for a user.

I think we should instead: 
- Start with disabled name editing, allow editing from a button (pencil icon)
image. tooltip for the pencil button is "Edit layer name"
- When click on the pencil the input enable and you can edit. The button on the right now is an "ok" icon ("v" like check icon). tooltip for ok icon is "Confirm layer name change"
- When click on confirm, we disable again the input and do the refresh, going back to initial state.

I think it should be better, in case of error, to leave the input enabled, but I think it is hard (the state) so I propose this solution.

- [ ] Unit tests

**Comment by tdipisa** [comment]
> I think we should instead:
> 
> * Start with disabled name editing, allow editing from a button (pencil icon). tooltip for the pencil button is "Edit layer name"
>   image
> * When click on the pencil the input enable and you can edit. The button on the right now is an "ok" icon ("v" like check icon). tooltip for ok icon is "Confirm layer name change"
>   image
> * When click on confirm, we disable again the input and do the refresh, going back to initial state.

I agree with @offtherailz about the icons to use, it is also specified in the requirements:

>The layer name should be editable manually in Layer Settings (**a button will enable editing of the name and allow save**);

There is also the following part in the same requirement @offtherailz:

>once the settings are saved, the layer will be updated (name and description) and re-rendered. If name is wrong, a notification will show the error

We had the intention to persist changes only when the settings are saved. Let's talk about it one minute.

**Comment by offtherailz** [comment]
it should already work this way

Beyond what you edit in the settings, if you close without saving it asks you for confirmation and eventually cancels the changes.

All changes are applied "live" to the map, but editing the layer name can be dangerous (for this reason is disabled by default) and while editing you should not update (for this reason we ask confirm).

**Comment by vlt1** [comment]
@offtherailz @tdipisa changes persist only when pressing on save button

**Comment by offtherailz** [comment]
@vlt1 I think there is too much logic in layers epic/actions/reducers for a functionality like this to maintain. Moreover, this is not a generic "layers" functionality, so It should be isolated. 
I think as much self contained as possible. For this reason I suggested to use internal state (useState), maybe a small dedicated component.

**Review by offtherailz — CHANGES_REQUESTED** [review]
@vlt1 I think there is too much logic in layers epic/actions/reducers for a functionality like this to maintain. Moreover, this is not a generic "layers" functionality, so It should be isolated. 
I think as much self contained as possible. For this reason I suggested to use internal state (useState), maybe a small dedicated component.

Sorry if I didn't specified this implementation detail in the review, I though it was implicit in the evolution of your previous component (that had some internal state) to do it this way.

**Comment by vlt1** [comment]
@offtherailz the external actions are needed for the epic to trigger them correctly on layer load event

**Comment by offtherailz** [comment]
@vlt1 the first implementation contained it [here](https://github.com/geosolutions-it/MapStore2/pull/5956/commits/613577cf422c1a568f79e590374747eacc46d224#diff-4b3be91e5c684f0262d1806a1a14f4c9R159).  I think it was enough

**Comment by vlt1** [comment]
@offtherailz current implementation offers better user experience

**Comment by offtherailz** [comment]
@vlt1 yes, I like very much the user interface you did. 

But having the self contained solution works also in other use case of the TOC (e.g. maps in dashboards or in stories). 
For this reason a good compromise can be having an acceptable user experience with the functionality reusable also in the other use cases. 
Otherwise the we have to find a solution for each TOC use case (and maintain them). I think is easier for us.

**Comment by vlt1** [comment]
@offtherailz I've just realized layer loading and error information is kept and updated within the layer object(in General component it is the element prop I believe), so I can use that information, which means I can delete all actions and move edit state to component state and that should allow me to be able to keep the current UX. So new actions, state, reducers introduced can be removed.

**Comment by offtherailz** [comment]
Great. Thanks, 
Please check also if your changes work in dashboards map widget TOC and geostory map editor inline or mediaeditor, so we are sure that the solution is reusable in a lot of use case. In case of error handling problem in other contexts, do not implement complex error handling, but try to keep it simple as much as possible.

**Comment by vlt1** [comment]
@offtherailz Does name editing need to work also in geostory and dashboard? If so that it will need its own implementation anyway, because that MapView is separate from the main view and it's epics. Currently implementation is for map viewer only.

**Comment by offtherailz** [comment]
@vlt1 the old editor you made here (613577cf422c1a568f79e590374747eacc46d224) was working in all the contexts, except for the notification of the error, and I think it was acceptable. For this reason I asked to continue on that way in a self contained component, and only to change the internal behavior, limiting as much as possible the external interactions.

Of course, the TOCSettings should continue to work and be consistent in every use context inside the application.

**Comment by vlt1** [comment]
@offtherailz In other contexts there is no mechanism for notifying the state of the layer (is it loading, has been loaded, with what error) it seems to me. That is a problem I think, because the user can save a layer with a wrong layer name that doesn't work, since to check whether layer load or not we need to update it to force it to load. I'm not sure though need to investigate it more, since I've never worked with that code before.

**Comment by offtherailz** [comment]
@vlt1 for the moment you can avoid to notify the error in other contexts then the main map viewer, because only the map can support error catching due to tile loading errors. In the future we may allow to catch the errors also from other maps then the main viewer, or doing a request directly in the component that do this check.

For the moment, take only care of protecting the editing of the layer name the way I asked, in a self contained component.

**Comment by vlt1** [comment]
@offtherailz The functionality is contained within General component, I've added a prop that enables more feedback for the user if it is possible within the context the General component is used.

**Review by offtherailz — CHANGES_REQUESTED** [review]
- You forgot the tooltips for the edit/confirm buttons ;) . Just this to merge this PR
- maybe all the logic of edit confirm etc... stays well in a separated component "LayerNameEditor", instead of mixing all in General.jsx, anyway, this is a plus and there is no to much time.

**Review by offtherailz — APPROVED** [review]

**Pull request merged**
