### PR TITLE
Fix #3548 add coordinate editor for GFI panel

### LINKED ISSUE #3548: GFI via coordinate input
### Description
Add the possibility to use a coordinate editor for the GFI tool.
With all coordinate valid using Enter from keyboard will perform the GFI search.

We will also add two flags:
* enabledCoordEditorButton set to true by default
* showCoordEditor set to false by default

### PR DESCRIPTION
**Pull request by MV88**
## Description
This pr add the coordinate editor in the header of GFI panel.
the flag used to show the button that trigger visibility of coord editor in the toolbar is true by default and is called "enabledCoordEditorButton"
by default the flag used to show the coordinate editor is false by default and is called "showCoordinateEditor"

image

## Issues
 - Fix #3548 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
you cannot perform a GetFeatureInfo for exact coordinates

**What is the new behavior?**
you can use a coordinate editor to search custom point

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

If you want to avoid to hidethe button in the toolbar (true by default)
```
{
"name": "Identify",
  "cfg": {
    "enabledCoordEditorButton": false
}
```
or if you do not specify the previous config and you want to show the coordinate editor (by default is false), in the initialState add
```
"mapInfo": {
  "enabled": true,
  "showCoordinateEditor": true
}
```

### CODE REVIEW

**Comment by mbarto** [comment]
@tdipisa @MV88 so to enter a coordinate for GFI I have to first do a GFI clicking on the map?
I would have expected a tool external to the GFI panel.

**Comment by tdipisa** [comment]
> @tdipisa @MV88 so to enter a coordinate for GFI I have to first do a GFI clicking on the map?
> I would have expected a tool external to the GFI panel.

@mbarto yes, is what we agreed in the [mockup](https://demo.geo-solutions.it/mockups/mapstore2/annotation_styles/#/viewer/openlayers/new)

**Comment by MV88** [comment]
> You always use comma as a decimal separator in coordinates editor. You should use the right separator for the current locale (comma is used mainly in Italy)

@mbarto  I see the dots

image

**Comment by mbarto** [comment]
@MV88 if it depends on PC locale, then it's good, my only concern was if commas where used always

**Pull request merged**
