### PR TITLE
some modifications in translation

### PR DESCRIPTION
**Pull request by arp43b**
Some modifications en file tranlated

### CODE REVIEW

**Comment by MV88** [comment]
Hi, Antionio. Why do you have submitted this PR? The last one it should be already merged. 
see https://github.com/geosolutions-it/MapStore2/pull/2001

**Comment by arp43b** [comment]
I have 2 mistakes in traducction that i want fix

**Comment by arp43b** [comment]
I'm sorry, my mistake
I am not very accosted to upload code

**Comment by MV88** [comment]
No problem Antonio. I suggest you to follow these steps:
1. Go to master branch (git checkout master)
1. git pull 
1. git checkout -b fix_translations
1. made the changes you want.
1. git add the changed files
1. git commit -m "fixed some spanish translations"
1. git push YOUR_REPO fix_translations

or you can use the rebase command (https://git-scm.com/book/en/v2/Git-Branching-Rebasing)

Generally, it is preferred to create a pr from a branch inside your repo instead from the master branch.

**Comment by arp43b** [comment]
ok, i created a new branch in my repository, i'll provide a new PR

**Pull request closed without merging**
