### PR TITLE
#9320 - Support reading/loading of cloud-optimized geotiff (COG)

### PR DESCRIPTION
**Pull request by dsuren1**
## Description
This PR adds possibility to add new cloud-optimized geotiff source as layer to Mapstore

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Feature

## Issue

**What is the current behavior?**
- #9320 

**What is the new behavior?**
- COG layer support
- New COG layer can added as layer from Catalog and as background
- COG layer reprojection
- COG layers are skipped in print tool
- Visibility limits

**Future enhancement** (Currently not supported)
- GFI
- Compare tool (Needs to be updated to also support WebGL tile layer)
- Print
- StyleEditor
- Import/Export

## Testing
**Sample COG Urls:**  (You can also the sample urls listed in the issue. _Note:_ some urls are heavy and consumes significant bandwidth)
https://cogeo.craig.fr/opendata/ortho/2018_25cm_ain+isere.tif
[EPSG:2154] - https://cogeo.craig.fr/opendata/ortho/orthocraig3_vichy_2021.cog.tif
[EPSG:3946] - https://cogeo.craig.fr/opendata/ortho/ortho25_cc46_clerco_1996.cog.tif

Background configuration in `new.json`
```javascript
{
  "type": "cog",
  "title": "Cloud optimized geotiff",
  "name": "COG exmaple",
  "visibility": false,
  "url": [
    "https://cogeo.craig.fr/opendata/ortho/ortho25_cc46_clerco_1996.cog.tif"
  ],
  "group": "background"
}
```
**Catalog**
image

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by tdipisa** [comment]
@dsuren1 can you please fix conflicts?

**Comment by dsuren1** [comment]
> @dsuren1 can you please fix conflicts?

Resolved 👍

**Review by offtherailz — CHANGES_REQUESTED** [review]
Reporting things that should be improved, IMHO, to have a MVP Please @tdipisa take a look to decide what should be included and what should not. 

Here I'm attachning the map configuration used for tests:
[cog_test.zip](https://github.com/geosolutions-it/MapStore2/files/12673382/cog_test.zip)

- [x] I suggested inline some changes to make the configuration more open to future evolutions (using only "url" makes you continue to support the 1-url configuration forever, even when we may have many sources with many options.
- [ ] There should be a loading spinner on layer, because the load takes too much and the first impression of the user is that nothing happened.

[cog_loading.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/f3bee5b5-d747-4bf6-9cd2-305f3e97444e)

- [ ] No zoom to layer. Is there a way to fetch the bbox from the layer?
- [x] In 3D the layer should be disabled in TOC, as the 3D tiles layers are disabled in 2D to show they are not available.

One note about the documentation: 
Now we have only [this](
https://docs.mapstore.geosolutionsgroup.com/en/latest/developer-guide/local-config/#catalog-tool-configuration) for documenting catalog configurations. This is not enough anymore.

We have different catalogs with different rules (WMS, WFS, TMS, WMTS, COG...  with various options).
@tdipisa we should open a different issue for this.

**Comment by dsuren1** [comment]
@offtherailz 
Thanks. I have amended rest of the comments.

> * [ ]  There should be a loading spinner on layer, because the load takes too much and the first impression of the user is that nothing happened.

The GeoTIFF sources fires `tileloadend` and `tileloadstart` events which are already captured by our event listeners functions. tileloadstart is not fired when fetching of the data in progress. So I would like to add something to `Layers` or add a customLoader function 

```js
if (options.type === "cog" && this.layer.getSource().getState() === "loading") {
     this.props.onLayerLoading(options.id);
}
```

> * [ ]  No zoom to layer. Is there a way to fetch the bbox from the layer?

In order to get extent, we need `gdal` library, there are npm libraries that provides a wrapper for running GDAL in the browser however this needs to be run in worker as the process is heavy. We may also need to import gdal.js, gdal.wasm, gdal.data which are of significant size, doing it on client side we could often run into CORS too when accessing tif sources or we could implement gdal functions on the backend service

**Comment by tdipisa** [comment]
Thank you so much @dsuren1 

@offtherailz let us know for the following
>The GeoTIFF sources fires tileloadend and tileloadstart events which are already captured by our event listeners functions. tileloadstart is not fired when fetching of the data in progress. So I would like to add something to Layers or add a customLoader function

For this one instead I would like to open a dedicated issue for a future evolution @dsuren1. Can you or @offtherailz open it please?
>In order to get extent, we need gdal library, there are npm libraries that provides a wrapper for running GDAL in the browser however this needs to be run in worker as the process is heavy. We may also need to import gdal.js, gdal.wasm, gdal.data which are of significant size, doing it on client side we could often run into CORS too when accessing tif sources or we could implement gdal functions on the backend service

I would like then to capture also this one from the @offtherailz comment above. Can you please open a dedicate issue @dsuren1?
>Now we have only [this](https://docs.mapstore.geosolutionsgroup.com/en/latest/developer-guide/local-config/#catalog-tool-configuration) for documenting catalog configurations. This is not enough anymore.
We have different catalogs with different rules (WMS, WFS, TMS, WMTS, COG... with various options).

Thank you so much guys.

**Comment by offtherailz** [comment]
@tdipisa opened #9469 for your request about spinner issue.
 Please check if the milestone is correct, (the issue  is assigned to you right now)

**Comment by tdipisa** [comment]
> > @tdipisa opened #9469 for your request about spinner issue. Please check if the milestone is correct (the issue is assigned to you right now).
> 
> @offtherailz If I'm not wrong, I believe the ticket is required for `extent` and `documenting catalog` configurations.

indeed @offtherailz

**Review by offtherailz — APPROVED** [review]

**Comment by dsuren1** [comment]
> I would like then to capture also this one from the @offtherailz comment above. Can you please open a dedicate issue @dsuren1?
> 
> > Now we have only [this](https://docs.mapstore.geosolutionsgroup.com/en/latest/developer-guide/local-config/#catalog-tool-configuration) for documenting catalog configurations. This is not enough anymore.
> > We have different catalogs with different rules (WMS, WFS, TMS, WMTS, COG... with various options).

@tdipisa documentation issue as requested
- https://github.com/geosolutions-it/MapStore2/issues/9470

**Comment by tdipisa** [comment]
@offtherailz waiting for your second review. Thank you.

**Comment by offtherailz** [comment]
I effectively see that no event is triggered by openlayers for these load events.
So there is not an easy solution.
Even if we can trigger the load start on add, we can not catch load end... so I think it could be better to open a dedicated issue for that.
@tdipisa let me know what do you think. The rest is ready to be merged.

**Comment by tdipisa** [comment]
So, does this mean that you would like to avoid the proposal above from @dsuren1? If yes, please open that dedicate issue for a future evolution and merge this PR. Thank you.

**Comment by dsuren1** [comment]
I agree with @offtherailz to open a dedicated issue for this scenario, as even the generic `error` event is not fired when layer fetch is failed. It needs some investigation

**Comment by tdipisa** [comment]
@dsuren1 can you please that issue? Thank you so much.

**Comment by dsuren1** [comment]
Spinner issue created
https://github.com/geosolutions-it/MapStore2/issues/9480

**Comment by tdipisa** [comment]
@ElenaGallo please test in DEV once merged and let us know if we can backport.

**Comment by ElenaGallo** [comment]
Test passed, @dsuren1 please backport this to stable branch. Thanks

**Pull request merged**
