### PR TITLE
#4876. Introduced noRoot option to skip root rendering playback

### PR DESCRIPTION
**Pull request by offtherailz**
## Description
 Introduced noRoot option to skip root rendering of plugins that doesn't make sense in a stand-alone context. This solves also the problem notified in #4876 setting `noRoot` option for the Playback plugin. 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#4876

**What is the new behavior?**
Playback is rendered only in timeline. 

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by offtherailz** [comment]
@mbarto 
Good point. No, it can't. It have been developed to separate concerns of playback from the specific timeline implementation. Anyway, as you say, it's only a part of the timeline. 
Apart from it (maybe some future refactor can join the two plugin, `noRoot` make sense per-se, right? It is not a duplication of some existing option that I ignore, isn't it?

**Comment by mbarto** [comment]
Time of refactor is now, in my opinion, because this solves the original issue, and does not introduce more complexity (new configuration options)

**Comment by offtherailz** [comment]
A refactor like this is 0 gain, can introduce many bugs a requires a lot of work. And the result may not surely be better then the previous. 
Adding one (optional) configuration option, that makes sense in any case, ... well ... I think is a good compromise, in terms of cost-benefits. It is fully covered by tests, 1 line of code, so maintainance should not cost that much ( I think nothing )

**Comment by mbarto** [comment]
@offtherailz if you prefer I can do the refactor work by myself

**Comment by offtherailz** [comment]
I see this is the only point. I'm going to merge, we need this now.

**Pull request merged**
