### PR TITLE
#8551 fix dashboard embedded crash error

### PR DESCRIPTION
**Pull request by MV88**
## Description

it was missing a fix on embedded-template files

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#8551

**What is the new behavior?**

no error due to bowser are triggered

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by dsuren1 — CHANGES_REQUESTED** [review]
@MV88 
PR changes looks fine and the embedded template loads fine.

However, the embedded dashboard crashes with the following error. Could you please check if you encounter the same issue and if so should we open a separate ticket?

image

**Comment by MV88** [comment]
@dsuren1 I have found the reason, basically it was missing re registration of rxjsConfig since probably with modularity this was done in some observable no longer imported in dashboard, in fact here it was written to externalize it
https://github.com/geosolutions-it/MapStore2/blob/854c32c43f6c4b728f740ee1c3b6e9ad6cc3dd22/web/client/components/geostory/layouts/sections/enhancers/updateCurrentPageEnhancer.jsx#L10-L14
I think we can open a dedicated issue for that, in the meantime the dashboard is loading fine now
going to push the fix

**Review by dsuren1 — APPROVED** [review]
LGTM!

**Comment by dsuren1** [comment]
@ElenaGallo Kindly test it in DEV once deployed. Thanks!

**Comment by ElenaGallo** [comment]
Test passed, @dsuren1 please backport to stable branch

**Comment by MV88** [comment]
@ElenaGallo I have done initial PR, so it's me that has to do the backport

**Pull request merged**
