### PR TITLE
6217-style-charts-improvement

### PR DESCRIPTION
**Pull request by ashraf-alsamman**
## Description
style-charts-improvement
related to issue https://github.com/geosolutions-it/mapstore2/issues/6217

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by offtherailz** [comment]
The issue was still in inbox, so not ready to be worked. 
In fact we still have to define well the changes to apply. (also the value on top is wrong, and we have to decide if to aggregate as in pie or leave the pices separated).

From the PR I can not see any visible changes. 
image


going to close this PR.

**Comment by ashraf-alsamman** [comment]
New Project

**Comment by ashraf-alsamman** [comment]
New Project

**Comment by ashraf-alsamman** [comment]
and u can also add this 

.point path{
    stroke: white !important;
    stroke-width: 1 !important;
}

to the same less file

**Pull request closed without merging**
