### PR TITLE
add serverType option to wms & csw catalog entries #8167

### LINKED ISSUE #7809: failure to print WMS layers coming from mapproxy
## Description
similar to #7705, but for WMS protocol

## How to reproduce

- go to https://mapstore.geosolutionsgroup.com/mapstore/#
-  add wms service from https://tiles.craig.fr/pci/service
- add `cadastre` layer
- zoom to 'Clermont Ferrand'
- try to print pdf

*Expected Result*
the pdf should contain data from WMS layer

*Current Result*
the image shows `Invalid request: invalid tile size (use 256x256)`, probably because in the POST data ms2 sends `TILED=true` (added by https://github.com/geosolutions-it/MapStore2/blob/master/web/client/utils/PrintUtils.js#L490).

the postdata sent to mfprint has this:
```
{
    "baseURL": "https://tiles.craig.fr/pci/service?",
    "opacity": 1,
    "singleTile": false,
    "type": "WMS",
    "layers": [
        "cadastre"
    ],
    "format": "image/png",
    "styles": [
        ""
    ],
    "customParams": {
        "TRANSPARENT": true,
        "TILED": true,
        "EXCEPTIONS": "application/vnd.ogc.se_inimage",
        "scaleMethod": "accurate",
        "ENV": ""
   }
}
```

The WMS request sent by mfprint to mapproxy looks like this:
https://tiles.craig.fr/pci/service?BBOX=335973.47%2C5827852.5%2C339748.2%2C5832086.0&WIDTH=713&HEIGHT=800&format_options=dpi%3A96&map_resolution=96&FORMAT=image%2Fpng&STYLES=&ENV=&LAYERS=cadastre&EXCEPTIONS=application%2Fvnd.ogc.se_inimage&TILED=true&SRS=EPSG%3A3857&REQUEST=GetMap&VERSION=1.1.1&SERVICE=WMS&scaleMethod=accurate&TRANSPARENT=true

which reproduces the error. Without `TILED=true` the query succeeds.

The same layer successfully prints when being added/queried as WMTS since #7705.

- [x] Not browser related

From my understanding of WMS, if using `TILED=true` the `HEIGHT` and `WIDTH` parameters should match the server tile size (which at that point mapstore knows, since it uses it to display the layer?).

@offtherailz, any idea ?

### LINKED ISSUE #7877: set TILED=true only when printing layers from geoserver
## Description
printing layers coming from mapproxy WMS fails because it sets `TILED=true` ,cf proposed solution in #7811

*Expected Result*

- wms printing should succeed

*Current Result*

- mapproxy replies with an exception

*Solution*
it was proposed in #7811 to drop TILED from requests, but that's been rejected in favor of making it a global or per-server setting. Automagically deciding to set TILED whether the remote is detected as being geoserver being an option.

### LINKED ISSUE #7879: set TILED=true only when loading layers from geoserver
## Description
slightly different from #7877, loading a WMS layer from mapproxy, mapstore inconditionally adds the `TILED=true` parameter by default to all WMS requests.

In some mapproxy setup using 'mixed' caches (such as the `ortho` layer from `https://tiles.craig.fr/ortho/service`) this triggers an exception mapproxy-side which replies with `<ServiceException>Invalid request: invalid tile format, use mixed</ServiceException>`.

example: https://tiles.craig.fr/ortho/service?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image/jpeg&TRANSPARENT=true&LAYERS=ortho&STYLES=&SRS=EPSG:3857&CRS=EPSG:3857&TILED=true&WIDTH=256&HEIGHT=256&BBOX=626172.1357121654,5557277.704445455,704443.6526761858,5635549.221409475

removing `TILED=true` from the URL works to load a single tile, or going to the layer properties and checking 'singletile' also works within mapstore.

## How to reproduce

-  
- 

*Expected Result*
loading a WMS layer from mapproxy should work

*Current Result*
it fails

## Other useful information
interoperability is hard - `TILED=true` should only be added if we know we're talking to geoserver, or should be behind a configurable toggle per-server ?

### PR DESCRIPTION
**Pull request by landryb**
if undefined or set to "geoserver", the behaviour is unchanged. If set to "no-vendor", then TILED query parameter isnt sen't to the remote wms server, and the "tiled" and "localizedLayerStyles" options are hidden in the layer parameters.

more vendor options can be sent/avoided this way. Improves interoperability when displaying and printing layers coming from mapproxy.

closes #7809
closes #7877
closes #7879

## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Feature
 
## Issue

**What is the current behavior?**

#7809, #7877 & #7879

**What is the new behavior?**
can display and print layers coming from mapproxy, once "no-vendor" is set for the catalog entry.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [x] No

## Other useful information

- https://github.com/geosolutions-it/MapStore2/issues/8167#issuecomment-1479720443 is .. strange.

- 4b09ed555c isnt included after discussion with @allyoucanmap - widget codepaths have to be revisited ?

### CODE REVIEW

**Comment by landryb** [comment]
i see the `saveMapConfiguration` tests are failing, i think can fix that.

**Comment by allyoucanmap** [comment]
@landryb I just pushed a commit with the support fot serverType in dashboard so you need to update your local branch

**Comment by allyoucanmap** [comment]
@landryb I also included the fix mentioned here https://github.com/geosolutions-it/MapStore2/issues/8167#issuecomment-1480890381

**Comment by allyoucanmap** [comment]
@landryb if you could confirm that the pending problems has been solved by the new commits then I'm going to do a final review, thanks

**Comment by landryb** [comment]
i've pulled locally your last commits, and with[986ea75](https://github.com/geosolutions-it/MapStore2/pull/9048/commits/986ea7592a4ebbd31593f239d8ae92105818d478)  the serverType selection works for csw catalogs in the map.

I've also added pre-configured `no-vendor` and `geoserver` entries to the `services` array of `DashboardEditor` plugin config, the value of `serverType` is properly propagated there, and adding layers from such catalogs shows the correct behaviour (eg TILED sent when `serverType` is GEOSERVER only), so [5000365](https://github.com/geosolutions-it/MapStore2/pull/9048/commits/5000365e306f5b0c7461d532a7da5f9238e80ba8) seems to be correct.

**but** the only thing that isn't working seem to be the `serverType` selection in a csw catalog in the dashboard editor.
Peek 23-03-2023 13-15

it's as if 986ea75 didnt have any effect for the csw catalogs in the dashboard editor.

**Comment by landryb** [comment]
> @landryb it seems an issue related to the service object not correctly updated, here the fix [bdf7c90](https://github.com/geosolutions-it/MapStore2/commit/bdf7c909136fd81913cf5619f3e52b3b3cdf98b8)

thanks, can confirm that with this commit, the broken behaviour in the csw & wms catalog entries advanced properties is fixed in the dashboard editor, changing serverType/tilesize is directly updated in the UI. LGTM!

**Comment by ElenaGallo** [comment]
Hi @landryb @allyoucanmap 

once added 'cadastre' layer from 'https://tiles.craig.fr/pci/service' and 'ortho' layer from 'https://tiles.craig.fr/ortho/service' with NO_VENDOR as Server Type layers are visible but it is not possible to print them. The following error appears:

> Error while generating PDF:
org.mapfish.print.InvalidJsonValueException: spec.layers[1].baseURL has an invalid value:  https://tiles.craig.fr/ortho/service ? (Illegal character in scheme name at index 0:  https://tiles.craig.fr/ortho/service ?)
	at org.mapfish.print.map.readers.HTTPMapReader.<init>(HTTPMapReader.java:74)
	at org.mapfish.print.map.readers.TileableMapReader.<init>(TileableMapReader.java:42)
	at org.mapfish.print.map.readers.WMSMapReader.<init>(WMSMapReader.java:98)
	at org.mapfish.print.map.readers.WMSMapReader.<init>(WMSMapReader.java:46)
	at org.mapfish.print.map.readers.WMSMapReader$Factory.create(WMSMapReader.java:84)
	at org.mapfish.print.map.readers.MapReaderFactoryFinder.create(MapReaderFactoryFinder.java:36)
	at org.mapfish.print.map.MapChunkDrawer.renderImpl(MapChunkDrawer.java:120)
	at org.mapfish.print.ChunkDrawer.render(ChunkDrawer.java:55)
	at org.mapfish.print.config.layout.MapBlock$1.render(MapBlock.java:77)
	at org.mapfish.print.PDFCustomBlocks.addAbsoluteDrawer(PDFCustomBlocks.java:187)
	at org.mapfish.print.config.layout.MapBlock.render(MapBlock.java:73)
	at org.mapfish.print.config.layout.Page.render(Page.java:80)
	at org.mapfish.print.config.layout.Layout.render(Layout.java:64)
	at org.mapfish.print.output.AbstractOutputFormat.doPrint(AbstractOutputFormat.java:31)

**How to Reproduce**
- Open [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/43679)
- Follow the steps in the video below:

https://user-images.githubusercontent.com/56537133/227491570-144289ed-401e-44cf-a95b-134a11fae10c.mov

**Comment by landryb** [comment]
hi @ElenaGallo , the map link you gave requires login and i havent been able to login with either admin/admin or user/user. In your video i see the STR, but can't see what's the wrong request done by the print module.

i've tried reproducing your map (gzipped & attached below), adding two wms layers from mapproxy, and here it correctly generates a pdf preview.
[test-print-mapproxy.json.gz](https://github.com/geosolutions-it/MapStore2/files/11060955/test-print-mapproxy.json.gz)

**Comment by landryb** [comment]
the POST done to http://localhost:8081/proxy/?url=http%3A%2F%2Flocalhost%3A8080%2Fmapstore%2Fpdf%2Fcreate.json  had this attached payload
[post.json.gz](https://github.com/geosolutions-it/MapStore2/files/11061036/post.json.gz)

**Comment by landryb** [comment]
wild guess from the error message, would there be an extra space between `service` and `?` in the POST data sent in your map ?

**Comment by ElenaGallo** [comment]
@landryb sorry, now the map is public. In any case, now I can print and everything works as it should. Thanks

**Comment by ElenaGallo** [comment]
@allyoucanmap the rest passed on DEV, @landryb please backport to 2023.01.xx. Thanks

**Pull request merged**
