### PR TITLE
Updating default background configuration

### PR DESCRIPTION
**Pull request by tdipisa**
## Description

Default background layers list has been updated including GeoSolutions OSM ones.

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [X] Other... Please describe: configuration update

## Issue

**What is the current behavior?**

#9361 

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by offtherailz** [comment]
Accordingly to the deprecation timeline, you did the build at the first  brownout (see [here](https://blog.readthedocs.com/use-build-os-config/).
Given that this is not an issue of this specific PR, let me open a new issue in order to fix our builds before the final deprecation: 

Here the schedule:

```
Monday, August 28, 2023: Do the first brownout (temporarily enforce this deprecation) for 12 hours: 00:01 PST to 11:59 PST (noon)

Monday, September 18, 2023: Do a second brownout (temporarily enforce this deprecation) for 24 hours: 00:01 PST to 23:59 PST (midnight)

Monday, October 2, 2023: Do a third and final brownout (temporarily enforce this deprecation) for 48 hours: 00:01 PST to October 3, 2023 23:59 PST (midnight)

Monday, October 16, 2023: Fully remove support for building documentation using “build.image” on the configuration file
```

**Comment by tdipisa** [comment]
@offtherailz @allyoucanmap please re-review

**Comment by tdipisa** [comment]
@offtherailz @allyoucanmap I've included a commit to configure tile size to 512 for layers supporting it. I will get in touch with @randomorder in a second time for changing the GWC config on the GS side and enable the same also for other BGs with a new PR.

**Review by offtherailz — APPROVED** [review]

**Review by allyoucanmap — APPROVED** [review]

**Comment by ElenaGallo** [comment]
@tdipisa 
- The new thumbnail backgrounds are broken 
rotti

- When a new map is opened, the default background is `OSM` but `OSM Bright` is highlighted in the background selector


https://github.com/geosolutions-it/MapStore2/assets/56537133/e78f52aa-ca6b-4a64-9f75-2cdf8667d554

**Comment by tdipisa** [comment]
@ElenaGallo yes there is already a PR ti fix this
https://github.com/geosolutions-it/MapStore2/pull/9374

**Comment by ElenaGallo** [comment]
@tdipisa this problem is still present:

> - When a new map is opened, the default background is `OSM` but `OSM Bright` is highlighted in the background selector

https://github.com/geosolutions-it/MapStore2/assets/56537133/879d8248-e775-4757-ab24-6847f7876b4f

**Comment by ElenaGallo** [comment]
@tdipisa please backport this to 2023.02.xx. Thanks

**Comment by tdipisa** [comment]
> @tdipisa please backport this to 2023.02.xx. Thanks

The plan is changed. This will not be part of 2023.02.00, so this will be backported later

**Pull request merged**
