### PR TITLE
#5623: Improved icon image input

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description

This PR improves the icon input of the visual style editor. The input displays an error message when the url is empty or not valid.

This is part of the work started in this PR https://github.com/geosolutions-it/MapStore2/pull/5851

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Feature

## Issue

**What is the current behavior?**

#5623

**What is the new behavior?**

 The input displays an error message when the url is empty or not valid.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [x] No

### CODE REVIEW

**Review by offtherailz — COMMENTED** [review]
A couple of things I noticed:
1. If I write the URL and it is failing, it anyway allow to save
image
Anyway I'm not sure if this URI can be also a local path, so allowing it even if the image is unreachable from the client is a feature. In this case should not say "Invalid URL" but only a warning "not able to retrive the icon". Otherwise maybe denying the apply makes sense.

2. Data URI like this, passed as input, are valid anyway, but not correctly handled by GeoServer (at least this svg, not sure for img URL) Should we check the validity of the URL ?
```
data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMWVtIiBoZWlnaHQ9IjFlbSIgdmlld0JveD0iMCAwIDE2IDE2IiBjbGFzcz0iYmkgYmktYWxhcm0tZmlsbCIgZmlsbD0iY3VycmVudENvbG9yIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciPgogIDxwYXRoIGZpbGwtcnVsZT0iZXZlbm9kZCIgZD0iTTYgLjVhLjUuNSAwIDAgMSAuNS0uNWgzYS41LjUgMCAwIDEgMCAxSDl2MS4wN2E3LjAwMSA3LjAwMSAwIDAgMSAzLjI3NCAxMi40NzRsLjYwMS42MDJhLjUuNSAwIDAgMS0uNzA3LjcwOGwtLjc0Ni0uNzQ2QTYuOTcgNi45NyAwIDAgMSA4IDE2YTYuOTcgNi45NyAwIDAgMS0zLjQyMi0uODkybC0uNzQ2Ljc0NmEuNS41IDAgMCAxLS43MDctLjcwOGwuNjAyLS42MDJBNy4wMDEgNy4wMDEgMCAwIDEgNyAyLjA3VjFoLS41QS41LjUgMCAwIDEgNiAuNXpNLjg2IDUuMzg3QTIuNSAyLjUgMCAxIDEgNC4zODcgMS44NiA4LjAzNSA4LjAzNSAwIDAgMCAuODYgNS4zODd6TTExLjYxMyAxLjg2YTIuNSAyLjUgMCAxIDEgMy41MjcgMy41MjcgOC4wMzUgOC4wMzUgMCAwIDAtMy41MjctMy41Mjd6TTguNSA1LjVhLjUuNSAwIDAgMC0xIDB2My4zNjJsLTEuNDI5IDIuMzhhLjUuNSAwIDEgMCAuODU4LjUxNWwxLjUtMi41QS41LjUgMCAwIDAgOC41IDlWNS41eiIvPgo8L3N2Zz4K
```
Please @giohappy clarify if these things I noticed are blocking issues or we can move this to a future improvement.

**Comment by giohappy** [comment]
@allyoucanmap why did you set the ALMAVIVA icon here?
This issue wasn't raised by the customer, so from my point of view it's noeither blocker nor a priority. 
I'll leave @tdipisa and @simboss decide if / when to address this.

**Comment by allyoucanmap** [comment]
@giohappy this is a part of the review made for the Visual Style Editor PR https://github.com/geosolutions-it/MapStore2/pull/5604#pullrequestreview-443727656. We did not completed it at that time because we needed the Visual Style Editor plugin merged as soon as possible and we considered this a minor priority issue. This PR was started by alper on Septemper 10 https://github.com/geosolutions-it/MapStore2/pull/5851 and we completed this PR to keep the work already done  All the issues related to the PR of Visual Style Edtitor were labeled as part of ALMAVIVA project (there are still issues open with the label).

**Comment by giohappy** [comment]
So, I confirm that this can be tracked as ALMAVIVA @allyoucanmap.
@offtherailz if those two issues you found don't take much time (they look quite straightforward) I would include them in this PR.

**Comment by offtherailz** [comment]
Ok, what do you think @allyoucanmap, could you improve this PR with the suggested changes?

**Comment by allyoucanmap** [comment]
@offtherailz I'll take a look and let you know if feasable as quick fix

**Comment by allyoucanmap** [comment]
@offtherailz

I updated the PR adding warnings and errors. The errors will disable the save action while warning will only alert that the src could not be supported by some renderer.

errors (save action disabled):

- empty src
image

- invalid base64 image
image


warnings (save action enable):

- valid base64 image not supported on some style renderer
image

- loading error of the image resource. This could be due to different reason so in my opinion we should alert the user keeping save button enabled.

image

**Review by offtherailz — APPROVED** [review]

**Comment by tdipisa** [comment]
@allyoucanmap can you please backport this to 2021.01.xx for the release?

**Comment by allyoucanmap** [comment]
@tdipisa done https://github.com/geosolutions-it/MapStore2/pull/6408

**Pull request merged**
