### PR TITLE
#7409 add documentation to for metadataTool

### PR DESCRIPTION
**Pull request by offtherailz**
## Description
as for #7409 
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [x] Other... Please describe: Documentation

## Issue

**What is the current behavior?**

#7409

**What is the new behavior?**
Documented 

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by tdipisa — APPROVED** [review]

**Comment by tdipisa** [comment]
Thank you @offtherailz please backport to 2021.02.xx

**Comment by offtherailz** [comment]
The regression has been cause by: 
Issue #7361; feature info selector fixed (#7387)
checked using `git bisect`. In the `good` tasks, I had an error in console, but no complete failure.

**Comment by tdipisa** [comment]
> The regression has been cause by: Issue #7361; feature info selector fixed (#7387) checked using `git bisect`. In the `good` tasks, I had an error in console, but not a complete failure.

Is it maybe a comment for https://github.com/geosolutions-it/MapStore2/issues/7379 ?

**Comment by offtherailz** [comment]
Yes sorry, deleted to avoid confusion

**Pull request merged**
