### PR TITLE
#8740 Move the mouse on 3D Tiles

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description

Currently queryable false is available only on WFS and for this reason if was failing on top of 3D tiles because they are not inside an entity collection. This PR adds the queryable property also on Vector layer and improve the filter of drillPick

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**

#8740

**What is the new behavior?**

The application does not return an error in console and the 3D tiles are queryable again

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [x] No

### CODE REVIEW

**Review by dsuren1 — CHANGES_REQUESTED** [review]
@allyoucanmap 
LGTM

Not sure if this related to this PR. However wanted to highlight. I get this error when traversing the [3d map](http://localhost:8081/?debug=true#/viewer/cesium/38732)
image

**Comment by allyoucanmap** [comment]
@dsuren1 as discussed let's solve this in the Model PR because related to style editing

**Review by dsuren1 — APPROVED** [review]

**Comment by dsuren1** [comment]
@ElenaGallo 
Kindly test in DEV and let us know if it's good to be backported. Thanks!

**Comment by ElenaGallo** [comment]
Test passed on DEV. @dsuren1 please backport. Thanks.

**Pull request merged**
