### PR TITLE
Fix #9295 added better handling of format in csw service

### LINKED ISSUE #9295: Format and Information sheet format fields not populated in GN CSW catalog source
## Description

Contents for _Format_ and _Information sheet format_ fields are not properly fetched in Advanced Settings of a GeoNetwork CWS catalog source (eg. using [this](http://geonetwork.comune.intranet/geonetwork/srv/ita/csw) in c027 VPN).

## How to reproduce

-  Open the map viewer and configure a CSW source against GeoNetwork
- Open the advanced settings and try to expand the _Format_ or _Information sheet format_ fiels

*Expected Result*

Contents in drop down are fetched 

*Current Result*

Contents in drop down are not fetched. Wrong request performed by MS in this case 

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### PR DESCRIPTION
**Pull request by MV88**
## Description

providing an enhancement for format handling in csw

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

Fix #9295

**What is the new behavior?**

image

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by allyoucanmap — CHANGES_REQUESTED** [review]
The workflow seems fine, few changes:

- [ ] The format refresh button is not disabled when server type `no vendor` is selected
- [ ] I would like to propose a different structure for the UI. I suggest to apply a single control label and input for each FormGroup (see [forms](https://react-bootstrap-v3.netlify.app/components/forms/))

Normal:

image

No vendor selected:

image

Error:

image

**Comment by tdipisa** [comment]
@allyoucanmap 

> I would like to propose a different structure for the UI. I suggest to apply a single control label and input for each FormGroup (see [forms](https://react-bootstrap-v3.netlify.app/components/forms/))

This make sense. Let's evaluate the effort @MV88

**Comment by MV88** [comment]
on it since it should a quick change

**Comment by MV88** [comment]
@allyoucanmap 
there are some extra parts i have changed

image
image

**Review by allyoucanmap — APPROVED** [review]
The style is fine, I just pushed a commit to remove css, review select input and to remove text bold from format selects
image

**Comment by MV88** [comment]
@ElenaGallo please test it in DEV

**Comment by ElenaGallo** [comment]
Test passed, @MV88 please backport this. Thanks

**Pull request merged**
