### PR TITLE
#8718 geostyler: 3D - elevation properties

### PR DESCRIPTION
**Pull request by belom88**
## Description
Add new properties to geostyler for 3D elevation
For "Height reference" "toolbar" control is used. For "Height" - new component has been created:
image

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [X] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
#8718

**What is the new behavior?**
To control Mark and Icon elevation, new properties to geostyler were added.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by allyoucanmap — CHANGES_REQUESTED** [review]
There was an issue on restoring the original position of the point coordinates because by default the height was always set to zero.
Testing with a vector layer like this:

```js
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "coordinates": [
          8.893723941824277,
          44.41825307744699,
          50
        ],
        "type": "Point"
      }
    },
    {
      "type": "Feature",
      "properties": {
        "z": 20
      },
      "geometry": {
        "coordinates": [
          8.944385923748285,
          44.41313971256531,
          1000
        ],
        "type": "Point"
      }
    },
    {
      "type": "Feature",
      "properties": {
        "z": 100
      },
      "geometry": {
        "coordinates": [
          8.976508557215539,
          44.39845269171934,
          500
        ],
        "type": "Point"
      }
    }
  ]
}
```
image

I would expect to have the point located at the geometry height when the height reference is none or relative while now it fallback always to 0 meter.
@belom88 Here there is a patch PR on your branch, please review and merge so we can update this one, thanks 

https://github.com/belom88/MapStore2/pull/1

**Review by allyoucanmap — APPROVED** [review]

**Comment by allyoucanmap** [comment]
@ElenaGallo please test on dev, thanks.
you can use this GeoJSON
[points.zip](https://github.com/geosolutions-it/MapStore2/files/9879360/points.zip)

**Comment by belom88** [comment]
@allyoucanmap @tdipisa @ElenaGallo , goodbye and best wishes!

**Comment by tdipisa** [comment]
@ElenaGallo let us know also for the backport to the stable branch.

@belom88 thank you so much for this.

**Comment by ElenaGallo** [comment]
Test passed on DEV. @belom88 please backport to 2022.02.xx. Thanks

**Pull request merged**
