### PR TITLE
#4337 langbar

### PR DESCRIPTION
**Pull request by QSafariallahkheili**
## Description
Solves the react warning caused by placing button inside another button

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#4337 

**What is the new behavior?**
See the description

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by MV88 — CHANGES_REQUESTED** [review]
can you add a bit of space to the left of the flag so it seems to be in the middle
to have the same space between the flag and the caret
so that the flag is not attached to the left border

also this test is failing
**checks button click fires the proper action**

can you check?

**Comment by QSafariallahkheili** [comment]
Langbar performance & styling 

https://user-images.githubusercontent.com/50631096/125591316-281d773e-3f15-487e-987a-f4a0693a32f1.mp4

**Review by MV88 — APPROVED** [review]
thanks it works pretty

**Comment by MV88** [comment]
@ElenaGallo please test it in DEV

**Pull request merged**
