### PR TITLE
NL translations update v2024.01.02

### PR DESCRIPTION
**Pull request by ygodaert**
## Description
Dutch translation update, based on the latest release v2024.01.02

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [x] Other... Please describe: translations update

## Issue

**What is the current behavior?**
Outdated Dutch translations

**What is the new behavior?**
Updated Dutch translations

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by tdipisa** [comment]
@ygodaert thank you so much for contributing. Waiting for the review.

**Review by offtherailz — DISMISSED** [review]
I can approve for sure this contribution. 
Anyway @ygodaert if you run 

```
npm run i18n
```

You can see that there are 3 messages still missing.

```
data.nl-NL.json
-->     messages.layerProperties.enableInteractiveLegendInfo is missing
-->     messages.streetView.messages.errorServiceUrl is missing
-->     messages.streetView.messages.errorRetriveingLayerData is missing
--> data.nl-NL.json FAILED
```

I suggest to use this command line tool that is very useful to find missing translations in files.

The PR is mergiable technically, you can contribute these missing strings (if you want) contextually in this PR.
Anyway there is anyway the possibility to contribute them in the future, in a separate PR.


I'll wait your response, I set a note for July the 30th, when I will merge it anyway.
As I said there is no rush or warries about contributing them in a second time. Let me know.

Another note, you are contributing to master but the fix is intended to go for v2024.01.02 
Do you want to provide a PR also for the stable branch?

**Review by offtherailz — COMMENTED** [review]
https://github.com/geosolutions-it/MapStore2/pull/10482#pullrequestreview-2194180795

**Comment by offtherailz** [comment]
https://github.com/geosolutions-it/MapStore2/pull/10482#pullrequestreview-2194180795

**Comment by ygodaert** [comment]
Thank you for the feedback @offtherailz. We prefer to provide a new PR when we implement a new release. I will then update the translations based on the master branch instead of the last stable released branch.

**Review by offtherailz — APPROVED** [review]

**Pull request merged**
