### PR TITLE
#7754 Update bootstrap to the latest available v3

### PR DESCRIPTION
**Pull request by alexander-fedorenko**
## Description
Update bootstrap to the 3.4.1 version.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [x] Other... Please describe: Library update

## Issue

**What is the current behavior?**
#7754 

**What is the new behavior?**
Library is updated to the version 3.4.1, "react-bootstrap" version is kept untouched.
Tested all the components and plugins that use "react-bootstrap" components.
It breaks nothing, following spreadsheet contains test results along with the items that require specific environment and/or configuration for testing. Please note there's also a summary tab that shows ratio of successful component checks to the total usage count of component.
https://docs.google.com/spreadsheets/d/1DDyScCv9htif-apZHDhyqP_8qf6UGLBPxj9g7MJ5YI4/edit?usp=sharing

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by tdipisa** [comment]
Thank you so much @alexander-fedorenko for all your effort and the precise report. @allyoucanmap I would like to have you to review this.

**Review by allyoucanmap — APPROVED** [review]
LGTM.

Thanks @alexander-fedorenko for the spreadsheet, @tdipisa maybe we could use this information to remove all the deprecated or unsupported components or reduce the use of react-bootstrap in a separated issue. It seems some of `needInfo` or `deprecated` components are not used by MapStore indeed. The current version of react-bootstrap used by MapStore supports the 3.3.x version of bootstrap but taking a look to the releases notes of 3.4.0 and 3.4.1 we can see only bug fixes on the security part and minor changes that are compatible with our current environment.

releases notes:
- [bootstrap v3.4.0](https://github.com/twbs/bootstrap/releases/tag/v3.4.0)
- [bootstrap v3.4.1](https://github.com/twbs/bootstrap/releases/tag/v3.4.1)

**Comment by allyoucanmap** [comment]
@ElenaGallo please test in DEV, thanks

**Comment by tdipisa** [comment]
Thank you so much @allyoucanmap and @alexander-fedorenko

>  @tdipisa maybe we could use this information to remove all the deprecated or unsupported components or reduce the use of react-bootstrap in a separated issue.

I think so @allyoucanmap. Can you please open that issue and assign it to me?

**Pull request merged**
