### PR TITLE
#7652: output format selection plugin for Print, #7689: projection selection plugin for Print

### PR DESCRIPTION
**Pull request by mbarto**
## Description

This PR adds a couple of subplugins for Print:
 - an output format selection plugin, that enables exporting the printed map into an image format, as supported by the mapfish-print engine

image

 - a projection switcher for the printed map, that enables printing in a different coordinate system than the one on screen

image

Neither is included by default in the product or standard project.

As a bonus (needed for the two plugins above):
 - MapUtils.getResolutions has been improved, so that a crs can be specified to get resolutions for a specific coordinate system
 - the printingService used by the Print plugin has been extended to accept custom validators (functionality that validates user input, so that errors/warnings can be shown on the UI) and map transformers (transformers that work on the map object for the preview widget, instead of the final spec payload)

### Output Format plugin
Important things to know:
 - to enable mapfish-print support for alternative formats, a formats property is needed in config.yaml, for this reason I added "formats: '*'" that enables all supported formats
 - an alternative ImageViewer has been implemented that is automatically used instead of the PDF one, depending on the current outputFormat
 - some of the formats produced by mapfish-print are not shown by common browsers (e.g. TIFF), so a warning is shown if one of those is selected by the user (download of the produced file is always possible)

### Project Selection plugin
Important things to know:
 - by default, map preview is disabled when a crs different than the screen one is chosen, this can be overridden setting allowPreview=true in the plugin configuration; we may switch to have this enabled by default in the future if the preview will be stable enough when tested with weird projections
 - by default all configured projections are shown, but this can be restricted by configuration

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
#7692 
#7694 
#7652
#7689

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
Cool: here I report some things I noticed while testing:

- [ ] The download URL contains the proxied URL, but it is not needed. In this case it fails because of formats allowed by the proxy. We should use the normal URL. If use target="_blank" it should be ok.
image
- [ ] When I add Projection selector, if I select GOOGLE or 4629 from the default list presented, i have a "Ops...something went wrong screen" , with this error: 
```
ypeError: Cannot read properties of undefined (reading 'degrees')
    at OpenlayersMap.eval [as getResolutions] (Map.jsx:100:110)
    at eval (Map.jsx:305:21)
    at getResolutions (MapUtils.js:261:39)
    at reprojectZoom (Projection.jsx:40:91)
    at mapTransformer (Projection.jsx:88:18)
    at getMapTransformerChain.map.reduce._state$print (PrintUtils.js:537:16)
    at Array.reduce (<anonymous>)
    at Object.getMapConfiguration (PrintUtils.js:536:63)
    at Print.eval [as renderPrintPanel] (Print.jsx:338:54)
    at Print.eval [as renderBody] (Print.jsx:388:27)
    at Print.render (Print.jsx:516:124)
    at finishClassComponent (react-dom.development.js:18407:31)
    at updateClassComponent (react-dom.development.js:18360:24)
    at beginWork$1 (react-dom.development.js:20108:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:362:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:411:16)
```
- [ ] When export is reprojected in 4326 vector data do not work. Moreover the OSM background seems to be used in a wrong way. Same happens when I start from 4326 from map's projection selector.
image

Please let me know if I missed something or if some  of these tasks are already scheduled.

**Comment by offtherailz** [comment]
Completely agree with everything @mbarto . 
Because of the force-push, I 'm not able to see recent changes in the code, after my review. 
Tomorrow I'll try to give you a review, checking the commits one by one.

**Review by offtherailz — APPROVED** [review]

**Comment by offtherailz** [comment]
I put all the issues linked in test. Anyway nothing can be tested on Dev instance.
@mbarto and @tdipisa  can you take care of them to get tested on the proper infrastructure?

**Comment by offtherailz** [comment]
My considerations about enabling it by default: 
If we want to do it, maybe we should make them standard panels, instead of optional plugins, and they should be configured by default with a very small set of controllable formats and projections that make sense. 
For instance, only EPSG:4326 and EPSG:3847 and PDF/JPEG.
- Other formats are unuseful to 99 % of users (moreover the tiff formats and so on ar not georeferenced, so 2 times unuseful)
- Or projections are not necessary at all. We have to complete the part 

Moreover, we need to complete the missing parts: 
 - Vector working reprojected
 - OSM disabled when reprojected.

Finally, we need to make sure to align the backend configuration (formats: '*') for all the customers that will align it.

Please @mbarto correct me if I'm wrong, or Itegrate whatever you think is important

**Comment by tdipisa** [comment]
@mbarto @offtherailz this work will land in a MS release. Having these new printing options enabled and usable, even with a restricted default configuration is part of the game as usual. Generally we should avoid having hidden features not known to most people, all these new options can be generally useful, therefore they should be enabled by default. Please proceed at your convenience by implementing the above considerations.

**Comment by mbarto** [comment]
> @mbarto is there a client environment where we can test this printing updates? Otherwise, and in any case, I think these should be enabled on master to be available on DEV for testing @offtherailz @mbarto. All related issues are new features and/or enhancements (I've assigned 2022.01.00, waiting @simboss for confirmation), therefore, why not having them enabled on master as usual?

No, we have still to prepare it. The client asked this functionality for geonode, so it will probably be a custom geonode project.
If you prefer to have this functionalities enabled by default, we can do it, of course.

All @offtherailz comments are appropriate, so I will not add more.

**Comment by tdipisa** [comment]
> > @mbarto is there a client environment where we can test this printing updates? Otherwise, and in any case, I think these should be enabled on master to be available on DEV for testing @offtherailz @mbarto. All related issues are new features and/or enhancements (I've assigned 2022.01.00, waiting @simboss for confirmation), therefore, why not having them enabled on master as usual?
> 
> No, we have still to prepare it. The client asked this functionality for geonode, so it will probably be a custom geonode project. If you prefer to have this functionalities enabled by default, we can do it, of course.
> 
> All @offtherailz comments are appropriate, so I will not add more.

@mbarto it would be good to have them active at least initially for a test in DEV.

**Comment by offtherailz** [comment]
@mbarto Could I open an issue for the pending tasks for this PR.

Could you please conplete the description summarising the tasks we need to do to include this in the standard MapStore and the accetpance criteria, accordingly with what we said? 
https://github.com/geosolutions-it/MapStore2/issues/7881

Thank you

**Pull request merged**
