### PR TITLE
#8588: Multi-chart widget improvements

### PR DESCRIPTION
**Pull request by dsuren1**
## Description
This PR improves upon multi-chart widget

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [x] Feature

## Issue

**What is the current behavior?**
https://github.com/geosolutions-it/MapStore2/pull/8684#issuecomment-1287015469
https://github.com/geosolutions-it/MapStore2/pull/8684#issuecomment-1290106695

**What is the new behavior?**
- User can edit chart name
- User can select same layer to create multi view of charts
- Filter per chart is applied properly

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
I've found this small issue: When I edit and accept the chart name, is set to layer name. 

https://user-images.githubusercontent.com/1279510/198084527-8377bcd3-a178-4756-85e4-c63df4dcef90.mp4

The rest works good for me. The workflow is still a little hard for me, but it is ok for the moment.

**Comment by dsuren1** [comment]
@offtherailz 
> I've found this small issue: When I edit and accept the chart name, is set to layer name.

_This issue is now fixed and the PR is ready for re-review_

**Review by offtherailz — APPROVED** [review]

**Comment by offtherailz** [comment]
@ElenaGallo, could you please test this on  DEV  ? Thank you

**Comment by ElenaGallo** [comment]
@dsuren1 @tdipisa Test passed on DEV.

**Pull request merged**
