### PR TITLE
3245: Failed password change attempts are not reported to the user

### PR DESCRIPTION
**Pull request by MuhweziDeo**
## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

#3245 

**What is the current behavior?**
Loading Spinner is not stopped when an error occurs while changing user password and no information is shown to the user
#3245 

**What is the new behavior?**
The spinner stops spinning and an error should be shown to the user

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by allyoucanmap — CHANGES_REQUESTED** [review]
This PR solves partially the request of the issue because this changes avoid the infinite loader spin and shows an error message but it's still not possible to add a password that ends with `&`.

image

@MuhweziDeo Did you try to use the suggested solution to use a application/json content-type in the changePassword request?

https://github.com/geosolutions-it/MapStore2/blob/master/web/client/api/GeoStoreDAO.js#L174-L181

image

**Comment by MuhweziDeo** [comment]
> This PR solves partially the request of the issue because this changes avoid the infinite loader spin and shows an error message but it's still not possible to add a password that ends with `&`.
> 
> image
> 
> @MuhweziDeo Did you try to use the suggested solution to use a application/json content-type in the changePassword request?
> 
> https://github.com/geosolutions-it/MapStore2/blob/master/web/client/api/GeoStoreDAO.js#L174-L181
> 
> image

No, I did not try this option. should  I proceed and implement this

**Comment by MuhweziDeo** [comment]
> This PR solves partially the request of the issue because this changes avoid the infinite loader spin and shows an error message but it's still not possible to add a password that ends with `&`.
> 
> image
> 
> @MuhweziDeo Did you try to use the suggested solution to use a application/json content-type in the changePassword request?
> 
> https://github.com/geosolutions-it/MapStore2/blob/master/web/client/api/GeoStoreDAO.js#L174-L181
> 
> image

This works

**Comment by tdipisa** [comment]
@MuhweziDeo 
please pay attention on what is reported in the issue description next time. There is a reason way a solution has been suggested.

**Comment by MuhweziDeo** [comment]
> @MuhweziDeo
> please pay attention on what is reported in the issue description next time. There is a reason way a solution has been suggested.

Sorry @tdipisa. Will do next time coz I thought the issue was mainly to do with the Spinner. My Apologies on that

**Review by allyoucanmap — APPROVED** [review]

**Comment by tdipisa** [comment]
@ElenaGallo please test this in DEV and let us know if we can proceed with the backport to 2021.01.xx.

**Comment by ElenaGallo** [comment]
@MuhweziDeo test done, can you please backport this to the stable branch? thanks

**Pull request merged**
