### PR TITLE
#8652 Cesium query parameters support

### PR DESCRIPTION
**Pull request by alex-fko**
## Description
This PR adds query parameters support for Cesium viewer.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
#8652 

**What is the new behavior?**
All query parameters are supported in Cesium viewer.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

Useful queries to test it on dev:

Center:
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/new?center=8.92368793487549,44.414175805394656&zoom=16.999999999999325&heading=8.881784197001252e-16&pitch=-1.5707963267948966&roll=0

Bbox
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/new?bbox=-92.59351205468747,40.80211096427987,-82.04663705468745,44.51290644051305

Marker/Zoom
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/new?marker=5,5

MapInfo
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/new?addLayers=unesco:Unesco_point&mapInfo=unesco:Unesco_point&mapInfoFilter=cod_unesco='IT_830'

FeatureInfo
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/10358?featureInfo=-98.863,41.3

AddLayers
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/new?addLayers=unesco:Unesco_point&mapInfo=unesco:Unesco_point&mapInfoFilter=cod_unesco='IT_830'

Background
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/new?background=OpenTopoMap;default_map_backgrounds

Map:
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/new?map={%22version%22%3A2%2C%22map%22%3A%7B%22center%22%3A%7B%22x%22%3A10.02955444304682%2C%22y%22%3A45.20761768954071%2C%22crs%22%3A%22EPSG%3A4326%22%7D%2C%22maxExtent%22%3A%5B-20037508.34%2C-20037508.34%2C20037508.34%2C20037508.34%5D%2C%22projection%22%3A%22EPSG%3A900913%22%2C%22units%22%3A%22m%22%2C%22zoom%22%3A6.993164119541465%2C%22mapOptions%22%3A%7B%7D%2C%22layers%22%3A%5B%7B%22id%22%3A%22mapnik__0%22%2C%22group%22%3A%22background%22%2C%22source%22%3A%22osm%22%2C%22name%22%3A%22mapnik%22%2C%22title%22%3A%22Open%20Street%20Map%22%2C%22type%22%3A%22osm%22%2C%22visibility%22%3Atrue%2C%22singleTile%22%3Afalse%2C%22dimensions%22%3A%5B%5D%2C%22hideLoading%22%3Afalse%2C%22handleClickOnLayer%22%3Afalse%2C%22useForElevation%22%3Afalse%2C%22hidden%22%3Afalse%7D%2C%7B%22id%22%3A%22Night2012__1%22%2C%22group%22%3A%22background%22%2C%22source%22%3A%22nasagibs%22%2C%22name%22%3A%22Night2012%22%2C%22provider%22%3A%22NASAGIBS.ViirsEarthAtNight2012%22%2C%22title%22%3A%22NASAGIBS%20Night%202012%22%2C%22type%22%3A%22tileprovider%22%2C%22visibility%22%3Afalse%2C%22singleTile%22%3Afalse%2C%22dimensions%22%3A%5B%5D%2C%22hideLoading%22%3Afalse%2C%22handleClickOnLayer%22%3Afalse%2C%22useForElevation%22%3Afalse%2C%22hidden%22%3Afalse%7D%2C%7B%22id%22%3A%22OpenTopoMap__2%22%2C%22group%22%3A%22background%22%2C%22source%22%3A%22OpenTopoMap%22%2C%22name%22%3A%22OpenTopoMap%22%2C%22provider%22%3A%22OpenTopoMap%22%2C%22title%22%3A%22OpenTopoMap%22%2C%22type%22%3A%22tileprovider%22%2C%22visibility%22%3Afalse%2C%22singleTile%22%3Afalse%2C%22dimensions%22%3A%5B%5D%2C%22hideLoading%22%3Afalse%2C%22handleClickOnLayer%22%3Afalse%2C%22useForElevation%22%3Afalse%2C%22hidden%22%3Afalse%7D%2C%7B%22id%22%3A%22s2cloudless%3As2cloudless__3%22%2C%22format%22%3A%22image%2Fjpeg%22%2C%22group%22%3A%22background%22%2C%22source%22%3A%22s2cloudless%22%2C%22name%22%3A%22s2cloudless%3As2cloudless%22%2C%22opacity%22%3A1%2C%22title%22%3A%22Sentinel%202%20Cloudless%22%2C%22type%22%3A%22wms%22%2C%22url%22%3A%5B%22https%3A%2F%2F1maps.geo-solutions.it%2Fgeoserver%2Fwms%22%2C%22https%3A%2F%2F2maps.geo-solutions.it%2Fgeoserver%2Fwms%22%2C%22https%3A%2F%2F3maps.geo-solutions.it%2Fgeoserver%2Fwms%22%2C%22https%3A%2F%2F4maps.geo-solutions.it%2Fgeoserver%2Fwms%22%2C%22https%3A%2F%2F5maps.geo-solutions.it%2Fgeoserver%2Fwms%22%2C%22https%3A%2F%2F6maps.geo-solutions.it%2Fgeoserver%2Fwms%22%5D%2C%22visibility%22%3Afalse%2C%22singleTile%22%3Afalse%2C%22dimensions%22%3A%5B%5D%2C%22hideLoading%22%3Afalse%2C%22handleClickOnLayer%22%3Afalse%2C%22useForElevation%22%3Afalse%2C%22hidden%22%3Afalse%7D%2C%7B%22id%22%3A%22undefined__4%22%2C%22group%22%3A%22background%22%2C%22source%22%3A%22ol%22%2C%22title%22%3A%22Empty%20Background%22%2C%22type%22%3A%22empty%22%2C%22visibility%22%3Afalse%2C%22singleTile%22%3Afalse%2C%22dimensions%22%3A%5B%5D%2C%22hideLoading%22%3Afalse%2C%22handleClickOnLayer%22%3Afalse%2C%22useForElevation%22%3Afalse%2C%22hidden%22%3Afalse%7D%2C%7B%22id%22%3A%22unesco%3AUnesco_point__973059b0-5b6b-11ed-8761-ebf209121ca0%22%2C%22format%22%3A%22image%2Fpng%22%2C%22search%22%3A%7B%22url%22%3A%22https%3A%2F%2Fgs-stable.geosolutionsgroup.com%2Fgeoserver%2Fwfs%22%2C%22type%22%3A%22wfs%22%7D%2C%22name%22%3A%22unesco%3AUnesco_point%22%2C%22description%22%3A%22%22%2C%22title%22%3A%22Unesco%20Items%22%2C%22type%22%3A%22wms%22%2C%22url%22%3A%22https%3A%2F%2Fgs-stable.geosolutionsgroup.com%2Fgeoserver%2Fwms%22%2C%22bbox%22%3A%7B%22crs%22%3A%22EPSG%3A4326%22%2C%22bounds%22%3A%7B%22minx%22%3A7.466999156080053%2C%22miny%22%3A36.67491984727563%2C%22maxx%22%3A18.033902263137904%2C%22maxy%22%3A46.656160442453356%7D%7D%2C%22visibility%22%3Atrue%2C%22singleTile%22%3Afalse%2C%22allowedSRS%22%3A%7B%7D%2C%22dimensions%22%3A%5B%5D%2C%22hideLoading%22%3Afalse%2C%22handleClickOnLayer%22%3Afalse%2C%22catalogURL%22%3A%22https%3A%2F%2Fgs-stable.geo-solutions.it%2Fgeoserver%2Fcsw%3Frequest%3DGetRecordById%26service%3DCSW%26version%3D2.0.2%26elementSetName%3Dfull%26id%3Dunesco%3AUnesco_point%22%2C%22useForElevation%22%3Afalse%2C%22hidden%22%3Afalse%2C%22params%22%3A%7B%7D%7D%5D%2C%22groups%22%3A%5B%7B%22id%22%3A%22Default%22%2C%22title%22%3A%22Default%22%2C%22expanded%22%3Atrue%7D%5D%2C%22backgrounds%22%3A%5B%5D%2C%22bookmark_search_config%22%3A%7B%7D%7D%2C%22catalogServices%22%3A%7B%22services%22%3A%7B%22gs_stable_csw%22%3A%7B%22url%22%3A%22https%3A%2F%2Fgs-stable.geo-solutions.it%2Fgeoserver%2Fcsw%22%2C%22type%22%3A%22csw%22%2C%22title%22%3A%22GeoSolutions%20GeoServer%20CSW%22%2C%22autoload%22%3Atrue%7D%2C%22gs_stable_wms%22%3A%7B%22url%22%3A%22https%3A%2F%2Fgs-stable.geo-solutions.it%2Fgeoserver%2Fwms%22%2C%22type%22%3A%22wms%22%2C%22title%22%3A%22GeoSolutions%20GeoServer%20WMS%22%2C%22autoload%22%3Afalse%7D%2C%22gs_stable_wmts%22%3A%7B%22url%22%3A%22https%3A%2F%2Fgs-stable.geo-solutions.it%2Fgeoserver%2Fgwc%2Fservice%2Fwmts%22%2C%22type%22%3A%22wmts%22%2C%22title%22%3A%22GeoSolutions%20GeoServer%20WMTS%22%2C%22autoload%22%3Afalse%7D%7D%2C%22selectedService%22%3A%22gs_stable_csw%22%7D%2C%22widgetsConfig%22%3A%7B%7D%2C%22mapInfoConfiguration%22%3A%7B%22trigger%22%3A%22click%22%7D%2C%22dimensionData%22%3A%7B%7D%2C%22timelineData%22%3A%7B%22snapRadioButtonEnabled%22%3Afalse%7D%2C%22mapViews%22%3A%7B%22active%22%3Afalse%2C%22selectedId%22%3Afalse%7D}

Actions:

ZOOM_TO_EXTENT
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/new?actions=[{%22type%22:%20%22ZOOM_TO_EXTENT%22,%22extent%22:%20[-1.645,48.105,-1.619,48.116],%22crs%22:%20%22EPSG:4326%22,%22maxZoom%22:%2016}]

SCHEDULE_SEARCH_WITH_FILTER
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/new?addLayers=unesco:Unesco_point&actions=[{%22type%22:%22SEARCH:SCHEDULE_SEARCH_WITH_FILTER%22,%22cql_filter%22:%22cod_unesco='IT_830'%22,%22layer%22:%22unesco:Unesco_point%22}]

ADD_LAYERS
https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/new?&actions=[{%22type%22:%22CATALOG:ADD_LAYERS_FROM_CATALOGS%22,%22layers%22:[%22unesco:Unesco_point%22],%22sources%22:[%22gs_stable_csw%22],%22options%22:%20[{%22params%22:{%22CQL_FILTER%22:%22cod_unesco='IT_829'%22}}]}]

### CODE REVIEW

**Review by allyoucanmap — APPROVED** [review]
LGTM

**Comment by allyoucanmap** [comment]
@ElenaGallo please test on dev, thanks

**Comment by tdipisa** [comment]
@ElenaGallo after the test a backport to 2022.02.xx-c040 is needed

**Comment by ElenaGallo** [comment]
Hi @alex-fko, I noticed that the marker and zoom parameter are not available for the 3D map because the marker must have log and lat. Open this map: https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/10358?background=OpenTopoMap;default_map_backgrounds&marker=6

**Comment by alex-fko** [comment]
@ElenaGallo looks ok to me https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/cesium/10358?background=OpenTopoMap;default_map_backgrounds&marker=-20,20&zoom=6
marker should have comma-separated lon/lat + zoom as another parameter to make it work

**Comment by ElenaGallo** [comment]
Ok, I understand. Thanks @alex-fko. Please backport to 2022.02.xx-c040

**Pull request merged**
