### PR TITLE
Fix #10530 fix catalog editor for array scenario

### LINKED ISSUE #10530: If a the url of service catalog is defined as array when you open it  the application crash
## Description

it crash because [this](https://github.com/geosolutions-it/MapStore2/blame/master/web/client/components/catalog/editor/MainForm.jsx#L166) gets trigger when editing the catalog and an array is not accepted, so we have to pass the first element of the array in case of array to prevent the crash to happen

in the onChangeUrl of defaultservice the value is an array, but when the onchange is triggered, the output value becomes comma separated string, so there we do not have the problem

## How to reproduce

-  create a service with an array of urls (also same url) in the url property
-  open the map with this service and try to edit it

*Expected Result*

*Current Result*

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### PR DESCRIPTION
**Pull request by MV88**
## Description

fixing case when catalog url service is array, all details in issue

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

Fix #10530

**What is the new behavior?**

no crash in case of array 

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by tdipisa** [comment]
@MV88 there is a failing test which is not depending on this PR. @offtherailz will check it during review.

**Review by offtherailz — CHANGES_REQUESTED** [review]
Instead of using the first URL, An error should be shown because the format with array is not supported, and so it is error prone.

Please show misconfiguration error.

**Comment by MV88** [comment]
> Instead of using the first URL, An error should be shown because the format with array is not supported, and so it is error prone.
> 
> Please show misconfiguration error.

done, please review again

**Review by offtherailz — APPROVED** [review]
The catalog still works for some reason in search, while gives error in the editor.
even if not properly consistent, I think that it is enough for a misconfiguration, that by definition can have inconsistent results.

**Pull request merged**
