### PR TITLE
C125 annotations

### LINKED ISSUE #16: Configure Travis build
We should configure a Travis build for MapStore 2. I would also like to see its badge as well as the Coveralls one on the front-page.

See [this CKAN](https://github.com/ckan/ckanext-pages) plugin for an example.

### PR DESCRIPTION
**Pull request by kappu72**
## Description
Add annotations to print pdf
## Issues
 - Fix #16

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Annotation are not printed in pdf

**What is the new behavior?**
Annotation are included in pdf

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by mbarto** [comment]
To make this work the geoserver printing-plugin must be the geosolutions one, witch a patch I am going to commit: this is needed for printing markers

**Comment by mbarto** [comment]
We should install this on demo.geo-solutions.it geoserver, in my opinion

**Comment by chiaracurcio** [comment]
see my comment in geosolutions-it/austrocontrol-C125#16

**Comment by chiaracurcio** [comment]
Note that you can't print any annotations (points = markers) created on MapStore2 using Firefox, Chrome and IE, you have this message:

`"Error on printing: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>500 Internal Server Error</title> </head><body> <h1>Internal Server Error</h1> <p>The server encountered an internal error or misconfiguration and was unable to complete your request.</p> <p>Please contact the server administrator at alessandro.parma@geo-solutions.it to inform them of the time this error occurred, and the actions you performed just before this error.</p> <p>More information about this error may be available in the server error log.</p> </body></html>"`

immagine

**Pull request merged**
