### PR TITLE
Updates and French translation

### PR DESCRIPTION
**Pull request by MaelREBOUX**
## Description
This PR and commits to solve https://github.com/georchestra/mapstore2-georchestra/issues/38

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
https://github.com/georchestra/mapstore2-georchestra/issues/38

**What is the current behavior?**

#<issue>

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

Some comments :

* 126 updateOldMap => upgrade ? update for me is to update map content
* 190 "jet": "{number, plural, =0 {Jet} =1 {Jet} other {Jet}}", => unknown color name
* 312 "addToFeatured": "Ajouter à la présentation",  => cartes à la une ? Add to featured maps ?
* 829 helptexts =>  ça sert à quoi ??
* 1425 to 1427 => error in the content ?
* 1283 traduction of task . what is the meaning of task here ? (not tâche, it seems)
* 1390 => 1392 don't traduced because i don't know where is it and i don't see the use
* 1926 : i borred "geofence" which is not present in english version

And we noticed that there is some shifts between the different locales files. I think switching to Transifex would be a good idea...

### CODE REVIEW

**Comment by MaelREBOUX** [comment]
```data.fr-FR.json 
OK!
```

ouf...

**Comment by offtherailz** [comment]
I did this PR to your branch with the necesary fixes.
https://github.com/sigrennesmetropole/MapStore2/pull/1

The en localization file is used as reference, you added tooltip.left to en file but it was missing in de and es files. The PR add the 2 translations lines.

**Comment by MaelREBOUX** [comment]
I noticed new strings since the 5 of may.
I working on.
Please wait for merging @offtherailz

**Comment by MaelREBOUX** [comment]
Seems ok for merge

**Pull request merged**
