### PR TITLE
[Backport 2022.02.xx] #8491 linter for markdown files

### PR DESCRIPTION
**Pull request by belom88**
#8491 linter for markdown files

### CODE REVIEW

**Review by MV88 — CHANGES_REQUESTED** [review]
some files are missing since in the original pr files changed were 63

keycloak for example it not included
image

please @belom88 can you find the missing files and add them to the pr ?
i not

**Comment by MV88** [comment]
@belom88 also please check [here](https://github.com/geosolutions-it/MapStore2/actions/runs/3335727903/jobs/5520036273) why the build is failing

**Comment by MV88** [comment]
> some files are missing since in the original pr files changed were 63
> 
> keycloak for example it not included image
> 
> please @belom88 can you find the missing files and add them to the pr ?

@belom88 hi, have you missed this comment?

**Comment by belom88** [comment]
> > some files are missing since in the original pr files changed were 63
> > keycloak for example it not included image
> > please @belom88 can you find the missing files and add them to the pr ?
> 
> @belom88 hi, have you missed this comment?

3 files were with conflict:
* docs/developer-guide/integrations/users/keycloak.md
* docs/user-guide/widgets.md
* docs/developer-guide/maps-configuration.md

Files not presented in the backport:
* docs/developer-guide/documentation-guidelines.md
* docs/developer-guide/integrations/users/keycloak.md
* docs/user-guide/widgets.md

The content of these files is different from master and doesn't have linter issues

**Comment by MV88** [comment]
> The content of these files is different from master and doesn't have linter issues

fair enough, thanks for the check. approving

**Review by MV88 — APPROVED** [review]

**Pull request merged**
