### PR TITLE
Fix #10062 enhanced the way details are stored within app

### LINKED ISSUE #10062: Map thumbnail is not visible from the Save panel
## Description

By opening the save panel from the sidebar, the previously added thumbnail is no longer visible on the thumbnail box

https://github.com/geosolutions-it/MapStore2/assets/56537133/b6f81dc8-3c28-47fd-bdcd-098021737d08

## How to reproduce

-  Open a map with a thumbnail
-  Click o Save 

*Expected Result*

The thumbnail is visible on the thumbnail box

*Current Result*

The thumbnail is not visible on the thumbnail box

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

The issue is not present on PROD

### PR DESCRIPTION
**Pull request by MV88**
## Description

- adjusted and refactor details load logic 
- fixed a bug that was pre existing, (open a map with details, go to home and create a new dashboard  --> details in sidebar still remains)
- maintained fix for avoiding 2 attributes calls

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#<issue>

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by dsuren1 — APPROVED** [review]
Looks fine to me.

Kindly address the unit test failure. Thanks!

**Comment by tdipisa** [comment]
@ElenaGallo please test this on DEV asap. and let us know if we can backport.

**Comment by ElenaGallo** [comment]
@MV88 

1_Map details are visible once a new dashboard is opened

https://github.com/geosolutions-it/MapStore2/assets/56537133/d2c778f0-dcb5-45e2-b5d7-77415941a3d0

**How to Reproduce**
- Open [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/49443)
- Click on Details
- Go back to the homepage
- Click on New dash

2_ If the details open as modal, the navigation bar is in the wrong position in the viewer

Open [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/10358)

https://github.com/geosolutions-it/MapStore2/assets/56537133/cbebd3d4-a0ac-4044-9390-a9d79ff73d72

**Comment by ElenaGallo** [comment]
Test passed, @MV88 please backport to 2024.01.xx. Thanks

**Comment by MV88** [comment]
this pr was already backport here
https://github.com/geosolutions-it/MapStore2/pull/10154

**Pull request merged**
