### PR TITLE
Updating tomcat and java versions for binary package

### PR DESCRIPTION
**Pull request by tdipisa**
## Description

This PR updates the binary package to _Java 11.0.22_ and _Tomcat 9.0.90_.
Some typos have been also corrected.

The updated **JRE tar.gz** to be used for review is available [here](https://drive.google.com/file/d/1muxrA1vSXGyXh7HWAe8dSeDQK0b054Jj/view?usp=drive_link) at the moment and it will need to be moved [here](https://www.dropbox.com/scl/fi/2rjaso3cxgab0jdjxwpjr/jre.tar.gz) (**don't replace the current one**) . @randomorder a new different link should be created for this so that the build of older versions can continue using the current java version.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#10444

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

@offtherailz please note that **due to [this](https://github.com/geosolutions-it/MapStore2/blob/master/binary/bin.xml#L26) 12 tomcat lib files are not included. I'm wondering if it is really wanted. The build works well and the binary generated with the following command works as expected:**

```
./build.sh "2024.01.02" "printing,binary,printingbundle"
```

@offtherailz please test also on linux using the JRE I've linked above.

### CODE REVIEW

**Comment by randomorder** [comment]
Hi @tdipisa 

jre_11_0_22.tar.gz is available here:  https://www.dropbox.com/scl/fi/87kle0o7vezax6eu18f7a/jre_11_0_22.tar.gz?rlkey=gjp6ulyos97xbf9w94xlkxg2q&st=pznxo0r2&dl=1

image

**Comment by offtherailz** [comment]
Hi @randomorder the file doesn't look to be corrupted https://github.com/geosolutions-it/MapStore2/pull/10446#issuecomment-2213546637 

```sh
uncompress jre_11_0_22.tar.gz

gzip: jre_11_0_22.tar.gz: not in gzip format
offtherailz@tifa-nali-studio ~/Scaricati/test $ unzip jre_11_0_22.tar.gz
Archive:  jre_11_0_22.tar.gz
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of jre_11_0_22.tar.gz or
        jre_11_0_22.tar.gz.zip, and cannot find jre_11_0_22.tar.gz.ZIP, period.
(failed reverse-i-search)`tar -': unzip jre_11_0_22.^Cr.gz
offtherailz@tifa-nali-studio ~/Scaricati/test $ tar -xzvf jre_11_0_22.tar.gz 

gzip: stdin: not in gzip format
tar: Child returned status 1
```

**Comment by randomorder** [comment]
Hi @offtherailz 
Apparently the archive was not compressed. New link: https://www.dropbox.com/scl/fi/bx70uj1biqzh4n8ad2giq/jre_11_0_22.tar.gz?rlkey=i3561opd2osxs71ypkdvovaq7&st=qzqs5dnu&dl=1

**Comment by offtherailz** [comment]
Things done: 
- replaced JDK with openjdk 11_0_23 (linux x64 and win). 
  Sources:
    - linux https://adoptium.net/temurin/releases/?version=11&os=linux&arch=x64
    - windows: https://adoptium.net/temurin/releases/?version=11&os=windows&arch=x64
- restored old port
- tested with linux

**Review by offtherailz — COMMENTED** [review]
the proxy is working with my changes and tests. 
The only issue is that openjdk now is 160MB bigger.
Now it is 389MB. Old was 231 MB.

**Review by offtherailz — APPROVED** [review]
for me it works on linux

**Comment by tdipisa** [comment]
@ElenaGallo please check this on win once the build finish. @offtherailz then can I ask you to provide the backport please?

**Comment by ElenaGallo** [comment]
Test passe, @offtherailz please backport to 2024.01.xx. Thanks

**Pull request merged**
