### PR TITLE
#6537: Measurement coordinate editor enhancement

### PR DESCRIPTION
**Pull request by dsuren1**
## Description
This PR adds fix and enhancement to measure panel (Additional to previous enhancement https://github.com/geosolutions-it/MapStore2/pull/6538) 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [x] Enhancement

## Issue

**What is the current behavior?**
https://github.com/geosolutions-it/MapStore2/issues/6537#issuecomment-780600932

**What is the new behavior?**
- When new measurement is added, the feature is auto selected in the dropdown (**Fix**)
- Adding additional row by clicking on + button, the map draw interaction is disabled and user can added new coordinate by clicking on the map or by adding the coordinates manually as before (**Enhancement**)

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information
https://github.com/geosolutions-it/austrocontrol-C125/issues/268

### CODE REVIEW

**Review by MV88 — APPROVED** [review]

**Comment by ElenaGallo** [comment]
@dsuren1 here are some considerations after testing this PR:
- From Measure distance, by clicking on the + buttons to add a new line, it is possible to draw only a point
- Adding a new polygon using the New button and then + button, the first segment drawn on the map is not visible and the measure panel is disabled
- After drawing various lines and polygons, adding a coordinate to a polygon, clicking the + button, the polygon is no longer visible on the map
- Adding a coordinate to an area or distance, with the + button, the visualization of the distance already present on the map is modified, it switches from curved line to straight line

**Comment by dsuren1** [comment]
> @dsuren1 here are some considerations after testing this PR:
> 
> * From Measure distance, by clicking on the + buttons to add a new line, it is possible to draw only a point
>   

As you can see the line is not complete yet, that's the reason you see only one point, you need to add one more row to add a point to complete the linestring. 

> * Adding a new polygon using the New button and then + button, the first segment drawn on the map is not visible and the measure panel is disabled
>   

Just like before, the polygon is not complete, only two rows are added, you need to add one more row to complete the poligon. Else you might draw a new polygon the latest feature will be selected.

> * After drawing various lines and polygons, adding a coordinate to a polygon, clicking the + button, the polygon is no longer visible on the map
>   

Not sure. I will try to reproduce it.

> * Adding a coordinate to an area or distance, with the + button, the visualization of the distance already present on the map is modified, it switches from curved line to straight line
>   

This could be because the interaction is turned off when in edit. Does it remain the same, even after completing the editing process?

**Comment by tdipisa** [comment]
@dsuren1 

>- From Measure distance, by clicking on the + buttons to add a new line, it is possible to draw only a point

In this case two empty coordinate points fields should be consecutively added (one after the other) in both cases, whether you edit the coordinates in the form or by clicking on the map (the bheavior is different at the moment). The final line is not curved anyway in all cases after adding a coordinate by clicking on + button.

>- Adding a new polygon using the New button and then + button, the first segment drawn on the map is not visible and the measure panel is disabled

As for point 1, in this case one more coordinate point fields row should be consecutively added in order to complete the polygon (now only two adding coordinates by clicking on map, in form only one). With each click on the map the point should be drawn in map as usual, now it isn't. We also have a different behavior between adding a coordinate in the form or clicking on the map (in the second case an extra row of coordinates is added but in the first case not)

>- After drawing various lines and polygons, adding a coordinate to a polygon, clicking the + button, the polygon is no longer visible on the map

I'm not able to replicate this.

>- Adding a coordinate to an area or distance, with the + button, the visualization of the distance already present on the map is modified, it switches from curved line to straight line.

I already replied to this in the firs point. it happens usually when you add a new coordinate by clicking on + button independently on the measurements and affect the drawn lines.

**Comment by dsuren1** [comment]
@ElenaGallo @tdipisa 

**Testing notes:**

**_Measurement panel with coordinates editor_**
- Upon clicking the **+** button, the coordinate row is added and either by clicking on the map or entering the valid coordinate and submitting, the coordinate editor will automatically add coordinates row until the geometry is valid (LineString & Bearing - 2 row, Polygon - 3 rows)
- Upon adding the vertices, the vertex points of the coordinate is highlighted with a point (To guide the user in visualizing the position while the geometry is drawn) 
- The Linestring arc will be maintained while updating the features (if any).
- When saving the measurement to annotation, the 'Bearing' will not be transformed to arc line (if applicable).
- User should be able to use left/right arrow keys to move cursor position in the coordinates editor input fields

**Pull request merged**
