### PR TITLE
#8591 Fix chart legend ordering matching colorCatagories order

### PR DESCRIPTION
**Pull request by MV88**
## Description

Now charts shows unordered data based on classification label list for "value" type
dashboard with id [dev-41396](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/dashboard/41396) can be a dashboard to be used for testing

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#8591

**What is the new behavior?**

Data are now sorted based on custom classification label order

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by dsuren1 — CHANGES_REQUESTED** [review]
@MV88 
As we discussed, please find below are the issues identified

- [ ] Default class label and color is missing in the chart widget
- [ ] Secondly, the sort order is matching only when the chart is stacked

image

**Comment by MV88** [comment]
>  Default class label and color is missing in the chart widget

yes this was missed and I'll provide a quick fix for it

> Secondly, the sort order is matching only when the chart is stacked

I'm not sure this was requested as part of requirements, since the PR targets a specific use case, when there are more data grouped by a common attribute, when you have more records inside each bar 
for example
image

I'll check if it is possible to cover also this scenario but, this requires some more time 
@tdipisa can I take half a day more to do this point?


BTW there was no mention on what to do with default class label, so with data not matched from custom color palette ,
so I'm putting them ad the end of the bar (chart starts from the bottom)

**Comment by MV88** [comment]
Nevermind I think I have found a quick way to obtain this result aswell if data are not grouped by
image
going to push an update if tests pass

**Comment by tdipisa** [comment]
> Nevermind I think I have found a quick way to obtain this result as well if data are not grouped by image going to push an update if tests pass

Nothing was requested for this scenario but, since you found a quick way to provide it, it is well accepted of course.

**Comment by MV88** [comment]
image

**Review by dsuren1 — CHANGES_REQUESTED** [review]
@MV88 
I found two instances where the order of classification is not matching the legend order

- It seems to work on chart based on classification on a string attribute. However with the range color classification it doesn't
 
2022-09-22 12_45_14-MapStore2

- Also it doesn't work on stacked where the x and y attributes are different

2022-09-22 12_24_47-MapStore2

This behavior needs to be decided upon

**Comment by tdipisa** [comment]
@dsuren1 since @MV88 is not available now I kindly ask you to complete this issue according to the review. Please check the code and let me know the estimate. Issue also assigned to you @dsuren1.

**Comment by dsuren1** [comment]
@MV88 

> * It seems to work on chart based on classification on a string attribute. However with the range color classification it doesn't

Looking at the code, we don't have support for range classification at the moment. We need to factor in `range classification` for legend ordering to fix this one

For the stacked issue, regardless of the attributes, if the data stacks in multiple along x, we encounter this scenario (attached sample map above) where the ordering is not maintained, we need to enhance the current implementation to factor in this scenario along with range classification to fit this use case.

**Comment by tdipisa** [comment]
Moving in blocked for now waiting for clarification.

**Comment by alex-fko** [comment]
So the root cause of all the issues with incorrect order of the legend is how Plotly library renders legend. Legend elements will inherit order of corresponding data entries appearance (https://community.plotly.com/t/customizing-the-order-of-legends/12668).

With the applied changes both ranged and plain value classifications work fine, for all the examples previously mentioned, though now it will only reorder based on classification attribute; it will not make an attempt to reorder entries in a sub-group when X-axis values are grouped (see `DATASET_5_ORDERED` data sample to see how its changed), otherwise we end up with the case when such nested reordering breaks legend order when not all classifications are represented in the first group.

**Review by dsuren1 — APPROVED** [review]

**Comment by dsuren1** [comment]
@ElenaGallo 
Kindly test this change in DEV once deployed and let us know if it can be backported to 2022.01.xx-c040 and eventually to 2022.02.xx

**Comment by ElenaGallo** [comment]
Test passed on DED, @dsuren1 please backport. Thanks

**Comment by tdipisa** [comment]
@alex-fko you can proceed with the backport. Thank you so much guys.

**Comment by tdipisa** [comment]
@alex-fko please backport also to 2022.02.xx. Thank you.

**Pull request merged**
