### PR TITLE
fixed #1021 added short hand css

### LINKED ISSUE #1021: Increase Codacy Level to A
We should solve the existing issues with Codacy: https://www.codacy.com/app/simone-giannecchini/MapStore2/dashboard

### PR DESCRIPTION
**Pull request by saidaipparla**
re writing some css where ever needed

### CODE REVIEW

**Comment by saidaipparla** [comment]
no i just changed margin-left:40%; to margin: 0 0 0 40%; now due to there are no other properties which are effecting that element . i keep same as original and just added short hand notation. let me know if you face any problem

**Comment by offtherailz** [comment]
I mean, why you replaced this 
```
 margin-left: 100px;
margin-right: 100px;
```
with 

```
margin: -50px 100px 50px 100px;
```

**This change margin-top to -50px and the margin bottom to 50px**

or this:
```
margin-left: 40%;
```
with this: 
```
margin: 0 0 10px 0;
```
That set margin-left to 0 and the margin-bottom to 10px (forcing the other ones to 0). Don't know if you simply used the wrong order, but anyway 40% is not the same of 10px.

Please reply the comments from @mbarto one by one to justify your choices, and fix what is wrong.

**Comment by offtherailz** [comment]
What about to set width to 100% for the settings of the coordinate indicator? 
image

@saidaipparla already did it locally, and it looks better, what you think ?

**Comment by offtherailz** [comment]
Going to close this pull request, please redo it from your fork

**Pull request closed without merging**
