### PR TITLE
Fix #9944 Map connected to table with date attribute breaks the app

### LINKED ISSUE #9944: Map connected to table with date attribute breaks the app
## Description

When a map is connected to a table with a date attribute the application crashes. The reason seems related to a missing message id that breaks the intl formatter

## How to reproduce

-  open this [dashboard](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/dashboard/48270)

*Expected Result*

Dashboard should be visible and working

*Current Result*

Application is not working and the message `Oops, something has gone wrong...` is displayed

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description

Some changes applied to date time filter were providing an empty string as message id and this was causing problem with intl library that expects always a valid id.

This PR restore fallbacks message id when date filters are not used by the attribute table and it adds an additional check to ensure the message id is valid before the intl formatting

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**

#9944

**What is the new behavior?**

Application is not breaking when a map is connected to a table with date/time attributes

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [x] No

### CODE REVIEW

**Comment by tdipisa** [comment]
@allyoucanmap to be backported to https://github.com/geosolutions-it/MapStore2/tree/c040-2024.01.xx once approved.

**Review by dsuren1 — APPROVED** [review]
@allyoucanmap 
LGTM!
Just a small icon line height misalignment. If it's not a concern for this issue, then please feel free to merge

image

**Review by dsuren1 — APPROVED** [review]

**Comment by tdipisa** [comment]
@ElenaGallo please test in DEV and let us know [if we can backport](https://github.com/geosolutions-it/MapStore2/pull/9947#issuecomment-1921436533)

**Comment by ElenaGallo** [comment]
Test passed on DEV. @allyoucanmap please [backport](https://github.com/geosolutions-it/MapStore2/pull/9947#issuecomment-1921436533)

**Pull request merged**
