### PR TITLE
#9839: Ability to print image legend with an appropriate scale

### PR DESCRIPTION
**Pull request by dsuren1**
## Description
This PR allows user to use legend options (scale) configured layer option to be used for printing along with an option to override all layer legend image icon size in the print tool

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Enhancement

## Issue

**What is the current behavior?**
- #9839 

**What is the new behavior?**

- User can print the legend options configured in the layer setting
- User can override all layer's legend icon size in the print tool

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by offtherailz — APPROVED** [review]

**Comment by offtherailz** [comment]
@ElenaGallo, could you please test this on  DEV as well as it will be deployed ? Thank you

**Comment by ElenaGallo** [comment]
Hi @dsuren1, the new behaviors work as expected but now the background legend is also visible on the legend.

**How to Reproduce**
- Open a [map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/47974)
- Open the printed tool
- Enable the legend
- Print the map

**Current Result**
The `OSM Bright` background legend is visible on the printed map.
See [this printed map](https://github.com/geosolutions-it/MapStore2/files/13885638/mapstore-print.-.2024-01-10T102301.892.pdf)

**Comment by dsuren1** [comment]
@ElenaGallo 
Is there a requirement where the background layers are skipped. As I can see, if the layer type is `wms`, regardless of the group if legend is requested and if present then the information is printed. Kindly correct me if I'm wrong.

You can try the same in **[QA](https://qa-mapstore.geosolutionsgroup.com/mapstore/#/viewer/new)** by selecting `Sentinel 2 Cloudless` as background and print legend

**Comment by ElenaGallo** [comment]
> You can try the same in **[QA](https://qa-mapstore.geosolutionsgroup.com/mapstore/#/viewer/new)** by selecting `Sentinel 2 Cloudless` as background and print legend

@dsuren1 that is correct, thanks for the clarification.

**Pull request merged**
