### PR TITLE
#8559: Feature grid aliases and tooltips for columns

### PR DESCRIPTION
**Pull request by dsuren1**
## Description
This PR allows adding alias and description to the attribute columns in table widgets

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Feature

## Issue

**What is the current behavior?**
#8559 

**What is the new behavior?**

image

image

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by allyoucanmap — CHANGES_REQUESTED** [review]
The code looks good but I found this while testing locally

- [ ] it is not possible to add alias to existing table, try with #/dashboard/21694 as in the video
https://user-images.githubusercontent.com/19175505/191542353-4b916679-760c-4d05-8d54-ca44d07b33a6.mp4

**Comment by dsuren1** [comment]
@allyoucanmap 
> * [ ]  it is not possible to add alias to existing table, try with #/dashboard/21694 as in the video
>   https://user-images.githubusercontent.com/19175505/191542353-4b916679-760c-4d05-8d54-ca44d07b33a6.mp4

It's because the columns were not selected. Upon selecting the column, the title and description can be added. 
image

However, I have handled now the auto selection of active columns on existing saved widgets upon editing.
It's ready for review now. Thanks!

**Review by allyoucanmap — CHANGES_REQUESTED** [review]
@dsuren1 just reviewed and I saw that now are preselected for the existing table also but I think it's still misleading to allow an user to edit a field if deselected.
Could we make the input disable if the row is deselected so at least the user knows that cannot edit it?

Current input allow to type also deselected
image

cc @tdipisa

**Review by allyoucanmap — APPROVED** [review]

**Comment by allyoucanmap** [comment]
@ElenaGallo please test this on dev and let us know when we can backport it to stable branch 2022.02.xx, thanks

**Comment by tdipisa** [comment]
@ElenaGallo please test this in DEV and let us know. For the backport to 2022.02.xx we have to wait after the release of 2022.02.00 @dsuren1.

**Comment by ElenaGallo** [comment]
@dsuren1 the description input field goes below the other widgets.

table

**Comment by ElenaGallo** [comment]
@dsuren1 now you can backport to 2022.02.xx. Thanks

**Pull request merged**
