### PR TITLE
Fix #9293 Update OpenLayers version 7.4.0

### LINKED ISSUE #9293: Update OpenLayers version 7.4.0
## Description

We should update OpenLayers to latest version 7.4.0

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [x] Minor changes to existing features

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description

This PR updates the OpenLayers version (7.4.0)

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Minor changes to existing features

## Issue

**What is the current behavior?**

#9293

**What is the new behavior?**

OpenLayers is updated to version 7.4.0

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [x] No

### CODE REVIEW

**Comment by allyoucanmap** [comment]
@ElenaGallo please test this update on DEV, thanks. The OpenLayers library has been updated so all the test related to 2D maps viewer, including geostories and dashboard should be covered

**Comment by ElenaGallo** [comment]
@allyoucanmap these are the test results: https://studio.cucumber.io/projects/292756/test-runs/810350/folder-snapshots/8631080. 
There are these problems:

**Attribute Table**
- Selecting a feature on the map with the Quick Filter selects the features but does not highlight them on the map. 
filter feature

- Clicking the Zoom to feature, does not highlight feature on the map.
zoom to feature

- Geometry cannot be drawn using snapping.
snapping

**Print tool**
- The map is not visible on the printed preview and pdf.
print

**Graticule**
- Only the first comment of #9292 is still present

**Comment by tdipisa** [comment]
@ElenaGallo I think it is better to open a dedicated issue for the above

**Comment by ElenaGallo** [comment]
@allyoucanmap @tdipisa this is the new issue, #9302. I'm closing this one.

**Pull request merged**
