### PR TITLE
Add docker-compose

### LINKED ISSUE #473: Allow skipping client side tests with -DskipTests in maven build
We need to add a new configuration param in frontend plugin executions

### PR DESCRIPTION
**Pull request by sycured**
## Description
This PR permits the usage of docker-compose to obtain a development environment.

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
Impossible to start easily an entire environment:
- MapStore
- PostgreSQL with PostGIS
- MapStore configuration to use PostgreSQL

**What is the new behavior?**
Ability to use docker-compose to start an entire environment:
- MapStore
- PostgreSQL with PostGIS
- MapStore configuration to use PostgreSQL
- Reverse proxy to access MapStore on standard HTTP port (80/tcp)

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by randomorder** [comment]
on `docker-compose up -d` I get:
image

Looks like the MAPSTORE_WEBAPP_SRC arg specified in the docker-compose file is ignored?
image

**Comment by sycured** [comment]
I've another error not on the same part because, on Debian Bullseye, `postgresql-client` is now version 13, not 11

Maybe it's time to don't hardcode the version because, at each Debian major release, the dockerfile/docker-compose needs to be fixed.

When it's working on my side, I re-clean images and cache and I record my screen because it's near impossible

**Comment by sycured** [comment]
> on `docker-compose up -d` I get:
> image
> 
> Looks like the MAPSTORE_WEBAPP_SRC arg specified in the docker-compose file is ignored?
> image

@randomorder I can't reproduce your error about the war file, it's successfully downloaded on my side…
I'll record my screen during a clean `docker-compose up -d`

**Comment by sycured** [comment]
https://user-images.githubusercontent.com/60801403/132356117-51695efa-346e-43c5-8bb4-f25e0403f7ad.mp4

**Comment by sycured** [comment]
@randomorder I fixed the issue removing ENV and adding the default to ARG

Tested working on my laptop and on different VM:
- Debian 11 (Bullseye)
  - kernel: 5.10.0-8-amd64
  - docker version: 20.10.8
  - docker-compose version: 1.29.2
- RHEL 8
  - kernel: 4.18.0-305.17.1.el8_4.x86_64
  - docker version:  20.10.8
  - docker-compose version: 1.29.2

**Review by randomorder — APPROVED** [review]

**Pull request merged**
