### PR TITLE
Switching to mapfish-print new official version 2.3.1

### PR DESCRIPTION
**Pull request by tdipisa**
## Description

Since [our PR](https://github.com/mapfish/mapfish-print-v2/pull/23#issuecomment-2244287754) was finally merged and a new version released for it.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [x] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#<issue>

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by tdipisa** [comment]
@ElenaGallo we need to schedule an extensive functional test for the printing functionality in DEV.

**Review by offtherailz — APPROVED** [review]

**Comment by tdipisa** [comment]
@ElenaGallo please perform an extensive test of all printing capabilities once deployed in DEV.

**Comment by ElenaGallo** [comment]
@offtherailz I tried to print the the demo map and this is the error that appears:

> Error on printing: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>500 Internal Server Error</title> </head><body> <h1>Internal Server Error</h1> <p>The server encountered an internal error or misconfiguration and was unable to complete your request.</p> <p>Please contact the server administrator at mapstore-developers@googlegroups.com to inform them of the time this error occurred, and the actions you performed just before this error.</p> <p>More information about this error may be available in the server error log.</p> <hr> <address>Apache/2.4.41 (Ubuntu) Server at dev-mapstore.geosolutionsgroup.com Port 443</address> </body></html>

print

**Comment by tdipisa** [comment]
@ElenaGallo it seems working for me. I'm wondering if the above was due to a temporary issue. Can you please try/test again?

**Comment by ElenaGallo** [comment]
@tdipisa Now all tests have been passed for the printing tool

**Comment by ElenaGallo** [comment]
@tdipisa I did the following tests:
- Print a map with title and description
- Print a map on PDF - PNG - JPEG
- Print a map with EPSG:3857- EPSG:4326
- Print a map with different Rotation
- Print a map in A2 - A3 - A4
- Print a map in 96 dpi - 150 dpi - 300 dpi
- Print a map with Legend
- Print a map with Legend on distinct page
- Print a map with on Landscape - Portrait
- Print a map with Legend on distinct page
- Print a map with custom Legend labels
- Print a map with different sizes of Legend icons
- [Print layer when visibility property is null | undefined](https://studio.cucumber.io/projects/292756/test-runs/994055/folder-snapshots/11674117/scenario-snapshots/36280187/test-snapshots/48408846)
- [Print map with scale selector enabled](https://studio.cucumber.io/projects/292756/test-runs/994055/folder-snapshots/11674117/scenario-snapshots/36280190/test-snapshots/48408849)
- [Credits text in printed page](https://studio.cucumber.io/projects/292756/test-runs/994055/folder-snapshots/11674117/scenario-snapshots/36280191/test-snapshots/48408850)
- [Print annotations](https://studio.cucumber.io/projects/292756/test-runs/994055/folder-snapshots/11674118/scenario-snapshots/36280192/test-snapshots/48408851)
- [Print image legend](https://studio.cucumber.io/projects/292756/test-runs/994055/folder-snapshots/11674120/scenario-snapshots/36280193/test-snapshots/48408852)
- [Print a mapproxy WMS service](https://studio.cucumber.io/projects/292756/test-runs/994055/folder-snapshots/11674121/scenario-snapshots/36280194/test-snapshots/48408853)

**Comment by tdipisa** [comment]
> @tdipisa Changing the resolution to 150 dpi or 300 dpi results in the following error and the map is not printable.
> 
> > Failed to load resource: the server responded with a status of 500 (Internal Server Error)
> 
>  print.error.mp4

@ElenaGallo it doesn't seems the print resolution is the problem. Also other kind of print requests have problems now while this morning all was working fine. It seems there is another problem on DEV since all HTTP print requests are going in timeout. Please open a dedicated issue maybe mentioning this one

**Comment by ElenaGallo** [comment]
@tdipisa new issue [here](https://github.com/geosolutions-it/MapStore2/issues/10512)

**Pull request merged**
