### PR TITLE
#9589: Notify data projection not compatible / available for COG

### PR DESCRIPTION
**Pull request by dsuren1**
## Description
This PR check for projection compatibility and notifies the user with meaningful feedback

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Enhancement

## Issue

**What is the current behavior?**
- #9589 

**What is the new behavior?**

**CATALOG**
Screenshot 2023-11-10 at 6 02 16 PM

**TOC**
Screenshot 2023-11-10 at 5 44 33 PM

**NOTIFICATION**
Screenshot 2023-11-10 at 5 44 44 PM

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by offtherailz** [comment]
@dsuren1 this PR after our recent PRs needs to be upated with master, some conflicts present.

**Comment by dsuren1** [comment]
@dsuren1 
> Can you provide a valid test case for the COG context https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/COG?

For the cog test service urls, we have projection defs already defined in Dev so i'm not able to create a test data that satisfies all cases. However, you can test it locally by removing projection defs and adding this service [url](https://cogeo.craig.fr/opendata/ortho/ortho25_cc46_clerco_1996.cog.tif) to _test catalog_ error and import this map [map_cog_notify.json](https://github.com/geosolutions-it/MapStore2/files/13389375/map_cog_notify.json) to _test warning and TOC_

**Comment by offtherailz** [comment]
@ElenaGallo, could you please test this on  DEV ? Thank you

**Comment by tdipisa** [comment]
@dsuren1 (FYI @ElenaGallo @offtherailz)

I've tested this as well the other issues. In this case I've reverted projDefs definitions from DEV data dir
and added COGs previosuly tested before releasing 2023.02.00 to [this test map ](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/COG/47284).

The notification works fine and the layer is not added to the map
image

There is anyway what I think is a wrong behavior. Every time the map is loaded the following notification appears independently of what is the COG layer visible in TOC (I've visualizing them tried one by one) and this is not correct because the projection is supported for all COG layers in TOC (once needed projectionDefs have been restored in DEV data dir).

**Comment by dsuren1** [comment]
@tdipisa 
> There is anyway what I think is a wrong behavior. Every time the map is loaded the following notification appears independently of what is the COG layer visible in TOC (I've tried visualizing them one by one).
> 
> This is not correct because the projections are supported for all COG layers in TOC (once needed projectionDefs have been restored in DEV data dir).

It's because the layer's `sourceMetadata` info is not saved on export and map save. I have fixed this in this [PR](https://github.com/geosolutions-it/MapStore2/pull/9736)

**Pull request merged**
