### PR TITLE
Problems in switch/exit fullscreen (browser related) #4324

### PR DESCRIPTION
**Pull request by vlt1**
## Description
Contains a fix for a chrome specific problem. Concerning F11 fullscreen, it seems that it is not part of Fullscreen API and thus there is no supported way of detecting that browser is in fullscreen or going back from fullscreen in this case. Fullscreen button in Safari is hidden on purpose with a stated reason that Fullscreen API in Safari is not fully supported. Looks like [not much has changed](https://caniuse.com/#feat=fullscreen) on that front, so it probably should stay disabled.(the button was disabled in [this pull request](https://github.com/geosolutions-it/MapStore2/pull/2166)).

## Issues
 - #4324 
 - ...

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by offtherailz** [comment]
So this PR doesn't fix anything, right?
In case please comment the issue

**Comment by vlt1** [comment]
@offtherailz it fixes a chrome specific issue

**Comment by offtherailz** [comment]
@vlt1 any news for this issue?
If I understood  well it doesn't solves the issue linked (that can't be solved), but another. If so, please :
 - [ ] Remove link from this issue
 - [ ] Add a comment in the issue about why is can not be solved
 - [ ] Fix the things in the review.

So we can merge it. It's waiting for a long time

**Comment by offtherailz** [comment]
This is still pending, please fix @vlt1

**Comment by vlt1** [comment]
@offtherailz the problem with previous code is that instead of 'fullscreen' it gave the second letter of that word, namely 'u', because on chrome the filtered array had three elements. As for the test, I don't think a meaningful one can be provided seeing as it's results are going to be valid only for a specific testing environment.

**Pull request merged**
