### PR TITLE
#6180: Save MapSwipe configuration inside the map

### PR DESCRIPTION
**Pull request by AGMETEOR**
## Description

Allow adding of MapSwipe configuration inside the map

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#6180 

**What is the new behavior?**

Allow adding of MapSwipe configuration inside the map

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by offtherailz** [comment]
Inspecting the issue is not to clear to me what is the expected behavior after saving the configuration.
When I load a map, the configuration stored is loaded, so if I select a layer and I activate the tool, for instance it reuses the old configuration and presents an horizontal swipe (of the spyglass option with the size) instead of vertical (default).

actual behavior

Is this the desired bahavior @giohappy ?

**Comment by giohappy** [comment]
@offtherailz the desired behaviour is to store the status of the tool. If it was saved as active / visible, I expect to see it when I open the map, without having to activate it.

**Comment by giohappy** [comment]
@offtherailz as agreed (phone call) this behaviour is a bit different from the design that has driven the current implementatiom
In paritcular the fact of having the swipe tool activation bound to the layer selection prevents from doing what I described.

For the moment we can drop this requirement, It will be resurrected in the future when an additional type of configurations for the mpa + swipe tool will be available.

**Comment by offtherailz** [comment]
so let me close this PR. do you want to preserve the related issue or create a new one @giohappy ?

**Pull request closed without merging**
