### PR TITLE
#6635: Fix Issue with Virtual Scroll

### PR DESCRIPTION
**Pull request by MuhweziDeo**
## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

#6635 

**What is the current behavior?**
The lists loaders infinitely  even without the user scrolling
#6635 

**What is the new behavior?**
List should load when the user scrolls to the bottom of the list

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
- This PR contains also changes for another issue #5110. Please create a separate PR for it and here commit only the fix to #6635
- more about #5110 --> Your fix to #5110 to map catalog here breaks the "MapCatalog" plugin. 
see http://localhost:8081/#/context/mapcatalog for instance (or create  a context with MapCatalog plugin to test). Virtual scroll doesn't work anymore there. This is why I suggested a different change, that make them work both, in the comment of #5110

This is why I suggested a different

**Comment by MuhweziDeo** [comment]
> * This PR contains also changes for another issue #5110. Please create a separate PR for it and here commit only the fix to #6635
> * more about #5110 --> Your fix to #5110 to map catalog here breaks the "MapCatalog" plugin.
>   see http://localhost:8081/#/context/mapcatalog for instance (or create  a context with MapCatalog plugin to test). Virtual scroll doesn't work anymore there. This is why I suggested a different change, that make them work both, in the comment of #5110

@offtherailz @tdipisa Do you recommend closing this PR and add the fixes to the PR for this issue #5110 . Since we discovered the issue was `server-side`

**Comment by MuhweziDeo** [comment]
@offtherailz this PR has fixes for only virtual scroll problem issue #5110 is related to the misalignment of the loader and text

**Review by offtherailz — APPROVED** [review]

**Comment by ElenaGallo** [comment]
@MuhweziDeo test done, please backport this to the stable branch. Thank you

**Pull request merged**
