### PR TITLE
Fix 6813 filter request layers only

### PR DESCRIPTION
**Pull request by MuhweziDeo**
## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Enhancement

## Issue

**What is the current behavior?**
Record Items that are not Layers are shown
#6813 

**What is the new behavior?**
 Record Items that are not Layers are hidden

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
This filter makes `https://gs-stable.geo-solutions.it/geoserver/csw` not working anymore. (now empty response).
So the filter should be optional. 
(if text filter and configured filter(s) are present, add the contrain tag, in with the filter, in `And` if both are present.)

I'm wandering if we should make this additional filter configurable (via UI and/or json configuration). @giohappy ?

**Comment by MuhweziDeo** [comment]
> This filter makes `https://gs-stable.geo-solutions.it/geoserver/csw` not working anymore. (now empty response).
> So the filter should be optional.
> (if text filter and configured filter(s) are present, add the contrain tag, in with the filter, in `And` if both are present.)
> 
> I'm wandering if we should make this additional filter configurable (via UI and/or json configuration). @giohappy ?

There is a pending fix on the backend to take this in consideration already reported this issue

**Comment by offtherailz** [comment]
mmm... Anyway we may need to support csw without this "fix". I think this filter have to be optional **in any case**. So I suggest to make this filter optional, configured where needed, and continue. @giohappy do you agree?
Can you link the ticket for back-end fixing?

**Comment by giohappy** [comment]
@offtherailz I'm fineto have it as optional. The filter is what should be used to filter layers only according to the CSW specs. FYI @etj is checking why Geoserver returns that unexpected value instead of "dataset". By the way I'm fine to have it configured only inside the GeoNode MapStore client.

**Comment by giohappy** [comment]
@offtherailz I'm fine, but if you set the "dc:dataset" filter by default now Geoserver won't return anything, because as I was saying Geoserver CSW is using a different label (apparently not standard).

**Comment by giohappy** [comment]
@tdipisa this is the original issue https://github.com/GeoNode/geonode-mapstore-client/issues/103
It's not connected to a specific project because it spans multiple clients (ADBPO and Almaviva at elast)

**Comment by offtherailz** [comment]
So, as discussed with @etj  and @giohappy adding modifying the filter with a more complex one, that includes all the possible `dataset` filters should be the solution for all the catalogs available.
@giohappy can you send to @MuhweziDeo the final filter so we can update this PR?

**Comment by giohappy** [comment]
The following filter was tested succesfully on:

 - GeoNode (https://master.demo.geonode.org/catalogue/csw?service=CSW&version=2.0.2&request=)
 - Geoserver (https://gs-stable.geo-solutions.it/geoserver/csw?service=CSW&version=2.0.2&request=)
 - GeoNetwork (http://gn3-rndt.geo-solutions.it/geonetwork/srv/eng/csw)

```xml
<ogc:Filter>
	 <ogc:Or>
	 <ogc:PropertyIsEqualTo>
		 <ogc:PropertyName>dc:type</ogc:PropertyName>
		 <ogc:Literal>dataset</ogc:Literal>
	 </ogc:PropertyIsEqualTo>
	 <ogc:PropertyIsEqualTo>
		 <ogc:PropertyName>dc:type</ogc:PropertyName>
		 <ogc:Literal>http://purl.org/dc/dcmitype/Dataset</ogc:Literal>
	 </ogc:PropertyIsEqualTo>
	</ogc:Or>
 </ogc:Filter>
```

@MuhweziDeo you can proceed with this

**Comment by offtherailz** [comment]
I removed the "blocked" label

**Comment by MuhweziDeo** [comment]
> I removed the "blocked" label



> I removed the "blocked" label

Do you mind updating the issue description for the issue as well to have better alignment with the expectations and also keep track of the requirements @offtherailz

**Comment by offtherailz** [comment]
Ok. Sumarizing, nothing changed except the filter that should be something like in the comment https://github.com/geosolutions-it/MapStore2/pull/6818#issuecomment-839646401 
use the services in the same comment as test.

**Review by offtherailz — APPROVED** [review]

**Pull request merged**
