### PR TITLE
Fix #10552 various enhancements

### LINKED ISSUE #10552: Plugin enhancements and CI upgrades for template build
## Description

Improved configuration for 
- Attribution plugin
- Footer plugin
- build

add svgs
- headphones.svg
- triangle-top.svg

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

### PR DESCRIPTION
**Pull request by MV88**
## Description

Improved configuration for 
- Attribution plugin
- Footer plugin
- build
- translations

add svgs
- headphones.svg
- triangle-top.svg

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

Fix #10552

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by offtherailz — APPROVED** [review]

**Comment by offtherailz** [comment]
@ElenaGallo, could you please test this on  DEV  ? Thank you. 
No particular testing in reality. Maybe check the footer and attribution plugins still work as previously designed, and the icons of mapstore are correctly used.

**Comment by ElenaGallo** [comment]
@MV88 I noticed that the data export button is always visible in the footer, even when a new map is opened.
footer

**Comment by MV88** [comment]
i do not see it

image

**Comment by ElenaGallo** [comment]
Test passed @MV88 please backport to 2024.02.xx. Thanks

**Pull request merged**
