### PR TITLE
#8503 Bugs related modular plugins implementation

### PR DESCRIPTION
**Pull request by alexander-fedorenko**
## Description
Bugfixes for regression issues after implementation of #8457 

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
PR applies changes to resolve following issues:
https://github.com/geosolutions-it/MapStore2/issues/8476
https://github.com/geosolutions-it/MapStore2/issues/8477
https://github.com/geosolutions-it/MapStore2/issues/8478
https://github.com/geosolutions-it/MapStore2/issues/8479
https://github.com/geosolutions-it/MapStore2/issues/8480
https://github.com/geosolutions-it/MapStore2/issues/8481
https://github.com/geosolutions-it/MapStore2/issues/8482
https://github.com/geosolutions-it/MapStore2/issues/8483
https://github.com/geosolutions-it/MapStore2/issues/8484

**What is the new behavior?**
Regressions from issues listed above are resolved.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by allyoucanmap — APPROVED** [review]

**Comment by allyoucanmap** [comment]
@ElenaGallo please test this dev and let me know if I can backport, thanks

**Comment by ElenaGallo** [comment]
@alexander-fedorenko 

**1_** After testing the #8481 I found this:

I can not save the map from the MAP EDITOR INLINE
  
## How to reproduce

-  Login as admin
- Click on new geostory
- Click on Change Media Source
- Click on Maps tab
- Click on +
- Click on OK


*Current Result*
The Ok button is not clickable

**2_** After testing the #8483  I found this:

For the second steps of the wizard, the tutorial start at the beginning but then when I click on Show Tutorial button the tutorial does not start and for the third steps of the wizard, the tutorial does not start and when I click on Show Tutorial button the tutorial does not start. 

## How to reproduce
See the gif below: 

https://user-images.githubusercontent.com/56537133/188417165-a6aa5978-9e89-49e9-abea-3225fcf2ef95.mov

**Comment by alexander-fedorenko** [comment]
Hi @ElenaGallo, thanks! I'll take a look on first point.
Issue with tutorial is covered with https://github.com/geosolutions-it/MapStore2/pull/8544

**Comment by tdipisa** [comment]
>1_ After testing the https://github.com/geosolutions-it/MapStore2/issues/8481 I found this:

@alexander-fedorenko as I said in the call, consider that now when I click on OK nothing happens while if I click on Cancel I am brought in the same state of OK. This is an additional caveat.

**Pull request merged**
