### PR TITLE
backport 2023.02.xx - Fix #9685 measurements issues and added some enhancements to it (#9809) 

### LINKED ISSUE #9685: Extend the GeoProcessing tool to work with client side Vector layers as WPS inputs
## Description

Our client is asking for a new additional feature based on the recently developed GeoProcessing tool for supported **Intersection** and **Buffer** processes. 
The existing tool functionalities are expecting to be used only for WMS and/or WFS layers in TOC as inputs for aforementioned processes.
As part of this work it is requested to extend the current tool to also support vector layers defined or imported on the client side.

Possible use case scenarios to supports are:

- Use the output of the GeoProcessing tool (vector layers generated by a buffer or intersection geoprocess) for performing another operation using it as a new input
- Use an imported vector layer (SHP, GeoJson, KML etc) as an input for the GeoProcessing tool
- Use existing annotations as an input for the GeoProcessing tool (to check if possible, it could be excluded initially since we have a new implementation in master)
- Use vector layers TOC coming from measurements

In all cases the UX should be the same and well consistent.

Partial evaluation already done in https://github.com/geosolutions-it/MapStore-C265/issues/29#issuecomment-1752913734

## Acceptance criteria

- [ ] Allow local vector layers listed above to be used as input in the GeoProcessing plugin
  - [ ] measurements
  - [ ] imported GeoJSON
  - [ ] imported Shapefiles
  - [ ] other imports
  - [ ] annotations
- [ ] make sure that the CollectGeometries request sent to the backend is adapted for vector layers
- [ ] handle cases where Geometry collection is generated from a vector layer, because buffer and intersect processes fails with it, we should prevent the user to click run and notifying it via user feedback
- [ ] for intersection it should maintain the previous checks we do, first layer/ feature can't be a point
- [ ] Add possibility to configure a predefined geoserver url to be used as a fallback within process requests when the source layer is a local vector layer

### PR DESCRIPTION
**Pull request by MV88**
## Description

backport 2023.02.xx - Fix #9685 measurements issues and added some enhancements to it (#9809)

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
- [ ] If I export a measure as annotation, the buffer operation includes also the points and do not follow the geodesic lines. Istead the export as a layer works well. @tdipisa should we fix this?
image

 
image

- WFS Intersection works well :+1: 
image

- [ ] Circle annotation buffer generation looks wrong, but at the end the annoation seems to have a strange behavior in any case. In the video below you can see the annotation (yellow) and the buffer generated (green). The buffer looks wrong, but when I go in editing the circle changes its shape, and the buffer seems to be generated on that shape...  maybe this is a bug of the old annotations ? 

[screencast-localhost_8081-2023.12.21-16_01_44.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/8a9819f6-aeed-40e2-b64c-2d570b4c1a3b)

- [ ] Intersection between annotations and remote layer gives the error "It was not possible to collect the geometry from the layer Annotations - undefined"

[screencast-localhost_8081-2023.12.21-16_07_38.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/7a1afea6-ee96-4558-8c8e-45a320777be9)

**Comment by MV88** [comment]
@offtherailz this is ready for review, but i have to specify this:

the third point the one related to the intersection issue is resolved, but it remains problematic since there is this issue in geoserver that occurs
image

@tdipisa i think we should focus on fixing it on master (geoserver side probably) and not in the stable branch

**Comment by tdipisa** [comment]
> @tdipisa i think we should focus on fixing it on master (geoserver side probably) and not in the stable branch

@offtherailz please proceed with the review and then we will discuss this.

**Review by offtherailz — APPROVED** [review]
I can not replicate anymore the error on the backend, probably fixed by the NG argorithm configuration.
And circle issue looks to be proper of annotations (re-written), not of this PR. 

So for me this PR is approved.

**Comment by offtherailz** [comment]
Please @ElenaGallo test as well as it is deployed

**Pull request merged**
