### PR TITLE
[Backport 2023.02.xx] #9469: COG layer zoom to extent (#9497)

### PR DESCRIPTION
**Pull request by dsuren1**
#9469: COG layer zoom to extent (#9497)

### CODE REVIEW

**Review by tdipisa — APPROVED** [review]

**Comment by dsuren1** [comment]
@offtherailz 
The earlier fix to this issue in PR was amended by skipping `null` crs  but it also happens when `projectionDefs` of source is missing which results in [reprojectBbox](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/map/openlayers/Map.jsx#L594) returning bounds as `null` and trying to set null bounds to [map view](https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/map/openlayers/Map.jsx#L606) results in this exception. I'm going to prepare a fix which will set bounds only when it is valid. Kindly let me know if you have other suggestions. Thanks!

**Comment by tdipisa** [comment]
@dsuren1 please open a dedicated issue and connect tit to the PR. Thank you so much

**Comment by tdipisa** [comment]
@dsuren1 @ElenaGallo I've also raised a PR to align the QA config for better supporting tests, I forgot to do that before.
https://github.com/geosolutions-it/mapstore-datadir/pull/14

**Comment by tdipisa** [comment]
PR just merged and deployed in QA

**Comment by dsuren1** [comment]
> @dsuren1 please open a dedicated issue and connect tit to the PR. Thank you so much

@tdipisa I checked with @offtherailz and agreed that will check defs before adding `bbox` to COG layer as it less prone to error. I will add the same to the issue

**Pull request merged**
