### PR TITLE
fix #9367 review of geo processing tool

### LINKED ISSUE #9263: Geoprocessing Tools plugin
## Description

The plugin can be embedded into the main MapStore project.

Based on the requirements, it is intended that only the following WPSs must be maintained:
- geo:buffer
- gs:IntersectionFeatureCollection

We also understand that, for both layer selections, a feature from one of the layers present in map need to be selected for both the WPS. This means:
- UI to select one of the layer present in TOC
- Once a layer is selected, UI to select a feature geometry from it
  
The result is, in both cases, a new vector client side layer added in TOC that can be saved within the map.
It will be also necessary to include in the UI all the other possible parameters requested from the above mentioned WPSs along with the possibility to choose the name of the resulting vector layer in TOC.

An extendable WPS tool needs to be implemented for MapStore for these kinds of purposes leveraging the existing support to manage asynchronous requests.

## Acceptance criteria

Summarizing the UI & ACs here:

- [x] This will be an optional plugin to be used in contexts and not included in default map viewer
- [x] Will open as a right panel through a button in the sidebar
- [x] When a layer is selected as source or intersection it will check with **describe wps process** if geo:buffer and gs:IntersectionFeatureCollection, gs:CollectGeometries are available, if not notify it via a message in the UI (using a tooltip as addon
- [x] Propose to select two functionalities in a combobox working on top of the WPS OGC standard

Buffer (WPS _geo:buffer_):

- [ ] Once selected this will ask to provide:
  - [x] A list of layers coming from TOC as a source
  - [x] (optional) a list of features in a combobox with fid or named "feature 0" etc.  that are fetched via a GetFeature request
  - [x] A distance numeric field
  - [x] A combobox for the unit of measure similar to the one in the measure plugin
  - [x] A RUN button
    - [ ] If pressed and no feature is selected then it will do before a gs:CollectGeometries to get the entire geometry to be used in the wps process, in this case a confirmation modal appears because the process can be heavy and take a lot of time (we have to check about the possibility to run the process asynchronously in this case, as it happens for the existing export plugin)  
    - [ ] If a feature is selected from combobox it can highlight the feature in map by zooming on it and it will do a get feature with geometry to be used in the wps process
    - [ ] Optionally it can have a button on the side to enable feature selection from the map
- [ ] As agreed with @tdipisa **we will send coordinates in 3857** 
- [ ] add possibility to define the **quadrantSegments**  number
- [ ] add possibility to define the capStyle string
- [ ] summarizing the distance factor conversion: 
  - [ ] regarding the distance of the buffer a better approximation will be done in this way
    - [ ] calculate the centroid of the geometry
    - [ ] calculate the geodetic distance of two points distant 1000m towards east at the latitude of the centroid lat (using haversine formula)
    - [ ] result = 1000 / distance_calculated

Intersection (WPS _gs:IntersectionFeatureCollection_):

- [ ] In this case the ui will be 4 combobox
  - [ ] One for layer and feature of the source
  - [ ] One for layer and feature of the intersection layer
  - [ ] The behaviour is the same as described before for the feature selection, the difference is that in this case we need to send these data to the gs:IntersectionFeatureCollection process of the layer source
  - [ ] include also other missing parameters
  - [ ] first attributes to retain (String)
  - [ ] second attributes to retain (String)
  - [ ] intersectionMode - list  (intersection, first, second)
  - [ ] percentagesEnabled - Boolean
  - [ ] areasEnabled - Boolean

General ACs:
- [ ] exclude raster layers from the possibility to run the tool
- [ ] add a checkbox to toggle on and off highlighted features
- [ ] add single map selection for the feature
- [ ] Loading spinners and blocked UI are needed to give the user a useful feedback 
- [ ] Include warnings messages and notification where needed, especially if a tool is run with no feature selected
- [ ] add an advanced options section in an accordion the following parameters present in the list

## Other useful information

more details here https://github.com/geosolutions-it/MapStore-C265/issues/4

### LINKED ISSUE #9367: GeoProcessing tool review
## Description

This issue collects a few findings I discovered while checking the tool [here](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/tdipisa_demo_theme).

1. It seems all times I try to use the Intersection process, the tool returns the same error.  **This need to be investigated**
image

Below the WPS output:

```
<?xml version="1.0" encoding="UTF-8"?>
<wps:ExecuteResponse xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:xlink="http://www.w3.org/1999/xlink" xml:lang="en" service="WPS" serviceInstance="https://gs-stable.geosolutionsgroup.com/geoserver/ows?authkey=f7a11038-a04d-4519-b778-d0994232e9ae&amp;" version="1.0.0">
	<wps:Process wps:processVersion="1.0.0">
		<ows:Identifier>gs:IntersectionFeatureCollection</ows:Identifier>
		<ows:Title>Intersection of Feature Collections</ows:Title>
		<ows:Abstract>Spatial intersection of two feature collections, including combining attributes from both.</ows:Abstract>
	</wps:Process>
	<wps:Status creationTime="2023-08-29T13:49:41.590Z">
		<wps:ProcessFailed>
			<ows:ExceptionReport version="1.1.0">
				<ows:Exception exceptionCode="NoApplicableCode">
					<ows:ExceptionText>Failed to retrieve value for input first feature collection</ows:ExceptionText>
				</ows:Exception>
			</ows:ExceptionReport>
		</wps:ProcessFailed>
	</wps:Status>
</wps:ExecuteResponse>
```

Does it maybe depends on the dataset used fro this test? In this case an hardening is requested.

2. There is no need to have the validation icon clickable as a button
image

3. Let's use simply **GeoProcessing** and **Select the process to use**
image

4. One of the main goal of a tool should be to display the result clearly without letting the user to find it. It is not the case here, where the result of the geoprocessing tools is not visible at the end:
    - Both Buffer and intersection layers are appended in TOC and for this reason they are not visible
Image

    - At the end of the process the map should zoom to the interested area covered by the geometry produced by the process. At the same time the layer should have a good default style to properly highlight it and make it more evident. Where is the intersection below? This test has been performed using [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/geoprocessing_rev/45727).
Image

   - When selecting the layer result of a process, the "zoom to" doesn't appear in TOC toolbar but it should be.

5. Tow consecutive runs of the same process (and also more making the problem incremental) generate an inconsistent behavior in TOC. This test has been performed using [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/geoprocessing_rev/45727). 
Image

   - I think it is totally useless to create at each run a new group in TOC and it must be avoided
   - In addition the layer name should have some sense, but it is also true the user can change it in a second moment throug layer settings (so nothing to do for this now)

6. When switching from a geoprocess to another, all the form should be cleaned (see also https://github.com/geosolutions-it/MapStore2/pull/9351/#pullrequestreview-1599950036). At the moment the previous selection performed by the client remains and it is not coherent with the state of the form
Image

7. A more coherent tool icon must be created
Image

8. If you click on the tool icon with the catalog tool opened the tool's panel is not visible. Visibility rules and thees kind of interactions must be better managed 
Image

9. Typo to be fixed for the following notification message
Image

10. As I indicated [here](https://github.com/geosolutions-it/MapStore-C265/issues/4#issue-1700382132) in the original issue, the request was to implement an extendable WPS tool also for future evolutions while, talking with @offtherailz that reviewed the work, it seems the current implementation it's overdressed on the two currently supported processes. An abstraction level in the middle should be present so, we have to discuss about that**What kind of improvement you want to add?** (check one with "x", remove the others) 

- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

### PR DESCRIPTION
**Pull request by MV88**
## Description

fixed 
- highlight interaction, in particular [this](https://github.com/geosolutions-it/MapStore2/issues/9263#issuecomment-1688151308) comment
- see also this comment to know what has been done https://github.com/geosolutions-it/MapStore2/issues/9367#issuecomment-1705521520

not including complete refactor of the logic to get more abstracted processes, this will be done here #9398 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

fix #9367

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
[screencast-dev-mapstore.geosolutionsgroup.com-2023.08.29-11_55_01.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/0e3fec8d-8875-49db-9a41-5bbc0e8ba9d8)

I tried to switch to buffer, but I don't see any improvement. The 2nd feature remains highlighted. 

If it is not a strict requirement, I think that when switching the tool from buffer to intersection and viceversa, we could simply reset the full status, including the selection. 
In fact the presence of a field with a feature to select depends on the tool, and it is only a case that the 2 tools shares a feature to select as first element.
What do you thing @tdipisa ? I'm not fully aware if it is a requirement or not.

**Comment by tdipisa** [comment]
@MV88 @offtherailz I agree with that

>If it is not a strict requirement, I think that when switching the tool from buffer to intersection and viceversa, we could simply reset the full status, including the selection.
In fact the presence of a field with a feature to select depends on the tool, and it is only a case that the 2 tools shares a feature to select as first element.

In addition I've created this new issue to capture also other things I've notified.

**Comment by MV88** [comment]
> screencast-dev-mapstore.geosolutionsgroup.com-2023.08.29-11_55_01.webm 
> I tried to switch to buffer, but I don't see any improvement. The 2nd feature remains highlighted.

idk what have you tested exactly but in my local branch it works. 

anyway i'll check internal comments and related feedbacks made here https://github.com/geosolutions-it/MapStore2/issues/9367

**Review by tdipisa — COMMENTED** [review]
@MV88 

I think something similar to this would be nicer and coherent for this tool 

image

or this

image


what about this ?
image

**Review by offtherailz — CHANGES_REQUESTED** [review]
Here my review. Some issues found 

Tested using http://localhost:8081/#/context/geoprocessing_rev/45727


- [x] As you can see the layers are still unconsistent. Running twice the process, we have 2 groups. The two group seem to have the same ID, because when you try to select one, the second is selected too. This doesn't happen with Buffered layer. I'd suggest to use only one group named "Geoprocessing Outputs" to use as target group for all the layers. What do you think?
[double_layer.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/61fc490b-eb1d-4230-b59b-2791b27883d1)

- [x] When you close the panel afte the selction, the interaction with the tool is still active.

[closing_click_map.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/96a09040-c01e-48b7-97d8-b2bbeaf3f70c)

- [ ] Trying the tool I had a crash

[crash.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/09256c42-b938-4fbe-97c8-f55e9e920c73)

This is the log: 
```
Error in epic "zoomToExtentEpic". Original error: TypeError: coordinates must be finite numbers
    at checkCoord (checkSanity.js:14:11)
    at __WEBPACK_DEFAULT_EXPORT__ (checkSanity.js:6:3)
    at Function.transform (transform.js:27:56)
    at Object.reproject (CoordinatesUtils.js:248:158)
    at reprojectBbox (CoordinatesUtils.js:481:42)
    at eval (Map.jsx:276:92)
    at SwitchMapSubscriber.eval [as project] (map.js:206:7)
    at SwitchMapSubscriber._next (switchMap.js:88:27)
    at Subscriber.next (Subscriber.js:89:18)
    at FilterSubscriber._next (filter.js:88:30)
    at Subscriber.next (Subscriber.js:89:18)
    at MapSubscriber._next (map.js:83:26)
    at Subscriber.next (Subscriber.js:89:18)
    at FilterSubscriber._next (filter.js:88:30)
    at Subscriber.next (Subscriber.js:89:18)
    at WithLatestFromSubscriber._next (withLatestFrom.js:113:34)
overrideMethod @ console.js:213
eval @ EpicsUtils.js:28
CatchSubscriber.error @ catch.js:104
Subscriber._error @ Subscriber.js:128
[...]

EpicsUtils.js:31 Uncaught TypeError: coordinates must be finite numbers
    at checkCoord (checkSanity.js:14:11)
    at __WEBPACK_DEFAULT_EXPORT__ (checkSanity.js:6:3)
    at Function.transform (transform.js:27:56)
    at Object.reproject (CoordinatesUtils.js:248:158)
    at reprojectBbox (CoordinatesUtils.js:481:42)
    at eval (Map.jsx:276:92)
    at SwitchMapSubscriber.eval [as project] (map.js:206:7)
    at SwitchMapSubscriber._next (switchMap.js:88:27)
    at Subscriber.next (Subscriber.js:89:18)
    at FilterSubscriber._next (filter.js:88:30)
    at Subscriber.next (Subscriber.js:89:18)
    at MapSubscriber._next (map.js:83:26)
    at Subscriber.next (Subscriber.js:89:18)
    at FilterSubscriber._next (filter.js:88:30)
    at Subscriber.next (Subscriber.js:89:18)
    at WithLatestFromSubscriber._next (withLatestFrom.js:113:34)
checkCoord @ checkSanity.js:14
__WEBPACK_DEFAULT_EXPORT__ @ checkSanity.js:6
transform @ transform.js:27
reproject @ CoordinatesUtils.js:248
reprojectBbox @ CoordinatesUtils.js:481
eval @ Map.jsx:276
[...]
```

- [x] I see advanced options are not understandable. 
image
This is because you used the descriptions of the process options without using the name. This is conusing. "Indicates" what indicates ?
image
I suggest to use the name as label. If we want a better description, add a tooltip with the description of the field.

Summarizing the points in the #9367 , here I list them providing the current status. Please correct me if I'm wrong somewhere 
1. It seems all times I try to use the Intersection process, the tool returns the same error. This need to be investigated **PENDING** 
    - I understood it is probably due to the process and still to investigate. So this will not be part of the PR. Should we open an issue for that?
2. There is no need to have the validation icon clickable as a button. **FIXED**. 
3. Let's use simply GeoProcessing and Select the process to use **FIXED**
4. One of the main goal of a tool should be to display the result clearly without letting the user to find it. It is not the case here [...]
    - Both Buffer and intersection layers are appended in TOC and for this reason they are not visible - **FIXED** now they are on top **FIXED**
     -  Changing the style of the generated layer to yellow-orange. **FIXED**
     - At the end of the process the map should zoom to the interested area covered by the geometry produced by the process. At the same time the layer should have a good default style to properly highlight it and make it more evident. **FIXED** the zoom is done, the style changed.
5. Tow consecutive runs of the same process  generate an inconsistent behavior in TOC. **STILL TO BE PROPERLY FIXED**
6. When selecting the layer result of a process, the "zoom to" doesn't appear in TOC toolbar but it should be. **FIXED**
7. A more coherent tool icon must be created **FIXED** -- @tdipisa the layer with "i" has been used. Did you sync on this?
8. If you click on the tool icon with the catalog tool opened the tool's panel is not visible. Visibility rules and thees kind of interactions must be better managed **WONT DO** - This requires a window manager for mapstore
9. Typo to be fixed for the following notification message **FIXED**
10. As I indicated [...] **IN PROGRESS** something is done in this PR, something have to be done in a separate issue.

So point 1 and 8 are remaining, but they need to be done separately. 
Please also cinfirm me the point about the icon.

**Comment by MV88** [comment]
> Tested using http://localhost:8081/#/context/geoprocessing_rev/45727

Hi, can you provide the exported map/context and/or save it on dev? 

> 1. it seems all times I try to use the Intersection process, the tool returns the same error. This need to be investigated PENDING
I understood it is probably due to the process and still to investigate. So this will not be part of the PR. Should we open an issue for that?

addressed here https://github.com/geosolutions-it/MapStore-C265/issues/20

> 8. If you click on the tool icon with the catalog tool opened the tool's panel is not visible. Visibility rules and thees kind of interactions must be better managed WONT DO - This requires a window manager for mapstore

this is done within PR, when you have the geo processing tool opened, and you open the catalog, the geoprocess tool gets closed

> 7. A more coherent tool icon must be created FIXED -- @tdipisa the layer with "i" has been used. Did you sync on this?

i propose this
image

>  Trying the tool I had a crash

I cannot replicate this, and seems strange on the video itself, are there any steps that replicates this any time, maybe issue is data related

**Review by tdipisa — CHANGES_REQUESTED** [review]
the only thing I would like to fix for the moment is the icon of the tool that is cut on the left

**Review by offtherailz — CHANGES_REQUESTED** [review]
When posting an incomplete review fix, it could be a good practice ( sometimes happens also to me to forget) to summarize what is missing, and why, and what has been ackieved to be changed.

Here the issues I noticed.
- [ ] If you run a process, click on home, get back in instory and re-open the panel ,the panel contains the old setting. I suppose this is not a desired behavior. I noticed this while trying to replicate the crash. 

- [ ] I noticed that on panel close I have an error in console

```
EpicsUtils.js:28 Error in epic "toggleHighlightLayersOnOpenCloseGPTEpic". Original error: TypeError: You provided an invalid object where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at Object.subscribeToResult (subscribeToResult.js:73:27)
    at MergeAllSubscriber._next (mergeAll.js:85:42)
    at Subscriber.next (Subscriber.js:89:18)
    at ArrayObservable._subscribe (ArrayObservable.js:114:28)
    at Observable._trySubscribe (Observable.js:57:25)
    at Observable.subscribe (Observable.js:45:27)
    at MergeAllOperator.call (mergeAll.js:63:23)
    at Observable.subscribe (Observable.js:42:22)
    at Observable._subscribe (Observable.js:113:28)
    at Observable._trySubscribe (Observable.js:57:25)
    at Observable.subscribe (Observable.js:45:27)
    at Object.subscribeToResult (subscribeToResult.js:22:27)
    at SwitchMapSubscriber._innerSub (switchMap.js:101:63)
    at SwitchMapSubscriber._next (switchMap.js:94:14)
    at Subscriber.next (Subscriber.js:89:18)
    at FilterSubscriber._next (filter.js:88:30)
```
- [ ] I still can repliacate he crash, here another video. ( using locally, pointing on dev , this context map : http://localhost:8081/#/context/geoprocessing_rev/45727 )

[screencast-github.com-2023.09.18-14_34_42.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/445c4a6c-c131-46ce-b650-be17bccfaf6f)

I noticed that this is caused by the layer `bbox.bounds` is for some reason:

```
maxx: -Infinity
maxy: -Infinity
minx: Infinity
miny: Infinity
```

**Comment by MV88** [comment]
> When posting an incomplete review fix, it could be a good practice ( sometimes happens also to me to forget) to summarize what is missing, and why, and what has been ackieved to be changed.

**ACKNOLEDGED** will better do this 

>Here the issues I noticed.
- [ ] If you run a process, click on home, get back in instory and re-open the panel ,the panel contains the old setting. I suppose this is not a desired behavior. I noticed this while trying to replicate the crash. 

**FIXED** this issue has been fixed reducer side

> - [ ] I noticed that on panel close I have an error in console

**FIXED** there was a typo in the epic,

> - [ ] I still can repliacate he crash, here another video. ( using locally, pointing on dev , this context map : http://localhost:8081/#/context/geoprocessing_rev/45727 )

**FIXED** on reducer side because when you were selecting the intersection layer having activated the draw with source you ended up updating the wrong piece of state

All the rest of the points were done in previous iteration of code reviews

**Review by offtherailz — APPROVED** [review]

**Review by tdipisa — APPROVED** [review]

**Comment by ElenaGallo** [comment]
@MV88 @tdipisa In Advanced Settings, the option names are incorrect and are not translated correctly.

https://github.com/geosolutions-it/MapStore2/assets/56537133/2adb043a-5040-4801-bd56-132634af3767

**Comment by tdipisa** [comment]
@ElenaGallo please open a new issue for the above. thank you so much

**Comment by ElenaGallo** [comment]
@tdipisa New issue here: https://github.com/geosolutions-it/MapStore2/issues/9474
@MV88 please backport this to stable branch. Thanks

**Pull request merged**
