### PR TITLE
#8745 Fixed date/time/date-time editor for feature grid

### PR DESCRIPTION
**Pull request by offtherailz**
## Description
This PR fixes the issues found in https://github.com/geosolutions-it/MapStore2/issues/8745#issuecomment-1326229211 providing a more robust way to handle dates. 

During my investigation I noticed that even if the application seemed to work, in fact the values was not correctly set to the current selection. So I needed to refactor the editor component to fix these issues. 

As quoted here, GeoServer JSON format for 'time' field returns a full ISO String (probably a bug). 
With this PR:
 - I made the formatter of rows smart enough to format also full iso string correctly
 - I noticed several errors during editing due to race conditions. I fixed the editor in order to avoid these problems (`setState` is not enough because the featuregrid calls `getValue` on the component. If I override `getValue` reading the current state, I'll have the previous one. So I used `this.date` to store most recent change. This seems to solve all the strange editing behaviors.
 - Calendar sometimes was buggy and set the time in arbitrary way. With these fixes, the datePicker preservers the time when date is selected. 
 
**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#8745

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by tdipisa** [comment]
@offtherailz you set the wrong milestone. Since this PR is connected to #8745 the milestone and related release should be 2023.01.00.

**Comment by tdipisa** [comment]
@allyoucanmap @ElenaGallo after the merge we need the backport to 2022.02.xx-c040

**Comment by offtherailz** [comment]
Ok, Great. So no backport is needed. Going to remove the label too.

**Comment by tdipisa** [comment]
> Ok, @tdipisa . I was afraid this bug was also in 2022.02.xx. Good to know. So no backport is needed. Going to remove the label for backport too.

@offtherailz the backport is needed for this 
https://github.com/geosolutions-it/MapStore2/pull/8844#issuecomment-1330803856

**Comment by tdipisa** [comment]
@ElenaGallo please test this in DEV and let us know for the backport to 2022.02.xx-c040

**Comment by allyoucanmap** [comment]
@ElenaGallo please test on dev and let us know if we can backport on 2022.02.xx-c040 thanks

**Comment by ElenaGallo** [comment]
Test passed on DEV, @offtherailz please backport on 2022.02.xx-c040. Thanks

**Pull request merged**
