### PR TITLE
#4379 Application Context - Parametric viewers - Basic UI

### PR DESCRIPTION
**Pull request by vlt1**
## Description
Implements basic creation and browsing of contexts

## Issues
 - #4379 
 - ...

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [x] Other... Please describe: Enhancement

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by tdipisa** [comment]
@vlt1 the travis build is failing, please fix it so we can proceed with the review. Thank you.

**Comment by vlt1** [comment]
@offtherailz What should a unit test for an entry point look like? Are there any existing examples?

**Comment by offtherailz** [comment]
@vlt1 no, only for API, and other parts is enough.

**Comment by tdipisa** [comment]
@vlt1

we only need to have one path like the one below:
`/context/<context-name>/<map-id:optional>`

**Comment by offtherailz** [comment]
This PR is ok, anyway it still contains home page context browser, that has been replaced by this other PR:
https://github.com/geosolutions-it/MapStore2/pull/4493
Therefore I'm going to close this in favor of the other.

**Pull request closed without merging**
