### PR TITLE
#10663: fix adding decimals in the aeronautical form in searcg by coordinates

### PR DESCRIPTION
**Pull request by mahmoudadel54**
## Description
This PR handles fixing the issue of prevent enters centesimal number after the comma/dot for 
- aeronautical form and 
- decimal form as well

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
#10663 

**What is the current behavior?**
#10663 

**What is the new behavior?**
Now user can enter any centesimal numbers after the comma/dot like 0.04 , 15.1236 ...etc

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by tdipisa** [comment]
@mahmoudadel54 there is a failing tests that seems related to your contribution. Can you please check and fix it? Thank you so much.

**Comment by mahmoudadel54** [comment]
> @mahmoudadel54 there is a failing tests that seems related to your contribution. Can you please check and fix it? Thank you so much.

Fixing is done

**Review by MV88 — APPROVED** [review]
lgtm

**Comment by ElenaGallo** [comment]
Test passed, @mahmoudadel54 please backport to 2024.02.xx. Thanks

**Comment by mahmoudadel54** [comment]
> Test passed, @mahmoudadel54 please backport to 2024.02.xx. Thanks

Backport is done ---> https://github.com/geosolutions-it/MapStore2/pull/10678

**Pull request merged**
