### PR TITLE
Fix #10100 intersection advanced options

### LINKED ISSUE #10100: Geoprocessing tools - verify which advanced settings are not sent with intersection
## Description

We need to better check the advanced parameters that are used and sent to the wps process using intersection process

## How to reproduce

- check that all fields are sent

*Expected Result*

all fields are sent

*Current Result*

they are not sent

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### PR DESCRIPTION
**Pull request by MV88**
## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

Fix #10100 
**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by dsuren1 — APPROVED** [review]

**Comment by dsuren1** [comment]
@ElenaGallo Kindly test it in DEV. Thanks!

**Comment by tdipisa** [comment]
@ElenaGallo please let us know then if we can backport. thank you.

**Comment by ElenaGallo** [comment]
@MV88 @tdipisa I don't know if it concerns this PR but I noticed that if I add an attribute in the Advanced Option this is not visible in the layer's GFI.


https://github.com/geosolutions-it/MapStore2/assets/56537133/9cbf3e46-ef7b-4238-9ebe-c855a3cbf28a

**Comment by tdipisa** [comment]
> @MV88 @tdipisa I don't know if it concerns this PR but I noticed that if I add an attribute in the Advanced Option this is not visible in the layer's GFI.

It is not expected @ElenaGallo since it is not the purpose of these advanced settings.

**Pull request merged**
