### PR TITLE
#8010: 3D Tiles Styling

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description

This PR introduces styling functionalities for 3D tiles with following enhancements:

- include a vector style editor with visual and textarea
- styling for 3d tiles limited to color and pointSize properties based on the 1.0 specification https://github.com/CesiumGS/3d-tiles/tree/1.0/specification/Styling
- improve parsing of bbox from tileset
- include a error panel in replacement of the default one provided by cesium. The new panel provides also a reload button to refresh the map rendering after restoring the style
- add a simple parser for 3d tiles. This parser is mainly focused on writing rather then reading function

Notes:

1) The style saved in the layer will have these properties:

- `format` style encoding
- `body` content of the style
- `metadata.editorType` current editor in use: `textarea` or `visual`
- `metadata.styleJSON`  the json representation of the style. This is needed to keep the original information and structure of the style editor and for the possible problems related an exact conversion of the style. This is the same information we are using for WMS styling in geoserver

example
```
{
    "type": "3dtiles",
    // ...
    "style": {
        "format": "3dtiles",
        "body": {
            "color": {
                "conditions": [
                    [
                        "((!(${height} === undefined || ${height} === null || isNaN(${height})) && ${height} < 5))",
                        "color('#f0f9e8', 1)"
                    ],
                    [
                        "((!(${height} === undefined || ${height} === null || isNaN(${height})) && ${height} < 10))",
                        "color('#ccebc5', 1)"
                    ],
                    [
                        "((!(${height} === undefined || ${height} === null || isNaN(${height})) && ${height} < 15))",
                        "color('#a8ddb5', 1)"
                    ],
                    [
                        "((!(${height} === undefined || ${height} === null || isNaN(${height})) && ${height} < 20))",
                        "color('#7bccc4', 1)"
                    ],
                    [
                        "((!(${height} === undefined || ${height} === null || isNaN(${height})) && ${height} < 25))",
                        "color('#43a2ca', 1)"
                    ],
                    [
                        true,
                        "color('#3879ff', 0.12)"
                    ]
                ]
            },
            "meta": {
                "title": "'3D Tile Style'",
                "names": "'height < 5,height < 10,height < 15,height < 20,height < 25,others'"
            }
        },
        "metadata": {
            "editorType": "visual",
            "styleJSON": "{\"name\":\"3D Tile Style\",\"rules\":[{\"name\":\"others\",\"ruleId\":\"39298070-b031-11ec-927f-2911a3e94ad4\",\"symbolizers\":[{\"kind\":\"Fill\",\"color\":\"#3879ff\",\"fillOpacity\":0.12,\"symbolizerId\":\"39298071-b031-11ec-927f-2911a3e94ad4\"}]},{\"name\":\"height < 25\",\"ruleId\":\"25c4e6f0-b031-11ec-927f-2911a3e94ad4\",\"symbolizers\":[{\"kind\":\"Fill\",\"color\":\"#43a2ca\",\"fillOpacity\":1,\"symbolizerId\":\"25c50e00-b031-11ec-927f-2911a3e94ad4\"}],\"filter\":{\"filterFields\":[{\"rowId\":1648648576697,\"groupId\":1,\"attribute\":\"height\",\"operator\":\"<\",\"value\":25,\"type\":\"number\",\"fieldOptions\":{\"valuesCount\":0,\"currentPage\":1},\"exception\":null}],\"groupFields\":[{\"id\":1,\"logic\":\"OR\",\"index\":0}]}},{\"name\":\"height < 20\",\"ruleId\":\"116c5080-b031-11ec-927f-2911a3e94ad4\",\"symbolizers\":[{\"kind\":\"Fill\",\"color\":\"#7bccc4\",\"fillOpacity\":1,\"symbolizerId\":\"116c5081-b031-11ec-927f-2911a3e94ad4\"}],\"filter\":{\"filterFields\":[{\"rowId\":1648648539186,\"groupId\":1,\"attribute\":\"height\",\"operator\":\"<\",\"value\":20,\"type\":\"number\",\"fieldOptions\":{\"valuesCount\":0,\"currentPage\":1},\"exception\":null}],\"groupFields\":[{\"id\":1,\"logic\":\"OR\",\"index\":0}]}},{\"name\":\"height < 15\",\"ruleId\":\"e37cf9e0-b030-11ec-927f-2911a3e94ad4\",\"symbolizers\":[{\"kind\":\"Fill\",\"color\":\"#a8ddb5\",\"fillOpacity\":1,\"symbolizerId\":\"e37cf9e1-b030-11ec-927f-2911a3e94ad4\"}],\"filter\":{\"filterFields\":[{\"rowId\":1648648461084,\"groupId\":1,\"attribute\":\"height\",\"operator\":\"<\",\"value\":15,\"type\":\"number\",\"fieldOptions\":{\"valuesCount\":0,\"currentPage\":1},\"exception\":null}],\"groupFields\":[{\"id\":1,\"logic\":\"OR\",\"index\":0}]}},{\"filter\":{\"filterFields\":[{\"rowId\":1648648217777,\"groupId\":1,\"attribute\":\"height\",\"operator\":\"<\",\"value\":10,\"type\":\"number\",\"fieldOptions\":{\"valuesCount\":0,\"currentPage\":1},\"exception\":null}],\"groupFields\":[{\"id\":1,\"logic\":\"OR\",\"index\":0}]},\"name\":\"height < 10\",\"symbolizers\":[{\"kind\":\"Fill\",\"color\":\"#ccebc5\",\"fillOpacity\":1,\"symbolizerId\":\"5070c7d1-b030-11ec-927f-2911a3e94ad4\"}],\"ruleId\":\"5070c7d0-b030-11ec-927f-2911a3e94ad4\"},{\"name\":\"height < 5\",\"ruleId\":\"6df8e670-b030-11ec-927f-2911a3e94ad4\",\"symbolizers\":[{\"kind\":\"Fill\",\"color\":\"#f0f9e8\",\"fillOpacity\":1,\"symbolizerId\":\"6df8e671-b030-11ec-927f-2911a3e94ad4\"}],\"filter\":{\"filterFields\":[{\"rowId\":1648648265523,\"groupId\":1,\"attribute\":\"height\",\"operator\":\"<\",\"value\":5,\"type\":\"number\",\"fieldOptions\":{\"valuesCount\":0,\"currentPage\":1},\"exception\":null}],\"groupFields\":[{\"id\":1,\"logic\":\"OR\",\"index\":0}]}}]}"
        }
    },
    // ...
}
```

2) There are corner cases that are triggering rendering error while editing the style with the textarea editor. 

For example if we apply POSITION variable inside the style incorrectly this could cause an error:

```
{
  "color": "color(${POSITION}, 1)"
}
```

we cannot exclude the POSITION from the available variables because is supported by specification but not all the feature could contain it. We provided a message panel that allow the user to restore the style and reload the map rendering to mitigate this issue.

image

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Feature

## Issue

**What is the current behavior?**

#8010

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [x] No

### CODE REVIEW

**Review by offtherailz — COMMENTED** [review]
It looks very good. I like it a lot and it's almost perfect. 

I only have some docs/code organization notes: 
- getRecords should be moved in catalog, imho. Probably there is a good reason for doing it, but I didn't get it.
- You should JSDoc a little bit the 3dTiles api functions
- A link to the specification in the editor could be great, so the user can refer to it. Anyway it is a plus (is not present in other languages so it can be a future nice to have). 

Moreover I found that the original issue tells that the style should go in **override** to the intrinsic color. But looking at the API, it seems thay you can only **blend** the color with the intrinsic color. No way to override. So we will have the following aspect: 
- Because default intrinsic color is not white, you can not obtain "white", applying white color has no effect in fact. 
- colors will be different from the one displayed

This have to be clear, but I don't see any way to work around this.

**Comment by allyoucanmap** [comment]
> A link to the specification in the editor could be great, so the user can refer to it. Anyway it is a plus (is not present in other languages so it can be a future nice to have).

@offtherailz @tdipisa I would prefer to do this in a different issue. I'm not sure right now on how to expose this information in the UI and probably we need to find a solution that could work also with all the other formats.
I'm going to connect this comment to the doc issue to include some explanation about the styling format https://github.com/geosolutions-it/MapStore2/issues/8012

**Comment by offtherailz** [comment]
Yes, I ment this when I said "future nice to have"

**Review by offtherailz — APPROVED** [review]

**Comment by allyoucanmap** [comment]
@ElenaGallo kindly test this enhancement in DEV and let me know when I can backport to the stable branch 2022.01.xx, thanks

**Comment by ElenaGallo** [comment]
Hi @allyoucanmap, I only noticed this little problem:

Clicking the Undo style button when the style panel has just been opened, the gray error page appears.

https://user-images.githubusercontent.com/56537133/162208834-83c2ccf4-9481-4ef1-a9f8-10073fb4cee2.mov

**How to reproduce**
- Select a 3D 
- Open the Settings > Style
- Click on Undo style

**Comment by allyoucanmap** [comment]
Thanks @ElenaGallo ,
checking the error

**Pull request merged**
