### PR TITLE
Issue #7776; fix for overflowing display tab

### PR DESCRIPTION
**Pull request by tonym3nsa**
## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#7776 

**What is the new behavior?**

The display tab does not overflow and horizontal scrolling is no more present
## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by dsuren1 — CHANGES_REQUESTED** [review]
Hi @tonym3nsa 
I noticed few issues. Kindly fix these.

**Dashboard**
_Map -> Select a Map -> Layer settings -> Display tab_
2022-03-24 11_27_27-MapStore HomePage

**Geostory**
_Layer settings -> Display tab_
The content on the right are partially hidden
2022-03-24 11_31_19-MapStore HomePage

**Comment by tonym3nsa** [comment]
@dsuren1 I just pushed a fix but for good measure, could you tell me what browser and OS you used for testing?

**Review by dsuren1 — APPROVED** [review]

**Comment by dsuren1** [comment]
@ElenaGallo Kindly test this issue when deployed to DEV. And let us know if it can be backported to 2022.01.xx

**Comment by ElenaGallo** [comment]
Test passed, @tonym3nsa please backport to 2022.01.xx. Thanks

**Pull request merged**
