### PR TITLE
#6869 fixes showing empty identify popup window

### PR DESCRIPTION
**Pull request by QSafariallahkheili**
## Description

This PR fixes identify popup issue by filtering and eliminating empty features.
**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#6869

**What is the new behavior?**

Check the description
## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by MV88 — APPROVED** [review]

**Comment by MV88** [comment]
@ElenaGallo please test in DEV

**Comment by ElenaGallo** [comment]
@QSafariallahkheili some notes after testing this issue:

1- Now, on a map, the Identify tool reports only one of the two information present in the clicked point

*Now to reproduce**
- Open [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/openlayers/34324)
- Click a point on map with *observatories* and *US states* layers are both present
*Expected Result*
before

*Current Result*
The Identify tool reports only the info of *US states* layer.
now


2- On an embedded map, the Identify tool is no longer present.

*Now to reproduce**
- Open [this embeded map](https://dev-mapstore.geosolutionsgroup.com/mapstore/embedded.html#/34324)
- Click a point on map

*Current Result*
The Identify tool does not open

**Comment by tdipisa** [comment]
@QSafariallahkheili can you please check and fix the above?

**Comment by QSafariallahkheili** [comment]
Thank you for the comments.

For the first issue, I believe that the popup must show the information of the requested layer (the clicked layer), no matter how many layers are being rendered and are existed in the map canvas.

**Comment by tdipisa** [comment]
@MV88 @QSafariallahkheili is this PR fixing both points reported by @ElenaGallo above?

**Comment by MV88** [comment]
@tdipisa yes, but it needs some small changes requested by Lorenzo

**Pull request merged**
