### PR TITLE
#6481 Implement rate control for the geolocation update frequency

### PR DESCRIPTION
**Pull request by luorlandini**
## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#6481

Currently the update of geolocation positions follows the frequency dictated by the underlying Web Geolocation API

as you can see in the video, with an increment of 0.5 in latitude, the requests are 298

screen-capture-_1_

**What is the new behavior?**

We  introduce a configurable control rate, that will filter the position updates and only broadcast one update within the configured period 

as you can see in the video, with an increment of 0.5 in latitude and 1 second of rate control, the requests are 62

screen-capture-_2_

**How to enable Sensors tab in inspect element:**
Open inspect element / DevTools click on three vertical dots at the bottom left, and add sensors

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by allyoucanmap — CHANGES_REQUESTED** [review]
@luorlandini The part in OpenLayers works fine while the Leaflet locate

**Review by allyoucanmap — APPROVED** [review]

**Comment by tdipisa** [comment]
@ElenaGallo can you please test this in DEV? Let us know if we can proceed with the backport.

**Comment by allyoucanmap** [comment]
@ElenaGallo @tdipisa you need to add the `rateControl` parameter to Locate plugin configuration to test this PR.
eg:
in localConfig.json
```js
{
  "name": "Locate",
  "cfg": {
    "rateControl": 1000
  }
}
```

**Comment by ElenaGallo** [comment]
@tdipisa test done, @luorlandini please backport this PR to the stable branch

**Pull request merged**
