### PR TITLE
#6695 Sk translation

### PR DESCRIPTION
**Pull request by MV88**
## Description

Add language support for Slovak sk-SK

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [x] Other... Please describe: add sk language

## Issue

**What is the current behavior?**

#6695

**What is the new behavior?**

you can use sk tranlsations

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by fgravin** [comment]
Thanks @MV88 for updating the PR, was currently a bit busy to push this off.

**Review by offtherailz — APPROVED** [review]

**Comment by MV88** [comment]
we need to backport this to 2021.02.xx

**Comment by MV88** [comment]
@ElenaGallo you can test this locally by changing config in order to enable sk language

**Comment by ElenaGallo** [comment]
Test passed, @MV88 please backport to stable branch.

**Pull request merged**
