### PR TITLE
Fix 4349 Link's url problems in Annotations/widgets description

### PR DESCRIPTION
**Pull request by kboczkowski-clurgo**
## Description
Added method for updating all links from WYSIWYG editor

## Issues
 - #4349
 - ...

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by offtherailz** [comment]
@kboczkowski-clurgo this is fine, anyway I'm not sure the issue notified is properly a bug... 
@tdipisa are you sure we want to fix this? fxing this makes impossible to add relative URL's that are important for portability of the site. I prefer to close this as "not an issue".

**Comment by tdipisa** [comment]
@kboczkowski-clurgo, @offtherailz, as far as I can see in [DEV instance](https://dev.mapstore2.geo-solutions.it/mapstore/#/viewer/openlayers/356) this issue has been already solved.
@kboczkowski-clurgo what have you fixed in master?

**Comment by kboczkowski-clurgo** [comment]
@tdipisa Problem occurs when user paste or write URL without `http://`/`https://`. Web browser doesn't recognize it as seperate link and merges with current domain launched in tab. In that case I've added regex for validation of this link, and add `http://` at the begining

**Comment by tdipisa** [comment]
@kboczkowski-clurgo, I checked it and I agree with Lorenzo. We can close this PR without merging it.
@kboczkowski-clurgo I'm sorry about that but next time we need to talk about this things if needed without proceeding in a mechanical way: didn't you have any suspect before starting development?

**Pull request closed without merging**
