### PR TITLE
6722: Wrong GFI Behaviour using the Share tool

### PR DESCRIPTION
**Pull request by MuhweziDeo**
## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**
The share function triggers a GFI request and therefore the message "No active queryable layer" is visualized.

#6722

**What is the new behavior?**
All GFI requests should be disabled while using the share function.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
I noticed this bug. Please look that the coordinate is update on MAP_CLICK event.

- [x] Click on map doesn't update the coordinates (left original, right PR) it should take the center as initial value, then on map click it should update. Moving the map should not affect the center coordinate ( using the code of the PR I see it happens sometimes)
Peek 08-04-2021 17-20

**Review by offtherailz — APPROVED** [review]

**Comment by offtherailz** [comment]
This can be back-ported to 2021.01.xx when passing tests.

**Comment by tdipisa** [comment]
@ElenaGallo please test this in DEV and let @MuhweziDeo know for the backport to 2021.01.xx

**Comment by ElenaGallo** [comment]
@MuhweziDeo a note after testing this PR:

The marker remains on the map once the share panel is closed

**How to Reproduce**
See the gif below:
share_marker


*Expected Result*
Once the Share panel is closed, the marker disappears

**Comment by MuhweziDeo** [comment]
> @MuhweziDeo a note after testing this PR:
> 
> The marker remains on the map once the share panel is closed
> 
> **How to Reproduce**
> See the gif below:
> share_marker
> 
> _Expected Result_
> Once the Share panel is closed, the marker disappears

OkaY let me implement a fix for that

**Pull request merged**
