### PR TITLE
ensure jackson version is 2.13.1

### PR DESCRIPTION
**Pull request by taba90**
## Description

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [x] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#<issue>

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by tdipisa — COMMENTED** [review]
that's ok for me. @offtherailz can you also review that please?

**Review by offtherailz — APPROVED** [review]
Seems ok to me. 
We removed them from being included in by print engine. (see here): 
https://docs.mapstore.geosolutionsgroup.com/en/latest/developer-guide/mapstore-migration-guide/#upgrading-the-printing-engine

Maybe this caused the issues we found?

**Comment by tdipisa** [comment]
@offtherailz do you mean we should remove that exclusion?

**Comment by offtherailz** [comment]
I think the better way to handle it is using dependency management. The exclusion is ok for me, also because they are not connected at the moment.

**Comment by tdipisa** [comment]
@offtherailz they are not connected? What if I include in the build the printing?

**Comment by tdipisa** [comment]
@offtherailz can you please connect a MS issue for this and let @ElenaGallo know what tests are needed for this? Thank you.

**Comment by offtherailz** [comment]
> @offtherailz they are not connected? What if I include in the build the printing?

@taba90 can explain it better then me. 




> @offtherailz can you please connect a MS issue for this and let @ElenaGallo know what tests are needed for this? Thank you. @ElenaGallo as soon as test pass in DEV let us know so that we will merge the backport.

Please @ElenaGallo test installation of Extensions and effective load of the extension. This process tests highly the JSON parsing of the application and the upload entry point that was failing.

**Comment by ElenaGallo** [comment]
Test passed on DEV, @offtherailz it is possible to backport the pr

**Pull request merged**
