### PR TITLE
7444 Layer styles - Update "like" filter tooltip message if CSS style format is used

### PR DESCRIPTION
**Pull request by alexander-fedorenko**
## Description
This PR introduces changes required to have custom tooltip text for style filter when "like" operator is used. For "CSS" format message will be altered to use proper wildcards (% and \ instead of * and .)

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
#7444 

**What is the new behavior?**
Tooltip message is different for "like" operator & "css" format.
Also tooltip message for "SLD" format is slightly updated: bold style removed from dot because it was looking confusing, user might think it was underscore.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

https://user-images.githubusercontent.com/4226620/150815452-6eefdb6f-abf0-4693-adcd-70025e64b39b.mp4

### CODE REVIEW

**Comment by alexander-fedorenko** [comment]
One thing that I was not able to check on local installation is the symbol that escapes % and _ characters. There is no layer available where one of the properties has underscore or percentage sign in values.

**Review by allyoucanmap — APPROVED** [review]
LGTM

**Comment by allyoucanmap** [comment]
@ElenaGallo I just merged and moved to test

**Comment by tdipisa** [comment]
@ElenaGallo please test in DEV and let us know if we can backport

**Comment by ElenaGallo** [comment]
Test passed, @alexander-fedorenko please backport to 2021.02.xx. Thanks

**Pull request merged**
