### PR TITLE
Closed #2404 added tiled true by default in openlayers wms layers

### LINKED ISSUE #2404: Openlayers tiled parameter should be true by default
### Description
New layers added from catalog have tiled = false by default in OpenLayers

### Please indicate if this issue is related to a bug or a new feature request
- [x] Bug
- [ ] New Feature

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [ ] Internet Explorer
- [x] Chrome
- [x] Firefox
- [ ] Safari

any version

*Steps to reproduce*

- Select maptype to openlayers
- open a map
- add a layer from the catalog
- see the WMS requests parameters

*Expected Result*

Tiled should be true by default

*Current Result*
-  for that layer added the paramete tiled is false

### PR DESCRIPTION
**Pull request by MV88**
## Description
Added tiled true by default to wms layer for openlayers

## Issues
 - Fix #2404

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

**What is the current behavior?** (You can also link to an open issue here)
The tiled param in wms request was set to false by default in openlayers for layers added from catalog.
see #2404 for details

**What is the new behavior?**
now the value is set to true if it is missing

**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [x] No

### CODE REVIEW

**Comment by mbarto** [comment]
Was already working for leaflet?

**Comment by MV88** [comment]
was working for leaflet because of this
https://github.com/geosolutions-it/MapStore2/blob/master/web/client/components/map/leaflet/plugins/WMSLayer.js#L115

**Comment by offtherailz** [comment]
@mbarto the change is in the plugins folder, that is not under tests coverage. Should we skip the testing of that section for the moment? It could require a lot of time .

**Comment by mbarto** [comment]
I mean, I see both the checkbox tests and docs are checked, but no test is there and no doc either

**Comment by MV88** [comment]
@mbarto i removed the checkboxes to be consistent with the guidelines

**Pull request merged**
