### PR TITLE
Update Croatian translation

### PR DESCRIPTION
**Pull request by dracic**
## Description
Update Croatian translation. Contains changes 28.03.2018 -> 20.08.2018.

## Issues
 - Fix #<issue>
 - ...

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [x] Other... Please describe: Translation

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes
 - [x] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by dracic** [comment]
I don't think that this CI build fail has to do with translation update. Any suggestion?

**Comment by mbarto** [comment]
I don't think either. I will check tomorrow morning. Thanks for the contribution. By the way I was in Croatia last week. Very nice places.

**Comment by dracic** [comment]
@mbarto, I hope you've had a great time too. :grin:

**Comment by dracic** [comment]
FYI. Yesterday I had one fail locally (Fedora 28, Karma on Chrome) similar to this one on Github, but than two times with no changes:

```SUMMARY:
✔ 3074 tests completed
⚠ 35 tests slow
```

With a bunch of errors related to NumberPicker component:

```
ERROR: 'Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the NumberPicker component.'
```
Also I tried it now withe the same result.

**Comment by mbarto** [comment]
We have some randomly failing tests that bother us (mainly time-dependent tests that sometimes take too long to complete), so I wouldn't worry. I have just relaunched Travis-CI, but I am going to merge it after that, because it looks good to me.

**Pull request merged**
