### PR TITLE
6770:  DefaultPointType property not properly applied for all annotation types

### PR DESCRIPTION
**Pull request by MuhweziDeo**
## Description
This configuration property is properly applied in the case of Point annotations but not for other annotations types (Circle center point, Line start/end points) and it should be.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**
defaultPointType is applied only for Point annotations

#6770 

**What is the new behavior?**
defaultPointType is applied for all types of points features in annotations

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by MV88 — CHANGES_REQUESTED** [review]
there is something wrong here

https://user-images.githubusercontent.com/11991428/114899196-0a576900-9e13-11eb-9882-55bff4da568a.mp4


please apply these changes in your localConfig.json before 
image

**Comment by MuhweziDeo** [comment]
> there is something wrong here
> 
>  6770.symbols.mp4 
> please apply these changes in your localConfig.json before
> image

I think this happens due to the network requests fetching or creating the SVG(SVG icon is still being loaded). Not sure what the right strategy to fix this

**Comment by MV88** [comment]
@ElenaGallo you can test on DEV

**Comment by ElenaGallo** [comment]
Test done, @MuhweziDeo please backport this to the stable branch. Thanks

**Pull request merged**
