### PR TITLE
Fix #3842 Switching CRS, circle annotations change size

### LINKED ISSUE #3842: Switching CRS, circle annotations change size
### Description
When switching CRS using the CRS selector, **circle annotations** (if present) change their size.

### In case of Bug (otherwise remove this paragraph)

*Browser Affected*
(use this site: https://www.whatsmybrowser.org/ for non expert users)
- [x] Internet Explorer
- [x] Chrome
- [x] Firefox
- [x] Safari

*Browser Version Affected*

Last

*Steps to reproduce*

- Open a map
- Add some layer
- Add a circle annotation
- switch CRS through the CRS selector

*Expected Result*

The circle annotation doesn't change size.

*Current Result*

The circle annotation changes size.

### PR DESCRIPTION
**Pull request by vlt1**
## Description
Circles are no longer transformed from Polygon to Circle to allow correct rendering
under projection changes

## Issues
 - #3842 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
Circle annotations don't change size upon switching projections

**What is the new behavior?**
Circle annotations transform correctly with projection changes

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by mbarto** [comment]
I suppose circles were transformed to a polygon for a reason. Maybe @MV88 can explain us why and if this fix is reasonable or not?

**Comment by MV88** [comment]
> I suppose circles were transformed to a polygon for a reason. Maybe @MV88 can explain us why and if this fix is reasonable or not?

It's the contrary, but the confusion is around the management of circles.

Polygons that are circles in reality (when drawn as circles) should be rendered as circles (ol has the Circle type of geometry). they are transformed and passed to the state as polygons in order to perform spatial search or GFI operations, but when rendered they should be circles.

@vlt1 have you tested it by playing with Query form spatial filter and annotations? i suppose that if they are not transformed back to circle they would be rendered as polygons and by zooming in you should start seeing it that is not a circle, but a polygon.

**Comment by vlt1** [comment]
What should happen to circles when projection changes?

**Comment by mbarto** [comment]
Looking at the animated gif in the original issue, I think the problem exists when you switch between a meters based projection (EPSG:3857) and a degrees based one (EPSG:4326). Maybe  the problem is that radius is not converted between meters and degrees?
From openlayers documentation I see that radius should be expressed in the unit of measure of the current projection, so we should probably also convert radius when we reproject circles.

**Comment by vlt1** [comment]
That is exactly what was implemented, which is why the circle doesn't change it's size going from one projection to another. The fact of the matter is, when projection changes, what was a circle in one projection would become an ellipse in another one. So the question is, what should be the behaviour? Should an ellipse be drawn? Or should it be converted to circle in some way? If an ellipse should be drawn, how to do it? OpenLayers doesn't seem to be able to draw ellipses.

**Comment by mbarto** [comment]
I think a circle is ok, no need to draw an ellipse. @MV88 what do we do in other circle use cases?

**Comment by MV88** [comment]
> I think a circle is ok, no need to draw an ellipse. @MV88 what do we do in other circle use cases?

i think there are two problems related to circles and projections:
1. when che crs changes
1. when the crs does not change

the solution of course depends on the desired behaviour (@tdipisa we may need you here)
i think we need to go back a step and analyze a bit all the scenarios:

scenario: **circle from 3857 to 4326**
- i have drawn a circle which in the state is a polygon but is rendered as circle
- i switch to 4326, it should change to ellipse (in this case it will be polygon) because it should reflect original points which are used for GFI and spatial operations
- switching back it should be rendered again as circle

scenario: **circle from 4326 to 3857**
i think here is the same thing as the previous scenario

scenario: **circle drawn in 3857, no switch**
- i have drawn a circle as annotation
- i save it
- i want to see Circles rendered, not polygons.

@mbarto @offtherailz @tdipisa correct me if i'm wrong

**Pull request closed without merging**
