### PR TITLE
Issue #7983 - GeoStories - support of WMTS layers with tileMatrix configuration

### PR DESCRIPTION
**Pull request by ale-cristofori**
Implementation of map object parsing and tileMatrix key
inclusion for WMTS layer imported in geostories maps

## Description
This PR fixes a bug that made the map crash whenever a user saved a map containing at least one WMTS layer, may this be loaded as part of a saved `json` config file or as a newly created map/media resource in the MediaEditor component.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

#7983 

**What is the current behavior?**

**case 1.** Export a map from map Editor in json format and subsequently import the map in GeoStory within the media import, the import is successful, the application will crash upon geostory map confirmation.

**case 2.** create a new map from the map editor of GeoStory and add a WMTS layer (as a background or not), same result as case 1.

#7983 

**What is the new behavior?**

**case 1.** Export a map from map Editor in json format and subsequently import the map in GeoStory within the media import, the import is successful, the application will correctly translate `json` configuration in a map that will be displayed in the MediaPreview component.

recording_1

**case 2.** create a new map from the map editor of GeoStory and add a WMTS layer, once clicked on the `OK` button the MediaPreview component will display the loaded map resource.

recording_1

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information
1. Clarified in #7983 that `WMC` config files are currently not supported for WMTS layers configurations (only WMS is)
2. Once this is merged we may agree with the customer if this will be backported to previous releases or not.

### CODE REVIEW

**Comment by ale-cristofori** [comment]
@offtherailz or @allyoucanmap I would be happy to provide tests for this, but to be fair I cannot see where to start. If it is needed maybe some help for me would be good.

**Comment by ale-cristofori** [comment]
@allyoucanmap thanks for you guidance. Unit test is now included for selector. Ready for re-review

**Review by allyoucanmap — APPROVED** [review]

**Comment by allyoucanmap** [comment]
@ElenaGallo kindly test this fix in DEV and let us know when we can backport this to the stable branch 2022.01.xx

**Comment by ElenaGallo** [comment]
Test passed, @ale-cristofori please backport this to 2022.01.xx. Thanks

**Pull request merged**
