### PR TITLE
Search Service - show GFI

### PR DESCRIPTION
**Pull request by vlt1**
## Description
Addressing [this](https://github.com/geosolutions-it/MapStore2/issues/5386#issuecomment-691067643). On my machine firefox works fine, but on Chromium if button is disabled the tooltips were not shown at all. This concerns any such button(for example location button in NavBar). The issue seems to be that if the button is disabled mouseover event handlers are not triggered for some reason. To resolve this I've found a solution in writing custom OverlayTrigger that will wrap the button in span that will handle showing the tooltip.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
#5386 

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by MV88 — CHANGES_REQUESTED** [review]
@vlt1 Is it possible to change the current OverlayTrigger instead of creating a new one, by doing so we could fix the tooltip problem elsewhere. or am i wrong?

should not break anything doing that, right?

**Comment by vlt1** [comment]
@MV88 OverlayTrigger is part of react-bootstrap, I can't change it. The other way to go about it is to upgrade react-bootstrap to 4 from 3, but I'm not sure if that isn't going to break something. Also the new OverlayTrigger can be later expanded to have all functionalities of the react-bootstrap one and substituted for the react-bootstrap one.

**Comment by vlt1** [comment]
@MV88 OvelayTrigger in misc just wraps react-bootstrap OverlayTrigger with a hoc withContainer

**Comment by offtherailz** [comment]
Yes @vlt1 , I'd like to see if we can solve the problem once for all. We have a lot of these problems, so adding also this fix of our custom version can be useful. 
Can you try and test the buttons?

**Comment by MV88** [comment]
> Yes @vlt1 , I'd like to see if we can solve the problem once for all. We have a lot of these problems, so adding also this fix of our custom version can be useful.
> Can you try and test the buttons?

probably we can open  new issue to do this, @offtherailz what do you think ?

**Comment by offtherailz** [comment]
To fix it only there now you're doing a sort of workaround. 
If you prefer to open a separate issue to speed-up the delivery of the functionality, ok, but generally speaking I'd prefer to fix the general issue rather then fixing it once for every special case. 
So, ok for opening an issue, but open a separate issue now and work on it very soon.

**Review by MV88 — APPROVED** [review]
this looks good to me, but as agreed, i will open a new issue for fixing the other buttons that have the same problems

**Pull request merged**
