### PR TITLE
Geometries become invisible when Marker or Text element is being added #7511

### PR DESCRIPTION
**Pull request by alexander-fedorenko**
## Description
All annotation geometries become invisible when user adds new Marker or Text to the map and before coordinates of new geometry are set.
This PR resolves this issue by partially rolling back changes introduced by #7345

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
#7511 

**What is the new behavior?**
All geometries stay visible when user adds Marker or Text and before new geometry gets proper coordinate.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by MV88 — CHANGES_REQUESTED** [review]
@alexander-fedorenko hi, i tested it locally and found the following;

- [ ] i tested first case and when you have something invalid after having clicked to obtain a valid point --> everything disappears

https://user-images.githubusercontent.com/11991428/141501426-c43e107f-f8d8-462b-b9ec-07e62715df48.mp4

- [ ] can you confirm that case 2 is no longer reproducible  ?

**Comment by alexander-fedorenko** [comment]
Further investigation shown that it's impossible to properly draw Feature collection when one of its features is a "Point" with empty coordinates array. Although, passing geometry = null will hide Point from the map, but all other features in collection will be rendered properly. Here is the codepen that visualize such behavior: https://codepen.io/min-hd/pen/ExvOKex
The only possible solution is to modify geometry of Points (Text and Marker) before their changes get to the map. Proposed commit doing so by adding flag that triggers change specifically for invalid points.

**Review by MV88 — APPROVED** [review]
LGTM

**Comment by MV88** [comment]
@ElenaGallo please test in DEV

**Comment by ElenaGallo** [comment]
Test passed., @alexander-fedorenko please backport to 2021.02.xx

**Pull request merged**
