### PR TITLE
Fix #9208 Timeline map sync does not update for time ranges visualization

### LINKED ISSUE #9208: Timeline map sync does not update for time ranges visualization
## Description

The timeline chart does not update based on viewport even if the map sync button is selected.

https://github.com/geosolutions-it/MapStore2/assets/19175505/e0e7537a-6975-43b4-a738-7f88eabfe3ec

## How to reproduce

- open this [map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/44392) (login as admin if needed)
- expand the timeline
- zoom on a feature to exclude the other
- click on map sync

*Expected Result*

The timeline should update the visualization of time intervals based on the viewport of the map

*Current Result*

The timeline does not update the visualization of time intervals based on the viewport of the map

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

The sync issue it seems related to inconsistent state of the time domain property. The timeline updates the new range data inside the [updateRangeDataOnRangeChange](https://github.com/geosolutions-it/MapStore2/blob/53713aeb41af739abebb64ab44d4fce78da9295b/web/client/epics/timeline.js#L418-L423) epic dispatching rangeDataLoaded action and then read the new histograms and rang line items using the [itemsSelector](https://github.com/geosolutions-it/MapStore2/blob/53713aeb41af739abebb64ab44d4fce78da9295b/web/client/selectors/timeline.js#L147-L162). The itemsSelector is using different parts of the state to create the correct items used by the timeline for the visualization:

- layer reducer static domain properties
- dimension reducer domain properties
- timeline reducer rangeData properties

After some check it seems that even if the rangeData is correctly updated the dimension reducers is still containing information related to domain that are taking precedence over the new rangeData.
We will need to review the update workflow of range data to properly fix this issue.

- [Layer for testing](https://github.com/geosolutions-it/MapStore2/files/11623108/test_time.zip)

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description

This PR improved the get time items selector to use the updated range data if provided

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**

#9208

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [x] No

## Other useful information

@tdipisa 
It seems there is a problem with the spatial filter of domains, here an example:

The following example shows a DescribeDomains request where we expect to get information of a single feature but instead we get two:

request: https://development.demo.geonode.org/geoserver/gwc/service/wmts?service=WMTS&REQUEST=DescribeDomains&version=1.0.0&layer=geonode:test_time&tileMatrixSet=EPSG:4326&bbox=829991.4716345865,5755211.389189923,1039581.8031925397,5899065.876422625,EPSG:3857&expandLimit=20&time=2022-06-01T00:00:00.000Z/2024-01-09T11:07:53.218Z

response: 
```xml
<Domains xmlns="http://demo.geo-solutions.it/share/wmts-multidim/wmts_multi_dimensional.xsd" xmlns:ows="http://www.opengis.net/ows/1.1" version="1.2">
<SpaceDomain>
<BoundingBox CRS="EPSG:4326" minx="2.021484375000004" miny="40.871987756697415" maxx="30.849609375000014" maxy="50.645977340713586"/>
</SpaceDomain>
<DimensionDomain>
<ows:Identifier>time</ows:Identifier>
<Domain>2023-01-01T00:00:00.000Z/2023-06-01T00:00:00.000Z,2023-01-01T00:00:00.000Z/2023-12-31T00:00:00.000Z</Domain>
<Size>2</Size>
</DimensionDomain>
</Domains>
```

Visual representation of bbox param (red) and returned space domain (orange)
image

Note: We are also applying the bbox param to GetDomainValues and GetHistogram so they could have the same problem

### CODE REVIEW

**Review by offtherailz — COMMENTED** [review]
I should
- [ ] move expandLimitSelector  default internally if possible
- [x] Check and debug the single point use case to indentify why it works

**Comment by allyoucanmap** [comment]
@offtherailz below test done with master without applying fix from this PR:

The layer in this [map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/42064
) does not have data.values and the domain contains `--` for this reason it always pass to the `else if`

image

in this case the rangeData is populated from this app initialization because of the [updateRangeDataOnRangeChange](https://github.com/geosolutions-it/MapStore2/blob/153554ea72bfb38fdbb5546caf02817eb0859f24/web/client/epics/timeline.js#L434) epic that update the value for all domain that returns true for [isTimeDomainInterval](https://github.com/geosolutions-it/MapStore2/blob/153554ea72bfb38fdbb5546caf02817eb0859f24/web/client/utils/TimeUtils.js#L164)

image


https://github.com/geosolutions-it/MapStore2/assets/19175505/358432af-51b8-4dd7-82db-ce2898b80878


---

The check `|| data && data.domain && !isTimeDomainInterval(data.domain)` is still used by domain that are not interval because they have a rangeData equal to undefined at initialization

image

**Review by offtherailz — APPROVED** [review]

**Comment by tdipisa** [comment]
@offtherailz you forgot to merge this :) 

@ElenaGallo please test in DEV and let us know if we can backport.

**Comment by aaime** [comment]
The issue with the bbox capturing two features is due to the WMTS multidimensional using a "BBOX" filter against the database, which in turn is configured for [loose bbox](https://docs.geoserver.org/2.23.x/en/user/data/database/postgis.html#using-loose-bounding-box) filtering:

image

With loose bbox, queries are very fast, but not precise, as a "bbox vs bbox" filter is applied: the second line does not intersects the red search area, but the bbox of the line does, that's why it's returned.

How to fix it:

- Disable loose bbox at the store level. That will slow down all GetMap/GetFeature requests (I don't recall how much) to make all the filters more precise.
- Change the WMTS multidimensional code to use a "intersect polygon" filter instead, which is always precise, regardless of that setting.

**Comment by tdipisa** [comment]
Thank you so much for reporting the above @aaime

**Pull request merged**
