### PR TITLE
Fix #9653 embedded icons are correctly loaded

### LINKED ISSUE #9653: New Annotations - Icons issue in embedded maps
## Description

In the embedded map (2D and 3D), the icons are not seen correctly

## How to reproduce

https://github.com/geosolutions-it/MapStore2/assets/56537133/27b09893-8ce3-47e2-aad1-41dff48a9cac

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

## Other useful information

TBD with @allyoucanmap

### PR DESCRIPTION
**Pull request by MV88**
## Description

It seems that simply adding the css to the html file fixed the issue

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

Fix #9653

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [x] Yes, and I documented them in migration notes
 - [ ] No

### CODE REVIEW

**Review by allyoucanmap — CHANGES_REQUESTED** [review]
Instead to update all project with the font-awesome links in all template I would like to propose a different approach:

- remove all the <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/> from all the html files
- create a loadFontAwesome promise that check if the font-awesome css is in the page if not add it an wait the load or error
- place the loadFontAwesome just before the rendering of markers in the drawIcons promise of StyleParserUtils.js

Promise to load the link stylesheet:
```js
const loadFontAwesome = () => {
    return new Promise((resolve) => {
        const fontAwesomeHref = 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css';
        if (!document.querySelector(`link[href='${fontAwesomeHref}']`)) {
            const fontAwesome = document.createElement('link');
            fontAwesome.setAttribute('rel', 'stylesheet');
            fontAwesome.setAttribute('href', fontAwesomeHref);
            document.head.appendChild(fontAwesome);
            fontAwesome.onload = () => {
                resolve();
            };
            fontAwesome.onerror = () => {
                resolve();
            };
        } else {
            resolve();
        }
    });
};
```

the we could use it inside drawIcons 
```js
export const drawIcons = (geoStylerStyle, options) => {
   ...
   return loadFontAwesome().then(() => new Promise((resolve) => {
   ...
```

I did a quick test and it seems to work but I would better to double check if we decide to give it a try. The advantage of this approach are:

- font awesome will be loaded only when we are using a vector layer
- no need to add the link to existing custom project in the html files

**Comment by MV88** [comment]
@allyoucanmap please review it again

**Review by allyoucanmap — APPROVED** [review]

**Comment by allyoucanmap** [comment]
@ElenaGallo please test this fix on DEV, thanks

**Comment by ElenaGallo** [comment]
@MV88 I noticed that:
- the first time a point is added the icon is not visible

https://github.com/geosolutions-it/MapStore2/assets/56537133/c85e097a-79c5-42eb-820b-ee0976bdd561


- now, in the embedded map (2D and 3D), the marker is too large

https://github.com/geosolutions-it/MapStore2/assets/56537133/078c85de-0d7c-4e7d-a91d-8036e1ce62fe


- on share map via a direct link (2D and 3D), the icon is not visible

https://github.com/geosolutions-it/MapStore2/assets/56537133/58361931-e050-4b13-9d98-a3f67d81008c

- on permalink (2D and 3D), the icon is not visible

https://github.com/geosolutions-it/MapStore2/assets/56537133/017076f2-86b8-4dc1-a281-4bc99f209e6a

**Comment by MV88** [comment]
@ElenaGallo please test it in DEV

**Pull request merged**
