### PR TITLE
Fix #9545 export dxf and GeoJSON and UI refactor

### LINKED ISSUE #9545: Longitudinal Profile tool enhancement
## Description

It is requested to enhance the [Longitudinal Profile](https://docs.mapstore.geosolutionsgroup.com/en/latest/user-guide/longitudinal-profile/) tool by providing also _GeoJson_ and _DXF_ as export format.

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [X] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Other useful information
Export in GeoJson is not a problem using the WPS output but we should investigate a bit for the DXF one evaluating available JS client solutions like https://www.npmjs.com/package/dxf-writer (or other). The dependency should be lazely loaded.

### PR DESCRIPTION
**Pull request by MV88**
## Description

examples
[profile-dxf.zip](https://github.com/geosolutions-it/MapStore2/files/13903457/profile-dxf.zip)
[profile.json](https://github.com/geosolutions-it/MapStore2/files/13903456/profile.json)
image

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

Fix #9545

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by dsuren1 — CHANGES_REQUESTED** [review]
@MV88 

- On exporting PNG, the export `File format` dropdown option is also present in the output
  <kbd>
  image
  </kbd>

- On importing `dxf` file that was exported from Longitudinal plugin, I get the following error
 
   image

- Similarly on importing `geojson` file, the following warning is shown and the import action is interrupted
   image

[export.zip](https://github.com/geosolutions-it/MapStore2/files/13938110/export.zip)
Also happens with examples attached in the PR description. 




Context - `/context/9241_long_profile`

**Comment by MV88** [comment]
@tdipisa the only issue is about the export in PNG the other ones are expected to happen give the nature of the exported formats.
- the geojson exported contains points that have a properties
- the dxf is using a drawepolyline3d which results in being incompatible as input  

a test on dxf input can be this one
[a_dxf_line.zip](https://github.com/geosolutions-it/MapStore2/files/13947766/a_dxf_line.zip)

**Comment by dsuren1** [comment]
@MV88 
PNG export work fine.

> a test on dxf input can be this one [a_dxf_line.zip](https://github.com/geosolutions-it/MapStore2/files/13947766/a_dxf_line.zip)

I'm unable to check this as upon import I get this error
image
image

If this is expected, then I'm good to approve. Kindly clarify. Thanks!

**Review by dsuren1 — APPROVED** [review]
LGTM. However, I'm unable to find test data (dxf file) that lands on sfdem layer to check import of dxf file

**Comment by tdipisa** [comment]
> LGTM. However, I'm unable to find test data (dxf file) that lands on sfdem layer to check import of dxf file

@ElenaGallo can I kindly ask you to better test importing a dxf file. You should be able to do that by using the GS dxf extension.

**Pull request merged**
