### PR TITLE
Mobile override shallow merge fix

### PR DESCRIPTION
**Pull request by alistairjmcintyre**
## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

When updating `localConfig.json` with an `initialState.mapInfo.highlight` value to enable on-click feature highlighting, this doesn't work when running MapStore in mobile mode. 

This appears to be due to the fact that a shallow merge between `newState` and `mobileOverride` is done by the root reducer function.

**What is the new behavior?**

`mobileOverride` and `newState` are correctly merged so that no values are lost when adding overrides for mobile.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information
I'm submitting this PR because I feel like this was intended behavior, however I can understand this may have been entirely intentional, and would appreciate feedback on if there's a better way to do this. I understand I can override `standardRootReducerFunc`, but that may not be an easy option for everyone.

### CODE REVIEW

**Comment by offtherailz** [comment]
The general idea is good and it doesn't look to generate any problem.
Actually we didn't used too much the mobile override. So testing it manually could be hard. For this reason I should suggest to add unit tests to define and lock the functionality intention. Could you provide them?

**Comment by alistairjmcintyre** [comment]
Hi I just wanted to add, I haven't forgotten about this I've just been absolutely swamped with work and haven't been able to add the tests yet!

**Comment by alistairjmcintyre** [comment]
@offtherailz I think these tests are sufficient for the change made. I just wanted to ensure that the deep merge was occurring as I expected, but only on mobile.

**Review by offtherailz — APPROVED** [review]
Looks good to me. 
I'll wait for the checks to run and then I'll merge it.

Thank you very much for contributing :+1:

**Pull request merged**
