### PR TITLE
Update managing-users.md

### PR DESCRIPTION
**Pull request by jkariukidev**
Updated typo in [managing users]() from _'Amin_ to _'Admin'_

## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [x] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#<issue>

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by MV88** [comment]
Ty for the contribution, next time you can create a single PR if you find more things to fix :)

**Review by MV88 — APPROVED** [review]

**Comment by jkariukidev** [comment]
> Ty for the contribution, next time you can create a single PR if you find more things to fix :)

Okay. Thanks for the recommendation.

**Review by tdipisa — APPROVED** [review]

**Comment by tdipisa** [comment]
Thank you @jkariukidev

**Comment by jkariukidev** [comment]
> Thank you @jkariukidev

Welcome

**Pull request merged**
