### PR TITLE
#7172: migration to GeoStore 1.8-SNAPSHOT to inherit latest spring co…

### PR DESCRIPTION
**Pull request by mbarto**
…mpatibility

## Description
This pull request upgrades MapStore to use version 1.8 of geostore, and as a consequence, newer versions of most of the backend base libraries and frameworks, in particular:

| Library      | Old |New|
| ----------- | ----------- |--|
| Spring| 3.0.5|5.3.9|
| Spring-security| 3.0.5        |5.3.10|
| CXF| 2.3.2        |3.4.4|
| Hibernate|      3.3.2   |5.5.0|
| JPA| 1.0        |2.1|
| hibernate-generic-dao| 0.5.1        |1.3.0-SNAPSHOT|

This enables implementing new features, using latest Spring based libraries that were not compatible with the very old one we were using so far.

Summary of the most important changes:
 - Tomcat 8.5 is now required, because it's mandatory for Spring 5 support
   * Tomcat 8.5 is now included for the standalone bin 
   * Tomcat 8.5 is used when the backend is run through maven (using the new mvn cargo:run command, that replaces mvn tomcat7:war-run)
 - the updated Spring MVC does not remove the optional extension from the url, so the config API controllers have been updated to take this into account (e.g. the localConfig resource will now be recognized also with the full name of localConfig.json)
 - the geostore login endpoint now returns a nested object with sessionToken as a root property, while the old one was flat (this behaviour change is due to the upgrade of CXF and the related json serializer, and it is more inline with other geostore APIs behaviour, so I can say that the old one was probably a bug in CXF itself). MapStore GeoStoreDAO has been adapted to accept both the old and the new response type

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [x] Other... Please describe: upgrade of libraries

## Issue
#7172 

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [x] Yes, and I documented them in migration notes
 - [ ] No

Breaking changes are mostly related to the backend requirements and configuration, in particular:
 - Java 8 and Tomcat 8.5 are now required to run MapStore
 - A couple of configuration changes in web.xml and geostore-spring-security.xml are needed (look at the migration notes for more details) to disable new defaults that are not compatible with MapStore, in particular CSRF needs to be disabled for the CXF requests (geostore)

### CODE REVIEW

**Review by offtherailz — COMMENTED** [review]
Generally LGTM. Only 2 questions below:
- [ ] mapstore-services latest 1.2 has been released before upgrading ?
- [x] Why updated publicPath in standard/templates ? is it a fix to the project independent from this update? It looks correct to me, it's same I did in `build/prod-webpack.config.js`

**Comment by mbarto** [comment]
> Generally LGTM. Only 2 questions below:
> 
> * [ ]  mapstore-services latest 1.2 has been released before upgrading ?

I have no idea, isn't it published during MapStore release?

> * [ ]  Why updated publicPath in standard/templates ? is it a fix to the project independent from this update? It looks correct to me, it's same I did in `build/prod-webpack.config.js`

Yes, it is unrelated, I needed for testing a newly created project with the updated backend

**Comment by offtherailz** [comment]
> I have no idea, isn't it published during MapStore release?
Let me check.

**Review by offtherailz — APPROVED** [review]
I updated #7233 to release also mapstore-services 1.2.0 .

**Comment by offtherailz** [comment]
as well as we solve problems on dev, we can re-merge your PR @mbarto .
Sorry for the inonvenient

**Pull request merged**
