### PR TITLE
Add resources to Developer Guide

### PR DESCRIPTION
**Pull request by Gnafu**
Adds instruction on own to customize the Theme and the search box services
Also make the standalone demo page accessible again

### CODE REVIEW

**Comment by mbarto** [comment]
This does not seem a user guide to me

**Comment by offtherailz** [comment]
Yes it looks more like a work in progress. Should we place some "TODO" here and there to make it become a user guide?

**Comment by mbarto** [comment]
Maybe we should simply remove what is not interesting to users, or redefine what a user is: a developer, a configurer, a designer (themes) or someone who uses the application?
This is not clear to me. From this PR it can be one of the first 3 roles, but not the last one.

**Comment by Gnafu** [comment]
Whatever solution is fine for me, I just don't want to loose this informations as they are not documented anywhere (or they are buried in the mapstore-users mailing list)

**Comment by mbarto** [comment]
I was wondering if the stuff you wrote is more developer oriented, than user oriented, and we already have a developer guide (where you can add new pages, if you like)

**Comment by Gnafu** [comment]
Moved them to the developers guide

**Comment by offtherailz** [comment]
Sorry if I take this too late, but the theme customization is for the dev guide, but the search services configuration is accessible from the web, so it's part user's guide, in my opinion. Should we merge this anyway?

**Pull request merged**
