### PR TITLE
#9739: Fix - Incorrect connection of the parent table with the map and other widget

### PR DESCRIPTION
**Pull request by dsuren1**
## Description
This PR fix the incorrect connection of parent table with map and other widgets.

### NOTE
The reason for creating this PR pointed directly to `2023.02.xx` is because the original fix in DEV deals also with **traces in the charts widget** and the traces changes are not yet backported to stable.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
- #9739 

**What is the new behavior?**
- Fixes the connection made to the parent table widget with map and other widgets
- Fixes multi-selection of maps and layers in the dashboard wizard for Mac as the event key was not handled correctly

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
In QA when I have no data I have this result:

image

Instead in the PR I have this issue:

image


Please fix.

**Comment by dsuren1** [comment]
> Instead in the PR I have this issue:
> 
> image
> 
> Please fix.

I have made this fix in another PR for DEV and will cherry pick it

**Comment by dsuren1** [comment]
**Fixed**
image

**Review by offtherailz — APPROVED** [review]

**Comment by offtherailz** [comment]
@ElenaGallo, could you please test this on   QA ? Thank you

**Pull request merged**
