### PR TITLE
Fix #9945 WFS legacy style breaks the app in OpenLayers

### LINKED ISSUE #9945: WFS legacy style breaks the app in OpenLayers
## Description

A change introduced in this PR #9888 removed the `asPromise` property needed to handle wfs legacy style

## How to reproduce

-  open this [map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/48274)

*Expected Result*

Map should be visible and working

*Current Result*

Application is not working and the message Oops, something has gone wrong... is displayed

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description

This PR restores the `asPromise` set to true for WFS layers for the OpenLayers implementation

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**

#9945

**What is the new behavior?**

The WFS layer with legacy style will not break the application

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [x] No

### CODE REVIEW

**Comment by tdipisa** [comment]
@allyoucanmap to be backported to https://github.com/geosolutions-it/MapStore2/tree/c040-2024.01.xx once approved. Thank you.

**Review by dsuren1 — APPROVED** [review]
LGTM!

**Comment by dsuren1** [comment]
@ElenaGallo Kindly test this fix in DEV and let us know if it can be backported. Thanks!

**Comment by tdipisa** [comment]
@ElenaGallo please test in DEV and let us know [if we can backport](https://github.com/geosolutions-it/MapStore2/pull/9947#issuecomment-1921436533)

**Comment by ElenaGallo** [comment]
Test passed on DEV. @allyoucanmap please [backport](https://github.com/geosolutions-it/MapStore2/pull/9950#issuecomment-1921705597)

**Pull request merged**
