### PR TITLE
#5224: ldap security configuration and related docs improved

### PR DESCRIPTION
**Pull request by mbarto**
## Description

This work introduces a backend build profile to get a standard LDAP security configuration.

This is done by:
 * replacing the geostore inerithed security configuration with 2 mapstore specfic ones (security-db and ldap)
 * adding two build profiles for the above configurations, security-db enabled by default and ldap enabled on demand
 * a dedicated ldap.properties for build or runtime configuration of ldap connection settings

The documentation has been improved by describing the new build procedures for LDAP configuration and introducing the (experimental) direct connection mode.

Direct connection mode still needs some work on the geostore side to be fully functional in the standard scenario. The missing things have been captured here: https://github.com/geosolutions-it/geostore/issues/219

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [x] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
#5224 

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by tdipisa** [comment]
@mbarto thank you for this. I think we have to talk a bit before merging this PR. After reading the PR description I only would like to resume this to check for eventual breaking changes in existing installation configured in the old way.

**Comment by tdipisa** [comment]
Before merging this PR, geosolutions-it/geostore#219 must be closed.

**Review by tdipisa — CHANGES_REQUESTED** [review]
@mbarto the PR [here](https://github.com/geosolutions-it/geostore/pull/220) has been merged. Thank you so much. I've asked @offtherailz for a review of this PR. 
Can you please publish on mvn the version 1.7-SNAPSHOT of geostore and then update the MapStore pom accordingly to use it? I think you can directly update this PR for this.

**Review by offtherailz — COMMENTED** [review]
Ok, tested. It is working good :+1: 
I only suggested some minor improvements on documentation. About custom project already using sync mode, do you know how they can be migrated to use this system easly (actually use property replacement, that is a little harder to maintain) ?

**Review by offtherailz — APPROVED** [review]

**Review by tdipisa — APPROVED** [review]

**Pull request merged**
