### PR TITLE
#5773: Fix issues with GFI popup in edit mode

### PR DESCRIPTION
**Pull request by dsuren1**
## Description
Fixes the issues with GFI popup in edit mode

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [X] Bugfix

## Issue

**What is the current behavior?**
#5773 

**What is the new behavior?**
- Pagination instead of stacking of the viewer
- Restrict empty responses only to GFI panel on feature click 
- Display first response with data instead of empty viewer 

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information
Related to #5465

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
Hi,
- [ ] As far as I understood you fixed the problem by removing the empty results from the list, that cause some problem in rendering. Can you please explain it better the reason of the bug and the solution ? 
- [ ] IMO `identifyFloating`  property should not be propagated (at least with this name) to the default viewer. We can think to rename with `renderEmpty` flag (with the opposite meaning), anyway I want to make sure that this flag is really needed, and if there is a way to simplify it. 
Also because checking the code I noticed also this bug. https://github.com/geosolutions-it/MapStore2/issues/5811
What do you think about it? 

- [ ] Pointing the mouse in an area with only states layer, during the loading I see first the spinner, then the spinner disappears and I see the popup has this state, until the content is loaded (or the no-data is shown)
Peek 01-09-2020 10-53
image
Is it possible to keep the spinner until the some are visible, or the blue box as in the original popup 
Peek 01-09-2020 10-46
?

**Review by offtherailz — COMMENTED** [review]
Why do you wait until all responses are received to show the results?
Some servers may take some time to respond, so we used to to start showing the results while downloading. Tipically, from the previous requirements, the first result that is received is shown.
Anyway I've seen it and it is not that bad. If possible, I should start showing something (maybe the loading spinner shown in a corner, until is finished).

@allyoucanmap , @tdipisa what do you think?

The rest of the PR works perfectly

**Comment by dsuren1** [comment]
> Why do you wait until all responses are received to show the results?
> Some servers may take some time to respond, so we used to to start showing the results while downloading. Tipically, from the previous requirements, the first result that is received is shown.
> Anyway I've seen it and it is not that bad. If possible, I should start showing something (maybe the loading spinner shown in a corner, until is finished), because it can take seconds to get a response.
> 
> @allyoucanmap , @tdipisa what do you think?
> 
> The rest of the PR works perfectly

I have fixed this.  Instead of waiting for all responses to be received, from now, will start showing the results as soon as they are received

**Review by offtherailz — CHANGES_REQUESTED** [review]
Great job. I only found a problem with Empty pages in GeoStory identify
image

**Review by offtherailz — APPROVED** [review]

**Pull request merged**
