### PR TITLE
#4748 Sync 3D switch with maptype

### PR DESCRIPTION
**Pull request by offtherailz**
## Description
This PR fixes several issues about 3D maps. 
- Now the URL of a map and the effective map used are always in sync (if the URL contains the maptype)
- MapType switch works even without the maptype in the URL (useful to add 3D switcher in contexts or maps with a different routing)
- 3d maptype is always reset when location change (if the new URL do not contain maptype). So dashboards/geostories etc... will always use 2d maps. This solves issues for #4748 too. 

### Info for testers
In order to test this you should try all the possible ways to switch 3D modes and navigate. 
Some examples: 
- open a map with the URL 
- Edit the maptype in the map url (/viewer/openlayers/1234 ---> /viewer/cesium/1234)
- open a map, switch to 3d mode, navigate back to dashboards or stories.
- From a context with 3D mode, switch to 3D, then use the map catalog:
   - If open a map (created within a context 3d) should be disabled
   - If open a normal map, the mode should be reset to the default
   - Share links should not contain /cesium/ even if 3d tool is active

### Info for reviewers

I moved the logic for switching to last 2D mode and to sync URL with 3d all in maptype epic. This should make the application work even in contexts without globeswitcher. Now the logic of maptype sync is only in one place.
I also moved the maptype epics, related only to routing (reset maptype/sync with the URL) in the standardEpics, as discussed with @allyoucanmap 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#4748

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by MV88 — APPROVED** [review]
LGTM

**Comment by tdipisa** [comment]
@ElenaGallo please test this in DEV and let us know if we can backport.

**Comment by ElenaGallo** [comment]
@offtherailz From a [context] (https://dev.mapstore2.geo-solutions.it/mapstore/#/context/4748cont) with 3D mode, switch to 3D, then click on map catalog and open the Demo map: the 3d tutorial opens and the URL is ../#/viewer/cesium/10358

**Comment by ElenaGallo** [comment]
@offtherailz the issue on the comment above now works. Please backport this on the stable branch.

**Pull request merged**
