### PR TITLE
fix catalog loading error when no style defined

### PR DESCRIPTION
**Pull request by flobz**
## Description
This pr fix the issue : #6549.
IGN doesn't provide style definition for every capabilities of the wmts service at this address: http://wxs.ign.fr/choisirgeoportail/geoportail/wmts.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue
 #6549 

**What is the new behavior?**
If layer.Style isn't set getDefaultStyleIdentifier return null instead of throwing an exception.
## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [x] No

### CODE REVIEW

**Comment by tdipisa** [comment]
@flobz thank you for your contribution, we will review as soon as possible.

**Review by MV88 — CHANGES_REQUESTED** [review]
please approve and merge [this](https://github.com/flobz/MapStore2/pull/1) PR
where i'm adding some unit tests

and then we are good to go :)

ps thanks for contributing

**Comment by flobz** [comment]
Done! :)

**Review by MV88 — APPROVED** [review]

**Comment by MV88** [comment]
this will need a backport to 2021.02.xx when release 2021.01.01 is out

**Comment by tdipisa** [comment]
@ElenaGallo can you please check this in DEV and let us know if we can proceed with the backport to 2021.01.xx?

**Comment by ElenaGallo** [comment]
@MV88 test done, please backport this to the stable branch, thx.

**Pull request merged**
