### PR TITLE
Fix #10238 Change Math.random with an alternative solution - C039

### LINKED ISSUE #10238: Change Math.random usages with an alternative
## Description

It was requested to substitute every usage of Math.random with an alternative like window.crypto.getRandomValues
for that we need to update two branches the 
- c039_math_random 
- master

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

### PR DESCRIPTION
**Pull request by MV88**
## Description

changing math.random instances with window.crypto.getRandomValues

Branch is **[c039_math_random](https://github.com/geosolutions-it/MapStore2/tree/c039_math_random)**

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [x] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

Fix #10238 

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by offtherailz** [comment]
I think for build you have to update your fork to most recent version.

**Comment by MV88** [comment]
> I think for build failuire on documentation and in general, you have to update your fork to most recent version.

it's not necessary to do that imho since it is only for a specific project that will be updated to master in the future

**Comment by MV88** [comment]
> [ ] If it is a general Math utility, it should be in the `utils` folder. Not in `utils/cesium`

I didn't want to create another new file called MathUtils but I might be wrong. 
Going to do it

> Evaluate to use this es-lint rule to prevent usage

I can spend some time checking it, good tip

**Comment by MV88** [comment]
@offtherailz please review it again since i have fixed the paths of the functions.

for eslint I tried but I was not able to integrate the singular rule, or to make it to be treated as error.
probably i was not correctly setup the project, what I tried was:
- npm install --save-dev eslint-plugin-security-node on root
- edit node_modules\@mapstore\eslint-config-mapstore\index.js by adding the plugins (and the single rule  with **"detect-insecure-randomness",2** not working))
- edit package.json by adding the extends required
- adding some code with math.random() 
- reloading window

result: 
i was getting this
image

and by removing  the rule from index.js of node_modules eslint i got only the highlight as suggestion/warning

in [this](https://github.com/MV88/MapStore2/tree/detect-insecure-randomness) branch there is the partial setup, then you have to edit locally the eslint files used by mapstore

**Comment by offtherailz** [comment]
In the master PR I renamed it as `RandomUtils` to be more clear. 
About this PR, I think is realated to a specific branch, so you can handle this on your own, evaluating better priorities and validity of tests.

**Comment by MV88** [comment]
> In the master PR I renamed it as `RandomUtils` to be more clear. 
About this PR, I think is realated to a specific branch, so you can handle this on your own, evaluating better priorities and validity of tests.

as you suggested is better to have both code aligned. so I'm going to apply same changes

**Comment by MV88** [comment]
> as you suggested is better to have both code aligned. so I'm going to apply same changes

done

**Review by offtherailz — APPROVED** [review]
for me it is ok for a  custom branch that will be removed sooner or later, I should run test locally to verify some errors

**Pull request merged**
