### PR TITLE
Add Dutch translation to mapstore2

### PR DESCRIPTION
**Pull request by gregvds**
## Description
This PR adds the dutch translation
## Issues
 - Fix issue #902

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Feature

**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [x] No

### CODE REVIEW

**Comment by gregvds** [comment]
Any update on this? 

We are eager to have this to go further with our developments :-)

**Comment by mbarto** [comment]
Hi, our idea would be to merge the translations, but not enabling the new language by default (we already have many flags in the settings panel and homepage). Is this ok for you?

**Comment by gregvds** [comment]
Hi,

no problem for us, it would enable us also to show only the languages that we want to use. 
How would this be defined, and where?

**Comment by mbarto** [comment]
You have to add this piece of code in your app.jsx (before everything else):

```
LocaleUtils.setSupportedLocales({
    "it": {
        code: "it-IT",
        description: "Italiano"
    },
    "en": {
        code: "en-US",
        description: "English"
    },
    "fr": {
        code: "fr-FR",
        description: "Français"
    },
    "de": {
        code: "de-DE",
        description: "Deutsch"
    },

    "es": {
        code: "es-ES",
        description: "Español"
    },
    "nl": {
        code: "nl-NL",
        description: "Nederlands"
    }
});
```

**Comment by mbarto** [comment]
Created this one: https://github.com/geosolutions-it/MapStore2/pull/2411
This does not enable dutch by default. I also added a fragment for the cookie notice panel (in english for  now, if you want you can translate that too)

**Comment by gregvds** [comment]
Thanks a lot!

We'll incorporate this asap and add the code to our app.jsx

**Comment by MV88** [comment]
Actually we are working to make this configurable via the extarnal file, without placing it in the app.jsx

follow [this](https://github.com/geosolutions-it/MapStore2/issues/2287) for future updates

**Pull request closed without merging**
