### PR TITLE
#7106 Make map in GeoStory updated on the fly without need to save it…

### PR DESCRIPTION
**Pull request by alexander-fedorenko**
## Description
Make map in GeoStory updated on the fly without need to save it by "Save" button explicitly.
- Removed save button from toolbar.
- Click on close glyph will not trigger discard modal. Instead of it all the changes will be kept as is.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [x] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [x] Other: small changes in feature configuration/workflow

## Issue

**What is the current behavior?**

#7106 

**What is the new behavior?**
Map configuration is updated with no need to use save button.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by alexander-fedorenko** [comment]
One particular issue that I can think of without having explicit save button:
- Open geostory with map that allows to pan; change map viewport (move around to another place);
- Click on "configure map" button, change settings of zoom, panning, but do not pan to another viewport.
- Close map configuration edit mode and save geostory.

User may expect that viewport changed prior to activation of the edit mode will be saved along with new settings of the map, but it won't. New viewport and zoom are written to the config only when panning or zoom happen in edit mode.

Previously such situation was impossible because "Save" button was activated only after some changes of pan/zoom/config in edit mode, so user was not able to save configuration without having panning action.

@tdipisa  what do you think? Should we make viewport position of the map saved into configuration automatically once user enters configuration edit mode? Or we should reset viewport to the stored configuration once user switch to edit mode?

**Comment by dsuren1** [comment]
@alexander-fedorenko 
Code looks fine. Will merge this PR once we have a feeback from @tdipisa for the question above.

**Comment by tdipisa** [comment]
@alexander-fedorenko I understand what you mean. To be coherent with the current UI/UX, I think the second option is the right one and so:

> should reset viewport to the stored configuration once user switch to edit mode?

**Comment by alexander-fedorenko** [comment]
@tdipisa With the recent update map viewport will be moved to the last saved configuration when "Edit map configuration" tool is toggled on.
@dsuren1 please review when it's convenient

**Review by dsuren1 — APPROVED** [review]
LGTM

**Comment by dsuren1** [comment]
@ElenaGallo Kindly test this issue in DEV once deployed and let us know if it's good to be backported to 2022.01.xx

**Pull request merged**
