### PR TITLE
#7717 Contexts tab on home page

### PR DESCRIPTION
**Pull request by alexander-fedorenko**
## Description
Ported geOrchestra changes that allows user to add contexts tab to the home page, customize Home path, patch ResourcesCard component on home page to support conditional display of available tools (used to display custom tools for contexts if it's in featured list)

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#7717 

**What is the new behavior?**
Users have opportunity to activate "Contexts" plugin on home page in order to list contexts in addition to Maps, Geostories and Dashboards.

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information
image

### CODE REVIEW

**Comment by offtherailz** [comment]
Here in [this commit ](https://github.com/geosolutions-it/MapStore2/pull/7718/commits/f5c03beafa8616b37228325909c51d9825b0680b) I fixed the Home plugin to work:
- documented ( I named `miscSettings.homePath` )
- make also other entries work with `homePath` in case that Omnibar is missing. 
-

**Review by offtherailz — CHANGES_REQUESTED** [review]
I did some changes. 

There is one bug not visible in the test environment of geOrchestra: 
- When I open contexts UI, a `*` appears in the search text.
- When I perform a search on home page, the same search text is used in contexts

This because the 2 plugins relies on same state and actions. I suggest to 

- [x] separate the 2 plugins, so they can work independently
- [ ] Make context do not load if the plugin is not present (this should be done also for the other plugins, but for the moment at least this that is not present in default home page should not have side effect when not present.

**Comment by alexander-fedorenko** [comment]
- Search on home page and on contexts manager is divided now.
 - Request to load contexts won't be triggered if "Contexts" plugin is not initialized by entry in localConfig.json

Tests coverage for new selectors, epics, reducers and actions is WIP.
@offtherailz please re-review. Thanks!

**Review by offtherailz — APPROVED** [review]

**Comment by offtherailz** [comment]
@ElenaGallo We don't have any functional changes from this PR. So we can proceed on backport @tdipisa ?

**Comment by tdipisa** [comment]
@ElenaGallo please check this in DEV ant let us know for the backport. It is quite an high priority for a client project.

**Comment by ElenaGallo** [comment]
There are no regressions on the home page, @alexander-fedorenko please backport to 2021.02.xx.

**Pull request merged**
