### PR TITLE
Fix #9620 better error handling of GeoProcessing

### LINKED ISSUE #9603: GeoProcessing - enhance user feedback when certain errors occurs
## Description

We have to improve user notification. In cases where the process raise an exception we should also report it in the popup message. For example when the user tries to intersect a polygon (Intersection layer) with a point (Source layer) the WPS process returns the following exception where a message important for the user that is now not handled (also for this a new issue should be opened on the MS side @MV88 to be implemented now if the effort is small) assigned to @MV88:

```xml
<ows:ExceptionText>
  Process failed during execution
  java.lang.IllegalArgumentException: First feature collection must be polygonal or linear
  First feature collection must be polygonal or linear
</ows:ExceptionText>
```

Corresponding request to this output is here
[Full error response - point layer as source layer.txt](https://github.com/geosolutions-it/MapStore2/files/12915771/Full.error.response.-.point.layer.as.source.layer.txt)

**What kind of improvement you want to add?** (check one with "x", remove the others)
- [ ] Minor changes to existing features
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

### LINKED ISSUE #9620: GeoProcessing - Enhance error handling use cases
## Description

There are some cases when the collectgeometries fails or when getting the features list fails that were not properly handled
you can use this map https://dev-mapstore.geosolutionsgroup.com/mapstore/#/context/geoprocessing_rev/46470

### Problem 1 - empty intersection
- open gpt tool
- select intersection
- select us states as source layer and pick a feature from it
- select linea costa as intersection layer and pick a feature from it
- click run

### Problem 2.a - error getting feature list (wfs get feature issue)
- open gpt tool
- select buffer
- select "Usa population" as source layer (from gs main)

### Problem 2.b - error with collect geom process (using buffer tool) that make the entire process fail (wfs get feature issue)
- open gpt tool
- select buffer
- choose "Usa population" (from gs main)
- click run

### Problem 3 - error with collect geom process (using intersection tool) that make the entire process fail (wfs get feature issue)
- open gpt tool
- select intersection 
- choose "Usa population" (from gs main) as source layer
- choose "Manhattan" (from gs main) as intersection layer
- click run

*Expected Result*

for all the problems an issue notification must be provided, and the application should never crash

*Current Result*

for all the problems an issue notification is missing, and with problem 1 the application crashes

- [x] Not browser related

<details><summary> <b>Browser info</b> </summary>

(use this site: <a href="https://www.whatsmybrowser.org/">https://www.whatsmybrowser.org/</a> for non expert users)

| Browser Affected | Version |
|---|---|
|Internet Explorer| |
|Edge| |
|Chrome| |
|Firefox| |
|Safari| |
</details>

### PR DESCRIPTION
**Pull request by MV88**
## Description

Error described in the issue now provides a feedback and the app does not crash with specific use case

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

Fix #9620 
Fix #9603

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by offtherailz** [comment]
For sure this exception is not handled.
We have a lot of layers and use cases where things do not work. Use them to test.
[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.10.18-13_06_22.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/83899731-decf-4df3-b6e5-b03a9193b2ad)

I'm going to review this better when you think that all the exceptions are correctly handled

**Review by offtherailz — COMMENTED** [review]
It improved a lot. It works well for me.
Please change the text about the source layer, because a source layer as line is anyway accepted.

Question:
I tried an intersection between raoads and streams, I have no results (theoretically I should have some points)
I tried an intersection between roads and roads, it worked. 

I think this is a bug/missing feature of the process.

**Review by offtherailz — APPROVED** [review]

**Comment by ElenaGallo** [comment]
Test passed @MV88 please backport to the stable branch. Thanks

**Comment by MV88** [comment]
backport here https://github.com/geosolutions-it/MapStore2/pull/9630

**Pull request merged**
