### PR TITLE
#9823: Fix - [Annotations] Disabled annotations are printed

### PR DESCRIPTION
**Pull request by dsuren1**
## Description
This PR excludes features hidden in annotation layers from getting printed

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix

## Issue

**What is the current behavior?**
- #9823 

**What is the new behavior?**
The hidden features of annotation layers are not printed 

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by offtherailz — APPROVED** [review]
the code LGTM. Didn't tested, but I'll code looks ok.

**Comment by offtherailz** [comment]
@ElenaGallo, could you please test this on  DEV when deployed ? Thank you

**Comment by ElenaGallo** [comment]
Test passed, @dsuren1 please backport to 2023.02.xx. Thanks

**Comment by ElenaGallo** [comment]
Test passed, @dsuren1 please backport to the 2023.02.xx. Thanks

**Comment by dsuren1** [comment]
@ElenaGallo This has to be tested in QA as this PR merges the fix directly to stable. Thanks!

**Pull request merged**
