### PR TITLE
#8755 Multivariable charts

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description

This PR introduces the concept of multi traces in chart widgets. Changes included in the PR:

- refactor of the json structure of the chart widget to support multiple traces. Here the json [schema.zip](https://github.com/geosolutions-it/MapStore2/files/13116745/charts-schema.zip), i was not able to include it in the docs bacause the [tested plugin](https://pypi.org/project/mkdocs-schema-reader/) does not allow references with multiple files and this other [one](https://github.com/adobe/jsonschema2md) generates too many files that I would prefer to not commit directly into the repo
- refactor of the UI removing advanced options and specifying the section and dividing traces from axis configuration
- refactor of chart styling to allow more color options and to align the UI to the style editor one
- refactor of chart data logic too support parallel request

#### multiple lines and axis configuration

https://github.com/geosolutions-it/MapStore2/assets/19175505/7697e2c1-e4f6-4c6d-a869-74c41a0d1543

#### multiple bars and style configuration

https://github.com/geosolutions-it/MapStore2/assets/19175505/86a706db-1e41-4715-9460-aa941e07efe4

#### multiple pie charts and dynamic classification

https://github.com/geosolutions-it/MapStore2/assets/19175505/e4c06c2c-255c-42e3-8c31-0b25f8776086

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [x] Feature

## Issue

**What is the current behavior?**

#8755

**What is the new behavior?**

Add support for multiple traces in charts

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [x] No

## Other useful information

```[tasklist]
### Additional enhancements
- [ ] Improve the custom style popover showing better the loading phases and the clear action
- [ ] Improve requests management in multiProtocolChart HOC (avoid request if already completed, merge request if possible, ...)
- [ ] Allow to visualize valid traces in chart with a warning. Currently the chart is visible only if all the traces are valid
```

### CODE REVIEW

**Comment by offtherailz** [comment]
Here some of my findings. I'm saving them in a comment for tomorrow to continue the testings

- [ ] stacked option do not work
image

- [ ] Pie charts on different axis looks to be stacked, they should be grouped. The stacking option do not influences it (Because is part of the trace, stacking correctly only the elements of the same trace). 
image

- [ ] when you open a new trace, the preview returns an error. Usually it shows a sample chart. The message is quite good but the error icon is scaring. 

[new_trace_errro.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/c2e9c74d-0569-4dd5-93d9-41fcbf6a7743)

- [ ] When I have strings on y axis, I have a nan in labels on bar chart
image

### Attachments 

- Configs of stacked chart bugs [stacked.zip](https://github.com/geosolutions-it/MapStore2/files/13121360/stacked.zip)
- config with NaN error [NaN.zip](https://github.com/geosolutions-it/MapStore2/files/13121716/NaN.zip)

**Review by offtherailz — CHANGES_REQUESTED** [review]
Here some of my findings. 

You can start fixing the bugs or define issues to solve later


- [x] stacked option do not work
image

- [x] Pie charts on different axis looks to be stacked, they should be grouped. The stacking option do not influences it (Because is part of the trace, stacking correctly only the elements of the same trace). 
image

**In general looks like layout section should splitted in:
- Layout tab, common for all charts, should be an external tab, as well as "Axes" (depending on the chart type anyway for bar mode etc...). Future we can organize it adding stackgroups, offsetgroups etc...
- An Axes section of the trace, refering the axes for the current trace.

- [x] when you open a new trace, the preview returns an error. Usually it shows a sample chart. The message is quite good but the error icon is scaring. I suggest to avoid to show the track until is misconfigured show a less warning icon. Is hard to understand that you have to delete or complete the incomplete trace to have the chart working again. 

[new_trace_errro.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/c2e9c74d-0569-4dd5-93d9-41fcbf6a7743)

- [ ] When I have strings on y axis, I have a nan in labels on bar chart
image

- [x] The  button  for clearing style customization should have a tooltip, is not clear it's role (maybe also because it is a trash that sounds like delete, not clear. a brush icon is more intuitive, but the tooltip should be there anyway)

[screencast-localhost_8081-2023.10.24-19_05_04.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/e8b62031-1ff8-459d-ae47-37b175bb4a05)

- [x] Also these buttons should have tooltips like: "Edit the chart title", "Edit the trace title", "Add a new trace", "delete the selected trace", "Select a different layer" (layer icon, maybe, or layer add), "filter the layer" (layer filter icon may be a good option too, even if a little redundant, in a so complex UI it helps)
image

- [x] the selector and the inputs styles overlap
image

- [x] "Tab title of "Axis" should be "Axes" (it contains x, y so it is plural). 
- [x] "Trace data" or "data" instead of "Configure data", not uniform with the rest of the labels.( i should remove "Configure "). See below the improvemnt suggested.


### Improvements

This section contains improvements that for sure can be done later, or that need a discussion.

- [x] I should remove `[ Trace 1 ]` `[Trace 2]` it takes space for no reason. I show it (grayed out) only if the title is not inserted. 
- [ ] hard to understand that the trace options below are related to the trace, maybe because of the sticky scrolling.
Maybe using labels like:
- Trace data ( i should remove "Configure ")
- Trace style 
- Trace axes (new option, instead of adding to layout) **Layout** is in common with all the traces, so is should stay in another tab, isn't it? 
- Value format
Another option is to have a layout like this, that is more descriptive.
image

Can help to have a better understanding?  
- A little misalignment between combo and buttons, that should be part of the combo somehow ( hard to understand note in the picture refers to tooltips).
image
- [ ] The same for axis settings, is a little hard to understand that where the options are dedicated for one axis and what are global. Maybe "Y axis vallue formatting" look to be global. 
- [ ] For the documentation of the json format, I should move the things in another issue from now.  
- [ ] the first new axis should be on the opposite side of the first one, to avoid the user to manually configure it every time. Even right by default on add can be ok. 
- [ ] The tooltip of the button for "go next step" on top tells me that one or more charts are invalid, but I don't have information about the reason or what charts/traces are invalid, maybe instead of indicating [Trace N] an icon on the right may show in the trace selector the trace that is invalid. This can be an improvement
[screencast-localhost_8081-2023.10.25-10_01_09.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/e9a60dde-6e13-4d05-bc25-973db19a9ee2)
 - [ ] I tried to create a real life example with 2 axis. Km<sup>2</sup> and people. The result is in the video. bbasically the things that do not work are stacking is randomic, thing that I already notified. I think this can be a good real world example to test this functionality, so I attach my result json that I produced (maybe we will have to adjust stacking). Ideally we should be able to: 
     - stack male/female while global population stays aside (grouped)
     - stack land and water km
     - Being able to add some other items to population.  

[screencast-localhost_8081-2023.10.25-10_01_09.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/e9a60dde-6e13-4d05-bc25-973db19a9ee2)

- It could be useful to be able to sort traces in the future to avoid the needing to recreate traces to properly sort them up
image



### Attachments 

- Configs of stacked chart bugs [stacked.zip](https://github.com/geosolutions-it/MapStore2/files/13121360/stacked.zip)
- config with NaN error [NaN.zip](https://github.com/geosolutions-it/MapStore2/files/13121716/NaN.zip)
- population (total, male, female) / surface (land km, water km) chart.
[male_km2.zip](https://github.com/geosolutions-it/MapStore2/files/13163072/male_km2.zip)

**Comment by tdipisa** [comment]
@offtherailz Thank you so much.

I had a call with @allyoucanmap to review what reported above together. Some points will remain outfor the moment and new issues will be opened for future enhancement. Anyway, the most relevant/important ones (the most part in practice) will be worked by @allyoucanmap that will provide a new update by tomorrow morning with a comment indicating what done point by point above.

**Comment by allyoucanmap** [comment]
@offtherailz @tdipisa I applied the requested changes but the following:

> - Layout tab, common for all charts, should be an external tab, as well as "Axes" (depending on the chart type anyway for bar mode etc...). Future we can organize it adding stackgroups, offsetgroups etc...

For the moment I kept it in the trace tab changing the name of other section as requested. We can discuss about this new tab to include additional options for the future

> - [ ]  When I have strings on y axis, I have a nan in labels on bar chart

The NaN issue was not introduced by this work. The reason is because we are always assuming that the aggregation property is always a number and always a y axis. The hover template of the axis add a default formatting assuming the y is a number (eg see [here](https://github.com/geosolutions-it/MapStore2/blob/2023.02.xx/web/client/components/charts/WidgetChart.jsx#L369))

>  - [ ] For the documentation of the json format, I should move the things in another issue from now.

We need to think on how integrate this inside the doc, as I mentioned in the PR description I tried some plugin but they are not working well

> - It could be useful to be able to sort traces in the future to avoid the needing to recreate traces to properly sort them up

I agree that the sorting option could be helpful

**Review by offtherailz — CHANGES_REQUESTED** [review]
- [ ] When selecting classification style I have a crash

[screencast-localhost_8081-2023.10.26-17_41_29.webm](https://github.com/geosolutions-it/MapStore2/assets/1279510/b7503ffb-2fbf-476b-84d7-5a6b154af7ea)

Error in console:

```
react-dom.development.js:501 Uncaught TypeError: Cannot read properties of undefined (reading 'method')
    at Object.onChange (ChartClassification.jsx:334:129)
    at Select.setValue (react-select.es.js:1290:16)
    at Select.clearValue (react-select.es.js:1379:9)
    at HTMLUnknownElement.callCallback (react-dom.development.js:362:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:411:16)
    at invokeGuardedCallback (react-dom.development.js:466:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:480:25)
    at executeDispatch (react-dom.development.js:612:3)
    at executeDispatchesInOrder (react-dom.development.js:634:7)
    at executeDispatchesAndRelease (react-dom.development.js:743:5)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:752:10)
    at forEachAccumulated (react-dom.development.js:724:8)
    at runEventsInBatch (react-dom.development.js:769:3)
    at runExtractedPluginEventsInBatch (react-dom.development.js:914:3)
    at handleTopLevel (react-dom.development.js:5848:5)
    at batchedEventUpdates$1 (react-dom.development.js:24343:12)
```
- [ ] On the video above you can notice that classification attribute has an x but it can not be cleared. Remove the `x`.
- [ ] On the video above you can see the custom classification table is misaligned when the value is a number
- [x] Creating multiple pie chart, the 4th for some reason is not visible. 
image
- [x] Editing the title of the trace do not work until the chart is fully set up. Instead it should be edited.



### Additional notes

- [x] the first impression of the new UI for notifiyng missing attribute works well but it looks to "WARNING" style :smile: . We should do a better design to indicate mandatory values and when compiled and made invalid again, then notify the error. 

image

**Review by offtherailz — APPROVED** [review]
:+1:

**Comment by tdipisa** [comment]
@offtherailz please create tasklist for further identified improvements and assign it to me please.

**Comment by ElenaGallo** [comment]
@allyoucanmap @tdipisa Here are some notes after my tests. I use [this dash](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/dashboard/46719)

- 1_ In Counter, the Use dropdown menu is under the other options

https://github.com/geosolutions-it/MapStore2/assets/56537133/7968f4fa-c715-4712-a955-f4ff2d1b7292

- 2_ The Y axis is not visible if I select the Right Side option and the chart legend is enabled

https://github.com/geosolutions-it/MapStore2/assets/56537133/4748485e-442a-4ec4-8d6f-eaf370a33b7c

- 3_The Filter layer option on Trace data does not work

https://github.com/geosolutions-it/MapStore2/assets/56537133/53a64e36-1512-4e86-9ba9-d9f2744004ca

- 4_ It is not possible to choose a different Outline color for the different Trace

https://github.com/geosolutions-it/MapStore2/assets/56537133/3a076107-0ed7-411e-b9cc-d402b4d5a73c

- 5_ In some cases, some ctraces are not clearly visible. It would be nice to have the ability to change the position of the traces.

https://github.com/geosolutions-it/MapStore2/assets/56537133/09e09c5e-2e35-4a28-a6df-743e6fe2f679

- 6_ If the widget has more that one charts, the charts name are not visible on the dorpdown menu.
**On DEV**
https://github.com/geosolutions-it/MapStore2/assets/56537133/5af5168f-96c9-4330-ae95-62d76f24ecb6

**On QA**
6_qa

- 7_ It is not possible to filter the charts with the table
Error on console:
> POST https://gs-stable.geosolutionsgroup.com/geoserver/wfs?service=WFS&outputFormat=json&authkey=0ccfa42c-cb08-466a-95f4-2cc814c7fd7e net::ERR_CONNECTION_RESET

https://github.com/geosolutions-it/MapStore2/assets/56537133/f9046381-8da7-459b-ade8-f1fdfe48d87f

**Comment by ElenaGallo** [comment]
@allyoucanmap points 1, 3 and 7 now work

**Comment by offtherailz** [comment]
Relevent things to fix only point 6 for the moment. 
Excluding 1,3, 7 i listed the remaining points in this issue for a re-check, here https://github.com/geosolutions-it/MapStore2/issues/9665

**Pull request merged**
