### PR TITLE
C125-157: Length Measurement - Enhancement

### PR DESCRIPTION
**Pull request by dsuren1**
## Description
Length measurement enhancement and text labels display with length and bearing info with the option to configure it via localconfig

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue
#5746
**What is the current behavior?**
The label on the line segment was displayed only with length measurement info

**What is the new behavior?**
https://github.com/geosolutions-it/austrocontrol-C125/issues/157

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Comment by dsuren1** [comment]
Hi @offtherailz 
- For now, I have fixed and updated the second and third review comments. 
- Based on your suggestion of discussion with @tdipisa , I will proceed with the label text angle correction comment.
Kindly advise if you have an alternative suggestion. Thanks!

**Comment by dsuren1** [comment]
> If I can propose, the simplest solution for me is to avoid rotation at all (calculate the effective tangent to the line can become complicated) and support this feature when it is converted to annotation.

@offtherailz 
Current version of Mapstore supports text rotation via annotation. 
It is safe to say that rotation can be handled as you have suggested above. In that case, shall I go ahead and remove the rotation while drawing line then?

**Comment by offtherailz** [comment]
Yes @dsuren1 we can proceed removing rotation and allowing to handle it via annotation.

**Comment by offtherailz** [comment]
Now there is a conflict, can you please fix it, so I can test it? thanks

**Review by offtherailz — APPROVED** [review]
I only noticed than when I export measure as annotation I see the line element as point, but this is a pre-existing bug (the same happens on the current stable, with old design, si I'll open a separate issue for that.

**Pull request merged**
