### PR TITLE
#6179: Deactivate swipe tool on location change

### PR DESCRIPTION
**Pull request by AGMETEOR**
## Description

This PR addresses this [comment](https://github.com/geosolutions-it/MapStore2/issues/6179#issuecomment-735877274)

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**

#6179 

**What is the new behavior?**

On location change deactivate swipe tool if it was active

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by MV88 — CHANGES_REQUESTED** [review]
the PR is good per se, but we are using too much epics even when they are not needed.

in this simple case this could have been solved with a new case in the swipe reducer.
we should try to minimize the use of epics since they are handful to manage side effects (which are considered "bad" things")

may I ask if you can move the current implementation to the reducer?

also i want ot ask to my colleagues what do they think
@mbarto @allyoucanmap @offtherailz

**Comment by offtherailz** [comment]
@MV88 I agree, but location change is not properly plugin logic, but app logic. For this reason I personally like also this solution, but what you say is correct, we can do it in a simpler way by resetting the reducer.

**Comment by mbarto** [comment]
@offtherailz @MV88 looking here: https://github.com/geosolutions-it/MapStore2/blob/ff233b7bb63fdc2f0f7571773a7e70cd88806ed0/web/client/plugins/Swipe.jsx#L16

To me it looks like both the reducer and the epic are included at the plugin level, not at the application level

**Comment by MV88** [comment]
> but location change is not properly plugin logic, but app logic

@offtherailz

is your point but to seems more logical to place the logic inside the plugin,
try to change the perspective.
"Me swipe plugin, what i need to do when it happen a location change? i need to reset my flags."

in this way you delegate to the plugin the behaviour of clean up procedures and so on

**Comment by AGMETEOR** [comment]
@MV88 what's final verdict from the discussion above?

**Comment by offtherailz** [comment]
@mbarto @MV88 Yes, the result is the same. I see reducers more "core", so seeing routing stuff inside them makes me wander "what if I don't have react-redux".
I can easly remove the epic from the plugin, It is less easy to remove the logic from the reducer. For this reason only I prefer epic solution, and in general I prefer to see less actions as possible in the reducer coming from other plugins/stuff...
 But is ok and works in both ways.  No strong opinion, proceed as you want

**Pull request merged**
