### PR TITLE
Fix 4382 Mobile - GetInfo areonautical coordinates display problem

### PR DESCRIPTION
**Pull request by kasongoyo**
## Description
see title

## Issues
 - #4382 
 - ...

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)

 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

**What is the current behavior?** (You can also link to an open issue here)
see #4382 

**What is the new behavior?**
aaaa

**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [ ] Yes, and I documented them in migration notes
 - [ ] No

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by kasongoyo** [comment]
@MV88 I tested against few devices and I couldn't see the problem anymore. I tested against the following devices

- **iPhone 4 through chrome mobile mode** 
Screenshot 2019-12-05 at 11 20 35

- **iPhone 5/6/7 through chrome mobile mode**
Screenshot 2019-12-05 at 11 20 50


- **Android One Plus through real device**
aaa

Please let me know what devices are failing, I guess the reporter of the issue used iphone and that's why I was satisfied after seeing it works with iphone 4 which is smallest screen phone compared to almost all other phones. I also tested against samsung galaxy s6, note 8 etc

**Comment by MV88** [comment]
> the fields overlaps and i cannot see the prime field, only degress and seconds.
4582 - missing a field

**Comment by MV88** [comment]
actually this is the situation
image

**Comment by MV88** [comment]
This was introducing also some regression in the style of coordinate editor, like it was removing the font Menlo and the borders.. 

closing in favor of 
https://github.com/geosolutions-it/MapStore2/pull/4631

**Pull request closed without merging**
