### PR TITLE
#10040 ArcGIS Interoperability - ArcGIS MapServer Catalog and Layer support

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description

This PR introduces a new `arcgis` layer type to support ArcGIS Rest MapServer services

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Feature

## Issue

**What is the current behavior?**

#10040

**What is the new behavior?**

A new `arcgis` layer type has been added to support ArcGIS Rest MapServer services

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)

 - [x] No

## Other useful information

Endpoints for testing https://sampleserver6.arcgisonline.com/arcgis/rest/services

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
I only found an issue testing the services below to check. The code is super-clear. I see also some good improvements 
Test done:
- Catalog: works : 
   - [x] https://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer
   - [x] https://sampleserver6.arcgisonline.com/arcgis/rest/services/911CallsHotspot/MapServer **Failing** <--
   - [x] Identify (serverla test with mixed layer, all consistent
   - [x] Layer properties. Minimal, but working
   - [x]  Print. Tested mixing layer of several types. It works. 


# Other things / questions
- [ ] Legend support is missing, but not mentioned
- [ ] What about the auth key suggested in the original issue. Is there a separate issue or you don't want to integrate it? 
- [ ] How I test for leaflet right now?
- [ ] I found that the annotations icon  print is not working, but I think it is not related to this. Just mention my finding

image

**Comment by allyoucanmap** [comment]
@offtherailz @tdipisa 

> https://sampleserver6.arcgisonline.com/arcgis/rest/services/911CallsHotspot/MapServer Failing <--

About this I tried and I'm able to see it, the only issue I'm seeing is the missing supported projection that is ESRI:102726.

Note: we are assuming EPSG in the message and maybe we should review the authorities support in the core

image

I found other two issue releted to bounding box and identify using https://sampleserver6.arcgisonline.com/arcgis/rest/services/SampleWorldCities/MapServer

1) selecting a feature near the IDL select all the features on the same latitude

image

2) Using the identify `Zoom to feature` action does not work if the bounding box of the selected features exceed the maximum extent of the map projection

image

Both above issues has been solved by this commit 78f88d7d5a0f3d353805c39353adca4ff0032b85

Note: I think a similar problem to the first one could happen also for WMS layer. In that case we could apply the same function implemented to solve this

It has been introduced a minimal support for ImageServer service to make the layer works on geonode istances with this commit 35a528f081501da2ebe90335d152790b3c96d4c2  

# Other things / questions

> How I test for leaflet right now?

I think the only way is to configure it manually

> I found that the annotations icon print is not working, but I think it is not related to this. Just mention my finding

I did a quick test and the client send the image as base64, I think we should investigate this in a separate issue

**Comment by ElenaGallo** [comment]
@allyoucanmap 

1_ If I set the Resolution as the Limits type, when I reopen the settings panel the Limits type changes to Scale

https://github.com/geosolutions-it/MapStore2/assets/56537133/2e6461e5-d5d4-425a-93b0-789c4911d7d3


2_If I set EPSG:4326 like map projection than the layer is not visible on Print preview


https://github.com/geosolutions-it/MapStore2/assets/56537133/97f621b9-5583-423a-aa12-c9d791d7fa6c

**Comment by ElenaGallo** [comment]
@tdipisa point one of the comment above also applies to other services and is also present on prod. Do I have to open an issue or is this correct?

**Comment by tdipisa** [comment]
@ElenaGallo 

>@tdipisa point one of the comment above also applies to other services and is also present on prod. Do I have to open an issue or is this correct?

a dedicated issue should be opened for this, of course. Thank you.

**Comment by ElenaGallo** [comment]
@tdipisa new issue https://github.com/geosolutions-it/MapStore2/issues/10355

**Comment by allyoucanmap** [comment]
@ElenaGallo @tdipisa the issue number 2 (https://github.com/geosolutions-it/MapStore2/pull/10330#issuecomment-2124672457) has been fixed here https://github.com/geosolutions-it/MapStore2/pull/10354

**Pull request merged**
