### PR TITLE
Improve localization strings

### PR DESCRIPTION
**Pull request by MaelREBOUX**
## Description

This PR to propose some enhancement on some strings visible in the UI

See https://github.com/geosolutions-it/MapStore2/issues/6843#issuecomment-848632106

May be discussed.

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
Hi, one thing to change

- [ ] We should leave "Search by location Name"  for MapStore. (for all the languages):
 It is consistent with the menu. (search by --> locatioon name, coordinate, bookmark)
image

Of course you can put this customization in your project, if you prefer (take into account this menu, anyway)

Of course if you think that the translation in french should be improved, you can do it. 


thank you very much for your contribution :+1:

**Comment by MaelREBOUX** [comment]
I revert the commit.

**Review by MaelREBOUX — COMMENTED** [review]
I revert this commit

**Review by MaelREBOUX — COMMENTED** [review]
I revert this commit

**Review by offtherailz — APPROVED** [review]

**Pull request merged**
