### PR TITLE
Add base support for 3d tiles layers

### PR DESCRIPTION
**Pull request by allyoucanmap**
## Description

This PR includes:

- refatcor of catalog API
- add 3D tiles layer in cesium
- add 3D tiles catalog service type

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Feature

## Issue

**What is the current behavior?**

#<issue>

**What is the new behavior?**

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by offtherailz — CHANGES_REQUESTED** [review]
- [x] See my comment about proxy (we can open an issue to support authkey and or improve proxy request system in a second time) --> I did it on my own. I also added a test
- [x] I tried to create this map with multiple catalogs and add various layers. At a certain point I'm not able to add layers anymore, or add the same layer more than once. This is a sample map. You can try to click to add button for the catalogs "ge" and "demo1", and see no result. 
[map.zip](https://github.com/geosolutions-it/MapStore2/files/8317382/map.zip)

- [ ] Search doesn't seems to filter consistently. Anyway the source provides only one result, so it can be acceptable somehow. 
- [ ] Differently from the original, we don't have any preset yet. https://github.com/geosolutions-it/MapStore2-C040/issues/519 (OSMBuilding). It's fine for me, just double checking
- [ ] sometimes clicking on search the title of the single record for some reason disappears, please see if you can replicate. 

Please @tdipisa after our call take a look at this too. 

- [x] Moreover, to go in production we need to fix `proxy.properties` accordingly. I'm still investigating on it. In the meanwhile I send you these fixes, so you can work on them --> I did it on my own


## Sample data

This worked for me here:
https://geoportale.comune.genova.it/sites/default/files/field/image/aa5/tileset.json
https://www.cityexplorer3d.com/Genova3D/dataset/tileset.json

wow 
image


I'm not able instead to see data from these tilesets. Did I do something wrong ?

https://demo.geo-solutions.it/share/3dtiles/3d-tiles-samples-main/1.0/


- [ ] We will need to test if this works with the elevation model we have in cesium of C040

**Comment by offtherailz** [comment]
For testing can be useful to create a map with all the data from here:
https://demo.geo-solutions.it/share/3dtiles/3d-tiles-samples-main/1.0/

**Comment by tdipisa** [comment]
@offtherailz it is not part of this implementation

>Differently from the original, we don't have any preset yet. https://github.com/geosolutions-it/MapStore2-C040/issues/519 (OSMBuilding). It's fine for me, just double checking

**Review by offtherailz — APPROVED** [review]
code review is ok. Some tests are failing but for functionality and my testing, it is ok.

**Comment by tdipisa** [comment]
@ElenaGallo can you please test this in DEV and let us know if we can backport

**Comment by ElenaGallo** [comment]
@allyoucanmap @tdipisa

1_ If the visibility limit is set, the 3D layer is no longer displayed even once the tool is disabled.

ok

**How to Reproduce**
- Open [this map](https://dev-mapstore.geosolutionsgroup.com/mapstore/#/viewer/leaflet/38732)
- Set scale to 1:36112
- Enable the 3D
- Select a layer on TOC
- Click on Settings > Display
- Set Max value to 1:36112
 > The layer is no longer displayed
- Zoom in
> The layer is no longer displayed
- Disable the Visibility limits
 > The layer is no longer displayed

**Comment by tdipisa** [comment]
@ElenaGallo please open a dedicated issue for this so, If this is the only thing you found, we can backport for the moment and proceed with a fix early after. This way we can proceed also with testing at project level.

**Comment by ElenaGallo** [comment]
@tdipisa here the new issue #8008, @allyoucanmap please backport to 2022.01.xx. Thanks

**Pull request merged**
