### PR TITLE
Fixed Issue #9627 and associated PR comments

### PR DESCRIPTION
**Pull request by mumairr**
## Description

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [ ] Bugfix
 - [x] Feature
 - [ ] Code style update (formatting, local variables)
 - [ ] Refactoring (no functional changes, no api changes)
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ] Other... Please describe:

## Issue

**What is the current behavior?**
Fix https://github.com/geosolutions-it/MapStore2/issues/9627

**What is the new behavior?**
Draftjs added, allows embedding of links, fonts and image upload can be handled via props

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

## Other useful information

Previous pull request at https://github.com/geosolutions-it/MapStore2/pull/9673 was mistakenly closed. It is linked here for reference of comments, which have been cross checked to work for branch 2022.02.xx

### CODE REVIEW

**Review by allyoucanmap — APPROVED** [review]

**Comment by allyoucanmap** [comment]
please @ElenaGallo test this fix on dev and let us know when we can backport to branch 2022.02.xx for geonode-mapstore-client

**Comment by ElenaGallo** [comment]
Hi @mumairr, some notes after my tests:

1_ In the widget preview, hover over a **Link** a link image is too big 

https://github.com/geosolutions-it/MapStore2/assets/56537133/64d391d4-f86a-4b6e-a31e-dbef85fe00f3

2_ In the widget preview, the scroll down bar is missing

https://github.com/geosolutions-it/MapStore2/assets/56537133/37b1f923-f4ec-4657-a5c5-12bca8619338

3_ The dimensions of the *Embedded link* change from preview to widget (investigate with @tdipisa)
suize

**Comment by mumairr** [comment]
> Hi @mumairr, some notes after my tests:
> 
> 1_ In the widget preview, hover over a **Link** a link image is too big
> 
>  hyperlink.mp4 
> 2_ In the widget preview, the scroll down bar is missing
> 
>  hyperlink_2.mp4 
> 3_ The dimensions of the _Embedded link_ change from preview to widget (Is that correct, @tdipisa?) suize

Hi @ElenaGallo,

1. Fixed, happened due to css properties applied to each img element inside editor if no image is found in link.
2. Unable to replicate the scrollbar error, i added huge text, embedded link and an error image.

Animation

**Comment by ElenaGallo** [comment]
> 2. Unable to replicate the scrollbar error, i added huge text, embedded link and an error image. Let me know if there are specific steps to reproduce it

@mumairr it only happens for the widget created from a map

**Comment by mumairr** [comment]
> > 2. Unable to replicate the scrollbar error, i added huge text, embedded link and an error image. Let me know if there are specific steps to reproduce it
> 
> @mumairr it only happens for the widget created from a map

Alright, fixed up

**Comment by ElenaGallo** [comment]
Test passed, @mumairr please backport to branch 2022.02.xx for geonode-mapstore-client. Thanks

**Pull request merged**
