### PR TITLE
#6126 - Annotations highlight and circle draw fix

### PR DESCRIPTION
**Pull request by dsuren1**
## Description
This PR adds fix to previous annotations remaining highlighted and issue with adding Circle annotations.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Bugfix
 - [x] Code style update (formatting, local variables)

## Issue

**What is the current behavior?**
#6126 

**What is the new behavior?**
- The previous annotations will not stay highlighted unless hovered upon
- Circle annotations can be added without any draw issues

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by MV88 — CHANGES_REQUESTED** [review]
i noticed that when you delete something , you lose the edit interaction and you can recover that editing the field lat lon or by clicking again on the selected one.

honestly i think that the highlight style should be different from the edit style, but this is my opinion

**Comment by dsuren1** [comment]
> i noticed that when you delete something , you lose the edit interaction and you can recover that editing the field lat lon or by clicking again on the selected one.

I think we can just disable the delete buttons on the geometries until the user is out of editing, it makes the scenario more clear and less complex? This will also prevent any cosmetic glitches during these combined actions. Your thoughts @MV88 @tdipisa 

> honestly i think that the highlight style should be different from the edit style, but this is my opinion
 
Yes, it makes sense @MV88 . @tdipisa your thoughts on this. If so, any color preference ?

**Comment by tdipisa** [comment]
@dsuren1 @MV88 I think what we have to do is to manage selections properly

**Comment by MV88** [comment]
> @dsuren1 @MV88 I think what we have to do here is to manage selections properly. I think that introducing now additional behavior could be counterproductive if it isn't strictly necessary.

@dsuren1 
The thing that the highlight is disabling the current edit interaction. this is probably the cause of the thing i noticed. 

please solve this behaviour and test that the edit interactions remain active while you are in that scenario i.e. while having the coordinate editor visible and one feature is selected

**Review by MV88 — APPROVED** [review]

**Pull request merged**
